<?php
declare(strict_types=1);
require_once __DIR__.'/config/bi_step22.php';
$error=null;$user=[];$p=bi_step22_period($_GET['month']??null);$report=(string)($_GET['report']??'summary');$format=(string)($_GET['format']??'html');$allowed=['summary','trends','products','customers','suppliers','signals','targets'];if(!in_array($report,$allowed,true))$report='summary';
try{$pdo=business_db();bi_step22_ensure($pdo);$user=bi_step22_guard($pdo,'bi.export');$ctx=bi_step22_context($pdo);$orgId=(int)$ctx['organization_id'];$m=bi_step22_metrics($pdo,$orgId,$p['start'],$p['end']);$rows=[];$headers=[];
if($report==='summary'){$headers=['Metric','Value','Scope'];foreach(['sales_count'=>'Sales Count','sales_revenue'=>'Sales Revenue','sales_vp'=>'Sales VP','verified_profit'=>'Verified Profit','profit_deferred_sales'=>'Deferred-Cost Sales','collections'=>'Collections','purchase_spend'=>'Purchase Spend','new_leads'=>'New Leads','lead_conversions'=>'Lead Conversions','finance_income'=>'Finance Income','finance_expense'=>'Finance Expense','finance_net'=>'Finance Net','customer_receivable'=>'Customer Receivable','supplier_payable'=>'Supplier Payable','inventory_units'=>'Sellable Inventory Units','inventory_value_known'=>'Known Inventory Value'] as $k=>$label)$rows[]=[$label,$m[$k]??0,in_array($k,['customer_receivable','supplier_payable','inventory_units','inventory_value_known'],true)?'Current exposure':$p['label']];}
elseif($report==='trends'){$headers=['Month','Sales','Revenue','VP','Verified Profit','Deferred Cost Sales','Collections','Purchases','New Leads','Conversions','Finance Net'];foreach(bi_step22_monthly_trends($pdo,$orgId,12) as $r)$rows[]=[$r['label'],$r['sales_count'],$r['sales_revenue'],$r['sales_vp'],$r['verified_profit'],$r['profit_deferred_sales'],$r['collections'],$r['purchase_spend'],$r['new_leads'],$r['lead_conversions'],$r['finance_net']];}
elseif($report==='products'){$headers=['Stock No.','Product','Qty','Revenue','VP','Verified Profit','Costed Lines','Total Lines'];foreach(bi_step22_top_products($pdo,$orgId,$p['start'],$p['end'],50) as $r)$rows[]=[$r['stock_no'],$r['product_name_snapshot'],$r['qty'],$r['revenue'],$r['vp'],$r['verified_profit'],$r['costed_lines'],$r['lines']];}
elseif($report==='customers'){$headers=['Customer','Orders','Revenue','Collected','Receivable'];foreach(bi_step22_top_customers($pdo,$orgId,$p['start'],$p['end'],50) as $r)$rows[]=[$r['customer_name'],$r['orders'],$r['revenue'],$r['collected'],$r['receivable']];}
elseif($report==='suppliers'){$headers=['Supplier','Bills','Billed','Paid','Outstanding'];foreach(bi_step22_top_suppliers($pdo,$orgId,$p['start'],$p['end'],50) as $r)$rows[]=[$r['supplier_name'],$r['bills'],$r['billed'],$r['paid'],$r['outstanding']];}
elseif($report==='signals'){$headers=['Signal','Type','Severity','Detail','Workflow Status'];foreach(bi_step22_signals($pdo,$orgId,$m) as $r)$rows[]=[$r['title'],$r['type'],$r['severity'],$r['detail'],$r['workflow_status']];}
else{$headers=['Code','Target','Metric','Period Start','Period End','Target Value','Actual','Achievement %','Status'];foreach(bi_step22_targets($pdo,$orgId,$p['start'],$p['end'],$m) as $r)$rows[]=[$r['target_code'],$r['target_name'],$r['metric_name'],$r['period_start'],$r['period_end'],$r['target_value'],$r['actual_value'],$r['achievement_pct'],$r['status']];}
if($format==='csv'){bi_step22_log_export($pdo,$orgId,$report,$p['start'],$p['end'],count($rows),(int)$user['id']);header('Content-Type: text/csv; charset=UTF-8');header('Content-Disposition: attachment; filename="HWC-BI-'.$report.'-'.$p['key'].'.csv"');echo "\xEF\xBB\xBF";$out=fopen('php://output','w');fputcsv($out,$headers);foreach($rows as $r)fputcsv($out,$r);fclose($out);exit;}
}catch(Throwable $e){$error=$e->getMessage();$rows=[];$headers=[];}
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>BI Export - Healthcare Wellness Club</title><link rel="stylesheet" href="assets/dashboard.css"><link rel="stylesheet" href="assets/product_pro.css"><link rel="stylesheet" href="assets/bi_step22.css"><style>@media print{.no-print,.os-topbar{display:none!important}.os-main{max-width:none!important}.os-card{border:none!important;box-shadow:none!important}}</style></head><body><header class="os-topbar no-print"><div class="os-topbar-inner"><a class="os-brand" href="executive_bi.php"><img src="../img/logo.png"><span><strong>Healthcare Wellness Club</strong><small>STEP 22 • BI Export</small></span></a><div class="os-top-actions"><a class="os-btn primary" href="executive_bi.php">Executive BI</a></div></div></header><main class="os-main" style="max-width:1500px;margin:auto"><section class="os-hero pp-hero"><div class="os-kicker">MANAGEMENT EXPORT • <?=bi_step22_h($p['label'])?></div><h1>Export exactly the BI view you need.</h1><p>CSV uses live values; Print can be saved as PDF by the browser. Export history records metadata only.</p></section><?php if($error):?><div class="pp-alert bad"><?=bi_step22_h($error)?></div><?php else:?><section class="os-card no-print" style="margin-top:14px"><form method="get" style="display:flex;gap:8px;align-items:end;flex-wrap:wrap"><div><label class="bi-muted">Month</label><input type="month" name="month" value="<?=bi_step22_h($p['key'])?>" style="display:block;padding:9px;border:1px solid #d8dfda;border-radius:10px"></div><div><label class="bi-muted">Report</label><select name="report" style="display:block;padding:9px;border:1px solid #d8dfda;border-radius:10px"><?php foreach($allowed as $r):?><option value="<?=$r?>" <?=$report===$r?'selected':''?>><?=bi_step22_h(ucwords($r))?></option><?php endforeach;?></select></div><button class="os-btn">View</button><a class="os-btn" href="?month=<?=rawurlencode($p['key'])?>&report=<?=rawurlencode($report)?>&format=csv">Download CSV</a><button class="os-btn" type="button" onclick="window.print()">Print / Save PDF</button></form></section><section class="os-card" style="margin-top:14px"><div class="os-title-row"><div><h2><?=bi_step22_h(ucwords($report))?> • <?=bi_step22_h($p['label'])?></h2><p><?=count($rows)?> row(s).</p></div></div><div class="bi-table-wrap"><table class="bi-table"><thead><tr><?php foreach($headers as $h):?><th><?=bi_step22_h($h)?></th><?php endforeach;?></tr></thead><tbody><?php if(!$rows):?><tr><td colspan="<?=max(1,count($headers))?>">No rows in this report.</td></tr><?php endif;?><?php foreach($rows as $r):?><tr><?php foreach($r as $v):?><td><?=bi_step22_h($v===null?'N/A':$v)?></td><?php endforeach;?></tr><?php endforeach;?></tbody></table></div></section><?php endif;?></main></body></html>