<?php
declare(strict_types=1);
require_once __DIR__ . '/config/step10_services.php';
require_once __DIR__ . '/config/product_step12_bridge.php';
$error=null;$legacy=['total'=>0,'mapped'=>0,'pending'=>0];$m=['members'=>0,'vp'=>0,'orders'=>0,'reports'=>0,'followups'=>0,'products'=>0,'prices'=>0,'images'=>0,'quotes'=>0,'sales'=>0,'cancelled'=>0,'paid'=>0.0,'outstanding'=>0.0,'verified_profit'=>0.0,'profit_deferred'=>0];$recent=[];
try{
 $pdo=business_db();$ctx=step10_org_context($pdo);step10_ensure_tables($pdo);product_step12_ensure($pdo);product_step12_bridge_backfill($pdo);$orgId=(int)$ctx['organization_id'];$legacy=step10_legacy_state($pdo,$orgId);$rev=defined('BUSINESS_REVERSED_SOURCE_SHEET')?BUSINESS_REVERSED_SOURCE_SHEET:'Manual Entry • Reversed';
 foreach(['members'=>'members','vp'=>'volume_point_entries','orders'=>'orders'] as $k=>$table){$s=$pdo->prepare("SELECT COUNT(*) FROM `{$table}` WHERE organization_id=? AND COALESCE(source_sheet,'') NOT IN (?,?)");$s->execute([$orgId,$rev,PRODUCT_SALE_REVERSED_SOURCE_SHEET]);$m[$k]=(int)$s->fetchColumn();}
 $s=$pdo->prepare("SELECT COUNT(*) FROM report_definitions WHERE organization_id=? AND is_active=1");$s->execute([$orgId]);$m['reports']=(int)$s->fetchColumn();$s=$pdo->prepare("SELECT COUNT(*) FROM business_followups WHERE organization_id=? AND status='open'");$s->execute([$orgId]);$m['followups']=(int)$s->fetchColumn();
 $pm=product_foundation_metrics($pdo,$orgId);foreach(['products','price_versions','images'] as $k)$m[$k==='price_versions'?'prices':$k]=(int)($pm[$k]??0);$s=$pdo->prepare("SELECT COUNT(*) FROM product_quotes WHERE organization_id=?");$s->execute([$orgId]);$m['quotes']=(int)$s->fetchColumn();
 $sales=product_step12_sales_rows($pdo,$orgId,'all');foreach($sales as $r){if($r['sale_status']==='cancelled'){$m['cancelled']++;continue;}$m['sales']++;$m['paid']+=(float)$r['paid_amount'];$m['outstanding']+=max(0,(float)$r['net_amount']-(float)$r['paid_amount']);if($r['cost_status']==='complete'&&$r['profit_total']!==null)$m['verified_profit']+=(float)$r['profit_total'];else $m['profit_deferred']++;}
 if(business_table_exists($pdo,'audit_logs')){$s=$pdo->prepare("SELECT event_type,entity_type,entity_id,created_at FROM audit_logs WHERE organization_id=? ORDER BY id DESC LIMIT 8");$s->execute([$orgId]);$recent=$s->fetchAll();}
}catch(Throwable $e){$error=$e->getMessage();}
$businessReady=$error===null&&$legacy['total']===757&&$legacy['mapped']===757&&$legacy['pending']===0&&$m['reports']===6;$productReady=$error===null&&$m['products']===64&&$m['prices']>=64;
function dc_money(mixed $v):string{return '₹'.number_format((float)$v,2,'.',',');}
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>Business OS Dashboard - Healthcare Wellness Club</title><link rel="stylesheet" href="assets/dashboard.css"><link rel="stylesheet" href="assets/step10.css"><link rel="stylesheet" href="assets/product_pro.css"></head><body>
<header class="os-topbar"><div class="os-topbar-inner"><a class="os-brand" href="../index.html"><img src="../img/logo.png" alt="Healthcare Wellness Club logo"><span><strong>Healthcare Wellness Club</strong><small>Business OS • STEP 10 + 11 + 12</small></span></a><div class="os-top-actions"><a class="os-btn" href="today_center.php">Today</a><a class="os-btn" href="global_search.php">⌕ Search</a><a class="os-btn" href="product_catalog.php">Products</a><a class="os-btn primary" href="product_sales_center.php">Product Sales</a></div></div></header>
<div class="os-layout"><aside class="os-sidebar"><div class="os-nav-label">Command</div><nav class="os-nav"><a class="active" href="index.php"><i class="dot"></i>Dashboard</a><a href="today_center.php"><i class="dot"></i>Today Center</a><a href="global_search.php"><i class="dot"></i>Global Search</a><a href="alerts_center.php"><i class="dot"></i>Alerts & Follow-ups</a></nav><div class="os-nav-label" style="margin-top:8px">Products & Sales</div><nav class="os-nav"><a href="product_catalog.php"><i class="dot"></i>Product Catalog</a><a href="product_order_builder.php"><i class="dot"></i>Order Builder</a><a href="product_sales_center.php"><i class="dot"></i>Product Sales</a><a href="product_payments.php"><i class="dot"></i>Payments</a><a href="product_cost_center.php"><i class="dot"></i>Cost & Profit</a><a href="product_sales_analytics.php"><i class="dot"></i>Sales Analytics</a><a href="product_sales_export.php"><i class="dot"></i>Sales Export</a><a href="step12_audit.php"><i class="dot"></i>STEP 12 Audit</a></nav><div class="os-nav-label" style="margin-top:8px">Business</div><nav class="os-nav"><a href="operations_center.php"><i class="dot"></i>Operations</a><a href="members.php"><i class="dot"></i>Members & Network</a><a href="data_management.php"><i class="dot"></i>Data Management</a><a href="report_center.php"><i class="dot"></i>Report Center</a><a href="insights_center.php"><i class="dot"></i>Insights</a><a href="data_quality.php"><i class="dot"></i>Data Quality</a><a href="health_center.php"><i class="dot"></i>System Health</a></nav><div class="os-sidebar-status"><b><?= $businessReady&&$productReady?'Business OS live':'Review required' ?></b><span><?= number_format($legacy['mapped']) ?>/757 legacy • <?= number_format($m['products']) ?>/64 products • <?= number_format($m['sales']) ?> active product sales.</span></div></aside>
<main class="os-main"><section class="os-hero s10-hero"><div class="os-kicker">BUSINESS OS • THROUGH STEP 12</div><h1>Business tracking, Product & Price Pro and Product Sales now operate as one traceable system.</h1><p>Catalog prices come from reviewed PDFs; sales flow from quote to Business OS order and report VP; payments track collections; profit appears only with explicit cost; cancellation and restore preserve evidence.</p><div class="os-status-row"><span class="os-chip <?= $businessReady?'good':'' ?>"><?= $businessReady?'STEP 10 COMPLETE':'Business review' ?></span><span class="os-chip <?= $productReady?'good':'' ?>"><?= $productReady?'STEP 11 COMPLETE':'Product review' ?></span><span class="os-chip good">STEP 12 INTEGRATION LIVE</span><span class="os-chip"><?= number_format($m['sales']) ?> active sales</span><span class="os-chip"><?= number_format($m['profit_deferred']) ?> profit deferred</span></div></section><?php if($error):?><div class="pp-alert bad"><strong>Dashboard diagnostic:</strong> <?= step10_h($error) ?></div><?php endif;?>
<section class="s10-kpis"><div class="s10-kpi"><small>Members</small><strong><?= number_format($m['members']) ?></strong><span>Active normalized identities</span></div><div class="s10-kpi"><small>Products</small><strong><?= number_format($m['products']) ?></strong><span>India PDF catalog</span></div><div class="s10-kpi"><small>Product Sales</small><strong><?= number_format($m['sales']) ?></strong><span><?= number_format($m['cancelled']) ?> cancelled preserved</span></div><div class="s10-kpi"><small>Outstanding</small><strong><?= dc_money($m['outstanding']) ?></strong><span><?= dc_money($m['paid']) ?> collected</span></div></section>
<section class="s10-grid"><article class="s10-card s10-span-8"><div class="os-title-row"><div><h2>STEP 12 • Product Sales Workflow</h2><p>Complete daily lifecycle from quote to audited business result.</p></div><a class="os-btn primary" href="product_sales_center.php">Open Sales Center</a></div><div class="os-report-grid"><a class="os-report" href="product_order_builder.php"><div class="os-report-head"><b>1. Build Quote</b><em>PRICE</em></div><span>Exact PDF price, quantity, VP, saving and delivery.</span><small>Build →</small></a><a class="os-report" href="product_sales_center.php"><div class="os-report-head"><b>2. Finalize Sale</b><em>TRACE</em></div><span>Create raw source, Business Order, line items and report VP bridge.</span><small>Finalize →</small></a><a class="os-report" href="product_payments.php"><div class="os-report-head"><b>3. Collect Payment</b><em>MONEY</em></div><span>Unpaid / Partial / Paid without duplicate Income posting.</span><small>Payments →</small></a><a class="os-report" href="product_cost_center.php"><div class="os-report-head"><b>4. Verify Cost</b><em>PROFIT</em></div><span>Actual invoice/cost sheet only; no inferred cost.</span><small>Cost →</small></a><a class="os-report" href="product_sales_analytics.php"><div class="os-report-head"><b>5. Analyze</b><em>LIVE</em></div><span>Revenue, VP, collection, outstanding and verified profit.</span><small>Analyze →</small></a><a class="os-report" href="step12_audit.php"><div class="os-report-head"><b>6. Audit</b><em>SAFE</em></div><span>Lifecycle, report bridge, payment and profit integrity.</span><small>Audit →</small></a></div></article><aside class="s10-card s10-span-4"><h2>Product Sales Health</h2><div class="s10-list"><div class="s10-row"><div><b>Collected</b><small>Active payment records</small></div><strong><?= dc_money($m['paid']) ?></strong></div><div class="s10-row"><div><b>Outstanding</b><small>Still to collect</small></div><strong><?= dc_money($m['outstanding']) ?></strong></div><div class="s10-row"><div><b>Verified Profit</b><small>Full explicit cost only</small></div><strong><?= dc_money($m['verified_profit']) ?></strong></div><div class="s10-row"><div><b>Profit Deferred</b><small>Missing cost coverage</small></div><strong><?= number_format($m['profit_deferred']) ?></strong></div></div></aside>
<article class="s10-card s10-span-7"><div class="os-title-row"><div><h2>Business Workspaces</h2><p>Legacy and MANUAL operations remain intact.</p></div><a class="os-btn" href="operations_center.php">Operations</a></div><div class="os-links"><a class="os-link" href="operations_center.php"><div><b>Operations Center</b><span>Orders, VP, Income and Royalty including active Product Sales</span></div><span>→</span></a><a class="os-link" href="report_center.php"><div><b>Six Live Reports</b><span>Product Sale VP arrives through a source-traced report bridge</span></div><span>→</span></a><a class="os-link" href="data_management.php"><div><b>Data Management</b><span>Manual Create → Correct → Reverse → Restore → Audit</span></div><span>→</span></a><a class="os-link" href="product_sales_export.php"><div><b>Product Sales Export</b><span>Filtered UTF-8 CSV + Print/Save PDF</span></div><span>→</span></a></div></article><aside class="s10-card s10-span-5"><h2>Recent Audit Activity</h2><div class="s10-list"><?php foreach($recent as $a):?><div class="s10-row"><div><b><?= step10_h(ucwords(str_replace('_',' ',(string)$a['event_type']))) ?></b><small><?= step10_h((string)($a['entity_type']??'system')) ?><?= $a['entity_id']?' #'.(int)$a['entity_id']:'' ?></small></div><strong><?= step10_h(substr((string)$a['created_at'],5,11)) ?></strong></div><?php endforeach;?><?php if(!$recent):?><div class="s10-row"><div><b>No recent audit events</b></div></div><?php endif;?></div></aside></section>
<div class="os-footer-note"><strong>Source-of-truth:</strong> STEP 12 does not rewrite the 757 legacy rows. Product Sales use PRODUCT-SALES raw evidence, quote/order snapshots, explicit cost versions and append-only lifecycle audit.</div></main></div></body></html>