<?php
declare(strict_types=1);
require_once __DIR__ . '/config/step10_services.php';
require_once __DIR__ . '/config/product_step12_bridge.php';

$error=null;$legacy=['total'=>0,'mapped'=>0,'pending'=>0];$m=['members'=>0,'products'=>0,'sales'=>0,'cancelled'=>0,'outstanding'=>0.0,'verified_profit'=>0.0,'stock'=>0.0,'stock_value'=>0.0,'low'=>0,'out'=>0,'expiring'=>0,'pending_sync'=>0,'batches'=>0];$recent=[];
try{
 $pdo=business_db();$ctx=step10_org_context($pdo);step10_ensure_tables($pdo);product_step12_ensure($pdo);product_step12_bridge_backfill($pdo);inventory_step13_ensure($pdo);$orgId=(int)$ctx['organization_id'];$legacy=step10_legacy_state($pdo,$orgId);$rev=defined('BUSINESS_REVERSED_SOURCE_SHEET')?BUSINESS_REVERSED_SOURCE_SHEET:'Manual Entry • Reversed';
 $s=$pdo->prepare("SELECT COUNT(*) FROM members WHERE organization_id=? AND COALESCE(source_sheet,'')<>?");$s->execute([$orgId,$rev]);$m['members']=(int)$s->fetchColumn();$pm=product_foundation_metrics($pdo,$orgId);$m['products']=(int)($pm['products']??0);
 foreach(product_step12_sales_rows($pdo,$orgId,'all') as $r){if($r['sale_status']==='cancelled'){$m['cancelled']++;continue;}$m['sales']++;$m['outstanding']+=max(0,(float)$r['net_amount']-(float)$r['paid_amount']);if($r['cost_status']==='complete'&&$r['profit_total']!==null)$m['verified_profit']+=(float)$r['profit_total'];}
 $locationId=inventory_step13_location_id($pdo,$orgId);foreach(inventory_step13_stock_rows($pdo,$orgId,$locationId) as $r){$m['stock']+=(float)$r['sellable_stock'];$m['stock_value']+=(float)$r['known_value'];if((bool)$r['track_stock']&&(float)$r['sellable_stock']<=0.0005)$m['out']++;if((float)$r['reorder_level']>0&&(float)$r['sellable_stock']<=(float)$r['reorder_level']+0.0005)$m['low']++;if($r['next_expiry']){$days=(int)floor(((new DateTimeImmutable((string)$r['next_expiry']))->getTimestamp()-(new DateTimeImmutable('today'))->getTimestamp())/86400);if($days>=0&&$days<=(int)$r['expiry_alert_days'])$m['expiring']++;}}
 $m['pending_sync']=count(inventory_step13_pending_sales($pdo,$orgId));$s=$pdo->prepare("SELECT COUNT(*) FROM inventory_batches WHERE organization_id=? AND location_id=? AND status='active' AND current_quantity>0");$s->execute([$orgId,$locationId]);$m['batches']=(int)$s->fetchColumn();
 if(business_table_exists($pdo,'audit_logs')){$s=$pdo->prepare("SELECT event_type,entity_type,entity_id,created_at FROM audit_logs WHERE organization_id=? ORDER BY id DESC LIMIT 8");$s->execute([$orgId]);$recent=$s->fetchAll();}
}catch(Throwable $e){$error=$e->getMessage();}
$ready=$error===null&&$legacy['total']===757&&$legacy['mapped']===757&&$legacy['pending']===0&&$m['products']===64;
function d13_h(mixed $v):string{return htmlspecialchars((string)$v,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8');}function d13_n(mixed $v):string{$x=number_format((float)$v,3,'.','');return rtrim(rtrim($x,'0'),'.');}function d13_m(mixed $v):string{return '₹'.number_format((float)$v,2,'.',',');}
?>
<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>Business OS Dashboard - Healthcare Wellness Club</title><link rel="stylesheet" href="assets/dashboard.css"><link rel="stylesheet" href="assets/step10.css"><link rel="stylesheet" href="assets/product_pro.css"></head><body>
<header class="os-topbar"><div class="os-topbar-inner"><a class="os-brand" href="../index.html"><img src="../img/logo.png" alt="logo"><span><strong>Healthcare Wellness Club</strong><small>Business OS • THROUGH STEP 13</small></span></a><div class="os-top-actions"><a class="os-btn" href="global_search.php">⌕ Search</a><a class="os-btn" href="product_sales_center.php">Sales</a><a class="os-btn primary" href="inventory_center.php">Inventory</a></div></div></header>
<div class="os-layout"><aside class="os-sidebar"><div class="os-nav-label">Command</div><nav class="os-nav"><a class="active" href="index.php"><i class="dot"></i>Dashboard</a><a href="today_center.php"><i class="dot"></i>Today Center</a><a href="global_search.php"><i class="dot"></i>Global Search</a></nav><div class="os-nav-label" style="margin-top:8px">Products & Sales</div><nav class="os-nav"><a href="product_catalog.php"><i class="dot"></i>Product Catalog</a><a href="product_order_builder.php"><i class="dot"></i>Order Builder</a><a href="product_sales_center.php"><i class="dot"></i>Product Sales</a><a href="product_payments.php"><i class="dot"></i>Payments</a><a href="product_cost_center.php"><i class="dot"></i>Cost & Profit</a></nav><div class="os-nav-label" style="margin-top:8px">Inventory</div><nav class="os-nav"><a href="inventory_center.php"><i class="dot"></i>Inventory Center</a><a href="inventory_inward.php"><i class="dot"></i>Stock Inward</a><a href="inventory_adjustments.php"><i class="dot"></i>Damage / Returns</a><a href="inventory_stocktake.php"><i class="dot"></i>Stocktake</a><a href="inventory_settings.php"><i class="dot"></i>Reorder Settings</a><a href="inventory_analytics.php"><i class="dot"></i>Inventory Analytics</a><a href="step13_audit.php"><i class="dot"></i>STEP 13 Audit</a></nav><div class="os-nav-label" style="margin-top:8px">Business</div><nav class="os-nav"><a href="operations_center.php"><i class="dot"></i>Operations</a><a href="members.php"><i class="dot"></i>Members</a><a href="data_management.php"><i class="dot"></i>Data Management</a><a href="report_center.php"><i class="dot"></i>Reports</a></nav></aside>
<main class="os-main"><section class="os-hero s10-hero"><div class="os-kicker">BUSINESS OS • STEP 10 + 11 + 12 + 13</div><h1>Business, Products, Sales and Inventory now operate as one traceable workflow.</h1><p>Product Sale finalization checks stock, deducts valid batches using FEFO, cancellation returns stock, restore deducts again, and inventory movements remain source-traced.</p><div class="os-status-row"><span class="os-chip <?= $ready?'good':'' ?>"><?= $ready?'BUSINESS OS LIVE':'Review required' ?></span><span class="os-chip good">STEP 10 COMPLETE</span><span class="os-chip good">STEP 11 COMPLETE</span><span class="os-chip good">STEP 12 COMPLETE</span><span class="os-chip good">STEP 13 INVENTORY LIVE</span></div></section>
<?php if($error):?><div class="pp-alert bad"><strong>Dashboard diagnostic:</strong> <?= d13_h($error) ?></div><?php endif;?>
<section class="s10-kpis"><div class="s10-kpi"><small>Sellable Stock</small><strong><?= d13_h(d13_n($m['stock'])) ?></strong><span><?= number_format($m['batches']) ?> live batches</span></div><div class="s10-kpi"><small>Known Stock Value</small><strong><?= d13_m($m['stock_value']) ?></strong><span>Explicit batch cost only</span></div><div class="s10-kpi"><small>Low / Out</small><strong><?= number_format($m['low']) ?> / <?= number_format($m['out']) ?></strong><span><?= number_format($m['expiring']) ?> expiring soon</span></div><div class="s10-kpi"><small>Sale Sync</small><strong><?= number_format($m['pending_sync']) ?></strong><span>Post-activation pending</span></div></section>
<section class="s10-grid"><article class="s10-card s10-span-8"><div class="os-title-row"><div><h2>STEP 13 • Inventory Workflow</h2><p>From real inward stock to sale deduction and physical verification.</p></div><a class="os-btn primary" href="inventory_center.php">Open Inventory</a></div><div class="os-report-grid"><a class="os-report" href="inventory_inward.php"><div class="os-report-head"><b>1. Receive Stock</b><em>IN</em></div><span>Opening or purchase stock with batch, expiry and source.</span><small>Inward →</small></a><a class="os-report" href="inventory_center.php"><div class="os-report-head"><b>2. Monitor</b><em>LIVE</em></div><span>Sellable, expired, low stock and valuation.</span><small>Stock →</small></a><a class="os-report" href="product_sales_center.php"><div class="os-report-head"><b>3. Sell</b><em>FEFO</em></div><span>Automatic valid-batch deduction from Product Sales.</span><small>Sales →</small></a><a class="os-report" href="inventory_adjustments.php"><div class="os-report-head"><b>4. Adjust</b><em>TRACE</em></div><span>Damage, loss, returns and corrections.</span><small>Adjust →</small></a><a class="os-report" href="inventory_stocktake.php"><div class="os-report-head"><b>5. Count</b><em>REAL</em></div><span>Physical count with variance ledger posting.</span><small>Stocktake →</small></a><a class="os-report" href="step13_audit.php"><div class="os-report-head"><b>6. Audit</b><em>SAFE</em></div><span>Balance, expiry, allocation and sync integrity.</span><small>Audit →</small></a></div></article><aside class="s10-card s10-span-4"><h2>Inventory Health</h2><div class="s10-list"><div class="s10-row"><div><b>Low Stock</b><small>Configured threshold reached</small></div><strong><?= number_format($m['low']) ?></strong></div><div class="s10-row"><div><b>Out of Stock</b><small>Tracked and zero sellable</small></div><strong><?= number_format($m['out']) ?></strong></div><div class="s10-row"><div><b>Expiring Soon</b><small>Within product alert window</small></div><strong><?= number_format($m['expiring']) ?></strong></div><div class="s10-row"><div><b>Pending Sale Sync</b><small>Needs allocation recovery</small></div><strong><?= number_format($m['pending_sync']) ?></strong></div></div></aside>
<article class="s10-card s10-span-7"><h2>Connected Workspaces</h2><div class="os-links"><a class="os-link" href="product_sales_center.php"><div><b>Product Sales</b><span><?= number_format($m['sales']) ?> active • <?= number_format($m['cancelled']) ?> cancelled</span></div><span>→</span></a><a class="os-link" href="product_payments.php"><div><b>Collections</b><span><?= d13_m($m['outstanding']) ?> outstanding</span></div><span>→</span></a><a class="os-link" href="product_cost_center.php"><div><b>Verified Profit</b><span><?= d13_m($m['verified_profit']) ?> explicit-cost profit</span></div><span>→</span></a><a class="os-link" href="inventory_export.php"><div><b>Inventory Export</b><span>UTF-8 CSV + Print / Save PDF</span></div><span>→</span></a></div></article><aside class="s10-card s10-span-5"><h2>Recent Audit Activity</h2><div class="s10-list"><?php foreach($recent as $a):?><div class="s10-row"><div><b><?= d13_h(ucwords(str_replace('_',' ',(string)$a['event_type']))) ?></b><small><?= d13_h((string)($a['entity_type']??'system')) ?><?= $a['entity_id']?' #'.(int)$a['entity_id']:'' ?></small></div><strong><?= d13_h(substr((string)$a['created_at'],5,11)) ?></strong></div><?php endforeach;?><?php if(!$recent):?><div class="s10-row"><div><b>No recent audit events</b></div></div><?php endif;?></div></aside></section>
<div class="os-footer-note"><strong>Source-of-truth:</strong> STEP 13 never invents stock from prices or historic sales. Real opening/purchase stock creates the inventory position; every later movement remains ledger-backed.</div></main></div><script src="assets/business-collapsible.js?v=20260820-1" defer></script></body></html>
