<?php
declare(strict_types=1);
/* STEP 25 is the final QA/UAT and production-launch layer over the completed STEP 24 dashboard. */
ob_start();
require __DIR__ . '/dashboard_step24.php';
$html=(string)ob_get_clean();
$replacements=[
    'Business OS • THROUGH STEP 24'=>'Business OS • THROUGH STEP 25',
    'BUSINESS OS • STEP 10 → 24'=>'BUSINESS OS • STEP 10 → 25',
    'The public product portal is now PWA-ready, mobile-optimized and discovery-ready.'=>'The Business OS is now at the final QA, UAT and production-launch gate.',
    'Visitors get a faster responsive storefront, installable-app plumbing, safe offline fallback, stronger keyboard/screen-reader support and SEO metadata. Checkout, tracking, pricing and Business OS controls remain server-governed.'=>'Automated regression checks, human UAT evidence, verified recovery and production health now converge into one controlled go-live path. No local test can silently mark the system deployed.',
    'PWA + MOBILE FOUNDATION LIVE'=>'FINAL QA + LAUNCH CONTROL LIVE',
    '<a href="step24_audit.php"><i class="dot"></i>STEP 24 Audit</a>'=>'<a href="final_launch_center.php"><i class="dot"></i>Final Launch Center</a><a href="step25_audit.php"><i class="dot"></i>STEP 25 Audit</a><a href="step24_audit.php"><i class="dot"></i>STEP 24 Audit</a>',
    '<strong>STEP 24 boundary:</strong> PWA, mobile, accessibility, performance and SEO improvements do not weaken STEP 23. Checkout remains an order request; sensitive checkout/tracking pages stay network-only and final business actions remain server-controlled.'=>'<strong>STEP 25 boundary:</strong> automated QA and UAT evidence do not equal a production deployment. A release is live only when the target production environment passes its gates and the authorized Deployment Releases workflow records it as deployed.'
];
$html=str_replace(array_keys($replacements),array_values($replacements),$html);

$quickAccess=<<<'HTML'
<section class="s10-grid"><article class="s10-card s10-span-12"><div class="os-title-row"><div><h2>Quick Access & Security</h2><p>Direct navigation to customer membership, customer-site publishing, product master, product assets, account and security workspaces.</p></div><a class="os-btn wr-feature-btn" href="../feature_hub.php">Open All Features</a></div><div class="wr-quick-grid"><a class="wr-quick-card" href="../feature_hub.php"><small>ROLE-AWARE</small><b>All Features</b><span>One launcher for every module allowed by your signed-in role.</span></a><a class="wr-quick-card" href="customer_membership_manager.php"><small>CLUB CUSTOMERS</small><b>Members & Offers</b><span>Assign Club Member IDs and discount labels, manage Coach ownership, and create product/bulk customer offers.</span></a><a class="wr-quick-card" href="customer_site_manager.php"><small>CUSTOMER SITE</small><b>Site Content Manager</b><span>Update public page text, contact details, services and rotating member stories without editing HTML.</span></a><a class="wr-quick-card" href="product_master_manager.php"><small>NEW PRODUCT</small><b>Product Launch Manager</b><span>Add a future product with SKU, category, description, image, VP, MRP, exact tier prices, source and effective date.</span></a><a class="wr-quick-card" href="product_image_manager.php"><small>PRODUCT ASSETS</small><b>Product Images</b><span>Bulk upload authorized current product packshots and auto-match them by Stock/SKU.</span></a><a class="wr-quick-card" href="../account.php"><small>ACCOUNT</small><b>My Account</b><span>Profile, active sessions, login history and device controls.</span></a><a class="wr-quick-card" href="../trusted_devices.php"><small>DEVICE SECURITY</small><b>Trusted Devices</b><span>Manage secure browser recognition and revoke device trust.</span></a><a class="wr-quick-card" href="../mfa_settings.php"><small>TWO-STEP</small><b>Authenticator Security</b><span>Authenticator app verification and one-time recovery codes.</span></a><a class="wr-quick-card" href="../security_alerts.php"><small>ALERTS</small><b>Security Alerts</b><span>Review unusual sign-in and account-security activity.</span></a><a class="wr-quick-card" href="../change_password.php"><small>PASSWORD</small><b>Change Password</b><span>Update your password under the current security policy.</span></a></div></article></section>
HTML;

$html=str_replace('</head>','<link rel="stylesheet" href="assets/workspace_refresh.css"></head>',$html);
$html=str_replace('<div class="os-top-actions">','<div class="os-top-actions"><a class="os-btn wr-feature-btn" href="../feature_hub.php">All Features</a>',$html);
$html=str_replace('<a class="active" href="index.php"><i class="dot"></i>Dashboard</a>','<a class="active" href="index.php"><i class="dot"></i>Dashboard</a><a href="../feature_hub.php"><i class="dot"></i>All Features</a>',$html);
$html=str_replace('</aside>','<div class="os-nav-label" style="margin-top:8px">Customer Management</div><nav class="os-nav"><a href="customer_membership_manager.php"><i class="dot"></i>Club Members & Offers</a></nav><div class="os-nav-label" style="margin-top:8px">Customer Site</div><nav class="os-nav"><a href="customer_site_manager.php"><i class="dot"></i>Site Content Manager</a><a href="product_master_manager.php"><i class="dot"></i>New / Update Product</a><a href="product_image_manager.php"><i class="dot"></i>Product Images</a></nav><div class="os-nav-label" style="margin-top:8px">My Access & Security</div><nav class="os-nav"><a href="../account.php"><i class="dot"></i>My Account</a><a href="../security_alerts.php"><i class="dot"></i>Security Alerts</a><a href="../trusted_devices.php"><i class="dot"></i>Trusted Devices</a><a href="../mfa_settings.php"><i class="dot"></i>Two-Step Verification</a></nav></aside>',$html);
$html=str_replace('<div class="os-footer-note">',$quickAccess.'<div class="os-footer-note">',$html);
echo $html;
