<?php
declare(strict_types=1);

require_once __DIR__ . '/config/database.php';

function gs_h(mixed $v):string{return htmlspecialchars((string)$v,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8');}
function gs_trim(mixed $v):string{return trim((string)$v);}
function gs_key(mixed $v):string{$t=preg_replace('/\s+/u',' ',gs_trim($v));$t=$t===null?'':$t;return function_exists('mb_strtolower')?mb_strtolower($t,'UTF-8'):strtolower($t);}
function gs_money(mixed $v):string{return '₹'.number_format((float)$v,2,'.',',');}
function gs_num(mixed $v):string{$t=number_format((float)$v,3,'.',',');return rtrim(rtrim($t,'0'),'.');}
function gs_date(?string $v):string{if(!$v)return '—';try{return(new DateTimeImmutable($v))->format('d M Y');}catch(Throwable){return(string)$v;}}
function gs_period_link(string $page,?string $date,array $extra=[]):string{if($date){try{$d=new DateTimeImmutable($date);$extra['year']=$d->format('Y');$extra['month']=$d->format('n');}catch(Throwable){}}return $page.($extra?'?'.http_build_query($extra):'');}

$query=gs_trim($_GET['q']??'');$scope=gs_key($_GET['scope']??'all');$allowed=['all','member','order','vp','renewal','income','royalty','tool','report'];if(!in_array($scope,$allowed,true))$scope='all';
$error=null;$organizationId=0;$sourceTotal=0;$sourceMapped=0;$sourcePending=0;$results=[];$counts=['member'=>0,'order'=>0,'vp'=>0,'renewal'=>0,'income'=>0,'royalty'=>0,'tool'=>0,'report'=>0];$rev=BUSINESS_REVERSED_SOURCE_SHEET;

$tools=[
 ['Today Center','today daily command followup quick actions activity','Today facts, due follow-ups, recent activity and quick commands.','today_center.php','DAILY'],
 ['Global Search','search command member order vp renewal report','Universal read-only Business OS search.','global_search.php','SEARCH'],
 ['Alerts & Follow-ups','alerts reminder followup overdue due identity system','Fact-safe alerts and persistent audited follow-ups.','alerts_center.php','ACTION'],
 ['Insights & Trends','insights analytics trends month vp order profit income royalty','Month-to-month normalized business analytics.','insights_center.php','LIVE'],
 ['Saved Views','saved views favorites shortcut filter workspace','Save recurring internal workspace/filter shortcuts.','saved_views.php','FAVORITE'],
 ['Data Management','data management create correct reverse restore audit workflow','Create → Correct → Reverse → Restore → Audit workflow hub.','data_management.php','CONTROL'],
 ['Smart Data Entry','add create new ums vp order renewal income royalty entry','Create new MANUAL business facts with raw trace and duplicate guard.','data_entry_center.php','WRITE'],
 ['Add New UMS','new ums member create add sponsor','Create a new member + UMS lifecycle record.','data_entry_center.php?tab=new_ums','WRITE'],
 ['Add Volume Points','vp volume points add create','Add a verified member-linked Volume Point fact.','data_entry_center.php?tab=vp','WRITE'],
 ['Add Order','order add create sale profit discount','Add an order with value, profit and VP.','data_entry_center.php?tab=order','WRITE'],
 ['Add Renewal','renewal ums renew add create','Record a verified member UMS renewal.','data_entry_center.php?tab=renewal','WRITE'],
 ['Add Income','income retail check club add create','Add Retail, Check, Club or Other income.','data_entry_center.php?tab=income','WRITE'],
 ['Add Royalty','royalty add create','Add a royalty amount and optional VP.','data_entry_center.php?tab=royalty','WRITE'],
 ['Correction Center','edit correct correction wrong manual entry','Correct MANUAL facts with before/after audit evidence.','correction_center.php','SAFE EDIT'],
 ['Reverse / Cancel Center','reverse cancel delete remove wrong manual no hard delete','Remove MANUAL business effect without deleting evidence.','reversal_center.php','NO DELETE'],
 ['Restore Center','restore recover reversed cancelled entry','Recover a reversed fact after conflict checks.','restore_center.php','RECOVER'],
 ['Unified Audit Center','audit history timeline created corrected reversed restored activity','Read the complete manual lifecycle audit timeline.','audit_center.php','READ ONLY'],
 ['Operations Center','operations orders vp income royalty analytics','Orders, VP, Income and Royalty workspace.','operations_center.php','LIVE'],
 ['Members & Network','member members network ums sponsor search','Search normalized members and inspect UMS/network context.','members.php','LIVE'],
 ['Member Profile 360°','member profile 360 timeline business history','Open a verified member complete business timeline.','member_profile.php','LIVE'],
 ['Sponsor Network','sponsor network tree downline upline','Verified sponsor links and interactive network tree.','sponsor_network.php','LIVE'],
 ['Report Center','reports reporting master tracking sp house name wise ums','Open all six live derived reports.','report_center.php','6 REPORTS'],
 ['Export Center','export csv print pdf share excel','Filtered UTF-8 CSV and print/save-PDF workspace.','export_center.php','EXPORT'],
 ['Data Quality','data quality duplicate identity shared mobile sponsor source trace','Read-only identity and source-quality diagnostics.','data_quality.php','QUALITY'],
 ['System Health','health database php extension backup readiness diagnostics','Environment, schema and backup-readiness diagnostics.','health_center.php','HEALTH'],
 ['Step 10 Completion Audit','step 10 audit complete completion a z pass','Verify all STEP 10 A–Z modules and database prerequisites.','step10_audit.php','26/26'],
 ['Excel Data Center','excel import historical legacy reconcile 757','Historical source reconciliation and normalized seeding tools.','final_excel_seeding.php','LEGACY'],
 ['Formula Audit','formula audit mapping workbook derived rules','Review workbook formula mapping and derived-report logic.','derived_reports_audit.php','AUDIT'],
];
$reports=[
 ['Master Tracking','master tracking weekly monthly vp income royalty','Weekly/monthly VP and business tracking.','master_tracking.php'],
 ['SP House','sp house personal family first line associate team vp','SP/first-line and team VP live view.','sp_house.php'],
 ['Name Wise Tracking','name wise tracking pc associate ums vp','Name-wise PC, Associate and UMS VP tracking.','name_wise_tracking.php'],
 ['Master Business Tracking','master business ppv dvp active ums royalty new ums','PPV, DVP, royalty and active UMS business summary.','master_business_tracking.php'],
 ['UMS Renewal','ums renewal renewed pending identity review','Renewed, pending and identity-review workspace.','ums_renewal.php'],
 ['UMS Active Duration','ums active duration lifecycle team supervisor','Live UMS duration and lifecycle view.','ums_active_duration.php'],
];

try{
 $pdo=business_db();foreach(['organizations','raw_source_records','members','orders','volume_point_entries','renewals','income_entries','royalty_entries'] as $t)if(!business_table_exists($pdo,$t))throw new RuntimeException("Required table {$t} is missing.");
 $organizationId=(int)$pdo->query("SELECT id FROM organizations WHERE organization_code='HWC-001' LIMIT 1")->fetchColumn();if($organizationId<=0)throw new RuntimeException('Healthcare Wellness Club organization was not found.');
 $state=$pdo->prepare("SELECT COUNT(*) total_rows,SUM(mapping_status='mapped') mapped_rows,SUM(mapping_status='pending') pending_rows FROM raw_source_records WHERE organization_id=? AND source_dataset IN ('New UMS','Volume Points','First & Second Set','Active UMS Month_Wise','Renewal UMS','Monthely_Income','Royalty_Tracking','Extra Order for Customer')");$state->execute([$organizationId]);$s=$state->fetch()?:[];$sourceTotal=(int)($s['total_rows']??0);$sourceMapped=(int)($s['mapped_rows']??0);$sourcePending=(int)($s['pending_rows']??0);
 if($query!==''){$like='%'.$query.'%';
  if($scope==='all'||$scope==='member'){$stmt=$pdo->prepare("SELECT m.id,m.full_name,m.mobile,m.status,sm.full_name sponsor_name FROM members m LEFT JOIN members sm ON sm.id=m.sponsor_member_id AND sm.organization_id=m.organization_id WHERE m.organization_id=? AND COALESCE(m.source_sheet,'')<>? AND (m.full_name LIKE ? OR COALESCE(m.mobile,'') LIKE ? OR COALESCE(m.member_code,'') LIKE ? OR COALESCE(m.external_member_code,'') LIKE ? OR CAST(m.id AS CHAR) LIKE ?) ORDER BY m.full_name,m.id LIMIT 18");$stmt->execute([$organizationId,$rev,$like,$like,$like,$like,$like]);foreach($stmt->fetchAll() as $r){$meta=array_filter([$r['mobile']?:null,$r['status']?:null,$r['sponsor_name']?'Sponsor: '.$r['sponsor_name']:null]);$results[]=['type'=>'member','title'=>$r['full_name'],'subtitle'=>implode(' • ',$meta),'value'=>'Member #'.(int)$r['id'],'url'=>'member_profile.php?member='.(int)$r['id'],'badge'=>'MEMBER'];$counts['member']++;}}
  if($scope==='all'||$scope==='order'){$stmt=$pdo->prepare("SELECT o.id,o.member_id,o.order_date,o.order_type,o.description,o.net_amount,o.volume_points,m.full_name FROM orders o LEFT JOIN members m ON m.id=o.member_id AND m.organization_id=o.organization_id WHERE o.organization_id=? AND COALESCE(o.source_sheet,'')<>? AND (CAST(o.id AS CHAR) LIKE ? OR COALESCE(m.full_name,'') LIKE ? OR COALESCE(o.order_type,'') LIKE ? OR COALESCE(o.description,'') LIKE ? OR CAST(o.net_amount AS CHAR) LIKE ?) ORDER BY o.order_date DESC,o.id DESC LIMIT 14");$stmt->execute([$organizationId,$rev,$like,$like,$like,$like,$like]);foreach($stmt->fetchAll() as $r){$extra=$r['member_id']?['member'=>(int)$r['member_id']]:[];$results[]=['type'=>'order','title'=>'Order #'.(int)$r['id'].' • '.($r['full_name']?:'Source-only customer'),'subtitle'=>gs_date((string)$r['order_date']).' • '.($r['description']?:$r['order_type']?:'Order'),'value'=>gs_money($r['net_amount']).' • '.gs_num($r['volume_points']).' VP','url'=>gs_period_link('operations_center.php',(string)$r['order_date'],$extra),'badge'=>'ORDER'];$counts['order']++;}}
  if($scope==='all'||$scope==='vp'){$stmt=$pdo->prepare("SELECT v.id,v.member_id,v.member_name_snapshot,v.entry_date,v.volume_points,v.order_type,v.vp_from,v.ordered_by,v.vp_type,v.level_label,v.week_label,m.full_name FROM volume_point_entries v LEFT JOIN members m ON m.id=v.member_id AND m.organization_id=v.organization_id WHERE v.organization_id=? AND COALESCE(v.source_sheet,'')<>? AND (CAST(v.id AS CHAR) LIKE ? OR COALESCE(m.full_name,v.member_name_snapshot,'') LIKE ? OR COALESCE(v.order_type,'') LIKE ? OR COALESCE(v.vp_from,'') LIKE ? OR COALESCE(v.ordered_by,'') LIKE ? OR COALESCE(v.vp_type,'') LIKE ? OR COALESCE(v.level_label,'') LIKE ? OR COALESCE(v.week_label,'') LIKE ? OR CAST(v.volume_points AS CHAR) LIKE ?) ORDER BY v.entry_date DESC,v.id DESC LIMIT 14");$stmt->execute([$organizationId,$rev,$like,$like,$like,$like,$like,$like,$like,$like,$like]);foreach($stmt->fetchAll() as $r){$name=$r['full_name']?:$r['member_name_snapshot']?:'Source-only member';$extra=$r['member_id']?['member'=>(int)$r['member_id']]:[];$detail=array_filter([$r['order_type']?:null,$r['vp_from']?'From: '.$r['vp_from']:null,$r['vp_type']?:null,$r['week_label']?:null]);$results[]=['type'=>'vp','title'=>gs_num($r['volume_points']).' VP • '.$name,'subtitle'=>gs_date($r['entry_date']?(string)$r['entry_date']:null).($detail?' • '.implode(' • ',$detail):''),'value'=>'VP #'.(int)$r['id'],'url'=>gs_period_link('operations_center.php',$r['entry_date']?(string)$r['entry_date']:null,$extra),'badge'=>'VP'];$counts['vp']++;}}
  if($scope==='all'||$scope==='renewal'){$has=business_column_exists($pdo,'renewals','member_name_snapshot');$nameExpr=$has?"COALESCE(m.full_name,n.member_name_snapshot,'Source-only member')":"COALESCE(m.full_name,'Source-only member')";$stmt=$pdo->prepare("SELECT n.id,n.member_id,n.renewal_date,n.amount,n.volume_points,{$nameExpr} display_name FROM renewals n LEFT JOIN members m ON m.id=n.member_id AND m.organization_id=n.organization_id WHERE n.organization_id=? AND COALESCE(n.source_sheet,'')<>? AND (CAST(n.id AS CHAR) LIKE ? OR {$nameExpr} LIKE ? OR CAST(n.amount AS CHAR) LIKE ? OR CAST(n.volume_points AS CHAR) LIKE ? OR CAST(n.renewal_date AS CHAR) LIKE ?) ORDER BY n.renewal_date DESC,n.id DESC LIMIT 14");$stmt->execute([$organizationId,$rev,$like,$like,$like,$like,$like]);foreach($stmt->fetchAll() as $r){$url=$r['member_id']?'member_profile.php?member='.(int)$r['member_id'].'&event=renewal':'ums_renewal.php';$results[]=['type'=>'renewal','title'=>'Renewal #'.(int)$r['id'].' • '.$r['display_name'],'subtitle'=>gs_date((string)$r['renewal_date']),'value'=>gs_money($r['amount']).' • '.gs_num($r['volume_points']).' VP','url'=>$url,'badge'=>'RENEWAL'];$counts['renewal']++;}}
  if($scope==='all'||$scope==='income'){$stmt=$pdo->prepare("SELECT id,income_date,income_type,amount,period_key FROM income_entries WHERE organization_id=? AND COALESCE(source_sheet,'')<>? AND (CAST(id AS CHAR) LIKE ? OR income_type LIKE ? OR CAST(amount AS CHAR) LIKE ? OR CAST(income_date AS CHAR) LIKE ? OR COALESCE(period_key,'') LIKE ?) ORDER BY income_date DESC,id DESC LIMIT 12");$stmt->execute([$organizationId,$rev,$like,$like,$like,$like,$like]);foreach($stmt->fetchAll() as $r){$results[]=['type'=>'income','title'=>ucfirst((string)$r['income_type']).' Income #'.(int)$r['id'],'subtitle'=>gs_date((string)$r['income_date']).($r['period_key']?' • '.$r['period_key']:''),'value'=>gs_money($r['amount']),'url'=>gs_period_link('operations_center.php',(string)$r['income_date'],['q'=>(string)$r['income_type']]),'badge'=>'INCOME'];$counts['income']++;}}
  if($scope==='all'||$scope==='royalty'){$stmt=$pdo->prepare("SELECT id,royalty_date,period_label,amount,volume_points FROM royalty_entries WHERE organization_id=? AND COALESCE(source_sheet,'')<>? AND (CAST(id AS CHAR) LIKE ? OR COALESCE(period_label,'') LIKE ? OR CAST(amount AS CHAR) LIKE ? OR CAST(volume_points AS CHAR) LIKE ? OR CAST(royalty_date AS CHAR) LIKE ?) ORDER BY royalty_date DESC,id DESC LIMIT 12");$stmt->execute([$organizationId,$rev,$like,$like,$like,$like,$like]);foreach($stmt->fetchAll() as $r){$results[]=['type'=>'royalty','title'=>'Royalty #'.(int)$r['id'].($r['period_label']?' • '.$r['period_label']:''),'subtitle'=>gs_date($r['royalty_date']?(string)$r['royalty_date']:null),'value'=>gs_money($r['amount']).' • '.gs_num($r['volume_points']).' VP','url'=>gs_period_link('operations_center.php',$r['royalty_date']?(string)$r['royalty_date']:null,['q'=>(string)($r['period_label']?:'royalty')]),'badge'=>'ROYALTY'];$counts['royalty']++;}}
 }
}catch(Throwable $e){$error=$e->getMessage();}

$key=gs_key($query);if($scope==='all'||$scope==='tool')foreach($tools as[$title,$keywords,$desc,$url,$badge]){if($query!==''&&!str_contains(gs_key($title.' '.$keywords.' '.$desc),$key))continue;$results[]=['type'=>'tool','title'=>$title,'subtitle'=>$desc,'value'=>'Open tool','url'=>$url,'badge'=>$badge];$counts['tool']++;}if($scope==='all'||$scope==='report')foreach($reports as[$title,$keywords,$desc,$url]){if($query!==''&&!str_contains(gs_key($title.' '.$keywords.' '.$desc),$key))continue;$results[]=['type'=>'report','title'=>$title,'subtitle'=>$desc,'value'=>'Open live report','url'=>$url,'badge'=>'REPORT'];$counts['report']++;}
$typeOrder=['tool'=>0,'report'=>1,'member'=>2,'order'=>3,'vp'=>4,'renewal'=>5,'income'=>6,'royalty'=>7];if($query!=='')usort($results,static fn($a,$b)=>(($typeOrder[$a['type']]??99)<=>($typeOrder[$b['type']]??99)));$totalResults=count($results);$sourceReady=$sourceTotal===757&&$sourceMapped===757&&$sourcePending===0;
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>Global Search & Command Center - Healthcare Wellness Club</title><link rel="stylesheet" href="assets/dashboard.css"><link rel="stylesheet" href="assets/global_search.css"></head><body>
<header class="os-topbar"><div class="os-topbar-inner"><a class="os-brand" href="index.php"><img src="../img/logo.png" alt="Healthcare Wellness Club logo"><span><strong>Healthcare Wellness Club</strong><small>Business OS • Global Search & Command Center</small></span></a><div class="os-top-actions"><a class="os-btn" href="today_center.php">Today</a><a class="os-btn" href="alerts_center.php">Alerts</a><a class="os-btn primary" href="index.php">Dashboard</a></div></div></header>
<div class="os-layout"><aside class="os-sidebar"><div class="os-nav-label">Business OS</div><nav class="os-nav"><a href="index.php"><i class="dot"></i>Dashboard</a><a href="today_center.php"><i class="dot"></i>Today Center</a><a class="active" href="global_search.php"><i class="dot"></i>Global Search</a><a href="alerts_center.php"><i class="dot"></i>Alerts</a><a href="insights_center.php"><i class="dot"></i>Insights</a><a href="saved_views.php"><i class="dot"></i>Saved Views</a><a href="data_management.php"><i class="dot"></i>Data Management</a><a href="operations_center.php"><i class="dot"></i>Operations</a><a href="report_center.php"><i class="dot"></i>Reports</a><a href="export_center.php"><i class="dot"></i>Export</a><a href="data_quality.php"><i class="dot"></i>Data Quality</a><a href="health_center.php"><i class="dot"></i>Health</a></nav><div class="os-sidebar-status"><b><?= $error===null?'Search engine ready':'Review required' ?></b><span><?= number_format($sourceMapped) ?> / 757 legacy mapped • reversed MANUAL facts hidden.</span></div></aside><main class="os-main">
<section class="os-hero gs-hero"><div class="os-kicker">Step 10N/X • Universal Business Search</div><h1>Find a person, transaction, report or any completed STEP 10 command from one search box.</h1><p>Search member name/mobile/ID, orders, VP, renewals, income, royalty, reports, or commands such as “today”, “alerts”, “export”, “data quality”, “add order” and “step 10 audit”.</p><div class="os-status-row"><span class="os-chip <?= $error===null?'good':'' ?>"><?= $error===null?'GLOBAL SEARCH LIVE':'Review required' ?></span><span class="os-chip <?= $sourceReady?'good':'' ?>"><?= number_format($sourceMapped) ?> / 757 legacy mapped</span><span class="os-chip good">READ ONLY SEARCH</span><span class="os-chip">STEP 10 COMMANDS COMPLETE</span></div></section>
<?php if($error):?><div class="gs-alert bad"><strong>Search diagnostic:</strong> <?= gs_h($error) ?></div><?php endif;?>
<section class="os-card gs-search-card"><form method="get" class="gs-search-form" id="globalSearchForm"><div class="gs-search-box"><span>⌕</span><input id="globalSearchInput" name="q" value="<?= gs_h($query) ?>" placeholder="Search member, mobile, order, VP, report or command…" autocomplete="off" autofocus><kbd>/</kbd></div><select name="scope"><option value="all" <?= $scope==='all'?'selected':'' ?>>Everything</option><option value="member" <?= $scope==='member'?'selected':'' ?>>Members</option><option value="order" <?= $scope==='order'?'selected':'' ?>>Orders</option><option value="vp" <?= $scope==='vp'?'selected':'' ?>>Volume Points</option><option value="renewal" <?= $scope==='renewal'?'selected':'' ?>>Renewals</option><option value="income" <?= $scope==='income'?'selected':'' ?>>Income</option><option value="royalty" <?= $scope==='royalty'?'selected':'' ?>>Royalty</option><option value="tool" <?= $scope==='tool'?'selected':'' ?>>Tools / Commands</option><option value="report" <?= $scope==='report'?'selected':'' ?>>Reports</option></select><button type="submit">Search →</button></form><div class="gs-hints"><span>Try:</span><a href="?q=today">today</a><a href="?q=alerts">alerts</a><a href="?q=add+order">add order</a><a href="?q=data+quality">data quality</a><a href="?q=export">export</a><a href="?q=step+10+audit">step 10 audit</a></div></section>
<?php if($error===null):?><section class="gs-summary"><?php foreach($counts as $k=>$c):if($c<=0)continue;?><a href="?q=<?= rawurlencode($query) ?>&scope=<?= gs_h($k) ?>"><b><?= number_format($c) ?></b><span><?= gs_h(ucwords($k)) ?></span></a><?php endforeach;?></section><section class="gs-layout"><article class="os-card gs-results"><div class="os-title-row"><div><h2><?= $query===''?'Command Center':'Search Results' ?></h2><p><?= $query===''?'Choose a Business OS command or live report.':number_format($totalResults).' result(s) for “'.gs_h($query).'”.' ?></p></div><?php if($query!==''):?><a class="os-btn" href="global_search.php">Clear</a><?php endif;?></div><?php if(!$results):?><div class="gs-empty"><b>No matching result found.</b><span>Try a shorter fragment or different scope. Search never guesses identity.</span></div><?php else:?><div class="gs-list"><?php foreach($results as $item):?><a class="gs-item <?= gs_h($item['type']) ?>" href="<?= gs_h($item['url']) ?>"><span class="gs-icon"><?= gs_h(strtoupper(substr($item['badge'],0,2))) ?></span><div class="gs-body"><div><b><?= gs_h($item['title']) ?></b><em><?= gs_h($item['badge']) ?></em></div><p><?= gs_h($item['subtitle']) ?></p></div><strong><?= gs_h($item['value']) ?></strong><i>→</i></a><?php endforeach;?></div><?php endif;?></article><aside class="os-card gs-side"><h2>Search Safety</h2><p>Global Search is a navigation/read layer.</p><div class="gs-policy"><b>Identity-safe</b><span>Exact normalized Member IDs are opened; duplicate names remain separate.</span></div><div class="gs-policy"><b>Reversal-aware</b><span><?= gs_h($rev) ?> facts remain audit-visible but are excluded here.</span></div><div class="gs-policy"><b>Source health</b><span><?= number_format($sourceMapped) ?>/<?= number_format($sourceTotal) ?> legacy mapped • <?= number_format($sourcePending) ?> pending.</span></div><div class="gs-shortcuts"><b>Keyboard</b><span><kbd>/</kbd> focus search</span><span><kbd>Esc</kbd> clear text</span></div></aside></section><?php endif;?>
<div class="os-footer-note"><strong>Command rule:</strong> search opens existing tools and exact normalized facts only. It never performs hidden writes or automatic identity merges.</div></main></div><script src="assets/global_search.js"></script></body></html>
