<?php
declare(strict_types=1);

require_once __DIR__ . '/config/step10_services.php';

$error=null;$ctx=['organization_id'=>0];$legacy=['total'=>0,'mapped'=>0,'pending'=>0];$checks=[];$dbSize=0.0;$tableCount=0;$schemaVersion='unknown';$manualRaw=0;$reports=0;
function hc_add(array &$checks,string $name,bool $ok,string $detail,string $warnDetail=''):void{$checks[]=['name'=>$name,'ok'=>$ok,'detail'=>$ok?$detail:($warnDetail!==''?$warnDetail:$detail)];}
try{
 $pdo=business_db();$ctx=step10_org_context($pdo);step10_ensure_tables($pdo);$orgId=(int)$ctx['organization_id'];$legacy=step10_legacy_state($pdo,$orgId);
 $tableCount=(int)$pdo->query("SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE()")->fetchColumn();
 $dbSize=(float)$pdo->query("SELECT COALESCE(SUM(data_length+index_length),0) FROM information_schema.tables WHERE table_schema=DATABASE()")->fetchColumn();
 if(business_table_exists($pdo,'schema_meta')){$stmt=$pdo->prepare("SELECT meta_value FROM schema_meta WHERE meta_key='schema_version' LIMIT 1");$stmt->execute();$schemaVersion=(string)($stmt->fetchColumn()?:'unknown');}
 $stmt=$pdo->prepare("SELECT COUNT(*) FROM report_definitions WHERE organization_id=? AND is_active=1");$stmt->execute([$orgId]);$reports=(int)$stmt->fetchColumn();
 $stmt=$pdo->prepare("SELECT id FROM data_sources WHERE organization_id=? AND source_code='MANUAL' LIMIT 1");$stmt->execute([$orgId]);$mid=(int)$stmt->fetchColumn();if($mid>0){$stmt=$pdo->prepare("SELECT COUNT(*) FROM raw_source_records WHERE organization_id=? AND data_source_id=?");$stmt->execute([$orgId,$mid]);$manualRaw=(int)$stmt->fetchColumn();}
 hc_add($checks,'Database connection',true,'Connected to '.(string)$pdo->query('SELECT DATABASE()')->fetchColumn());
 hc_add($checks,'Legacy source baseline',$legacy['total']===757&&$legacy['mapped']===757&&$legacy['pending']===0,$legacy['mapped'].' / 757 mapped',$legacy['mapped'].' / '.$legacy['total'].' mapped • '.$legacy['pending'].' pending');
 hc_add($checks,'Derived report registry',$reports===6,$reports.' / 6 active reports',$reports.' / 6 active reports');
 hc_add($checks,'PDO MySQL extension',extension_loaded('pdo_mysql'),'pdo_mysql loaded','pdo_mysql is missing');
 hc_add($checks,'ZIP extension',extension_loaded('zip'),'zip loaded for XLSX handling','zip extension missing; workbook import may fail');
 hc_add($checks,'mbstring extension',extension_loaded('mbstring'),'mbstring loaded','mbstring missing; Unicode fallbacks remain active');
 hc_add($checks,'Follow-up table',business_table_exists($pdo,'business_followups'),'business_followups ready','business_followups missing');
 hc_add($checks,'Saved Views table',business_table_exists($pdo,'business_saved_views'),'business_saved_views ready','business_saved_views missing');
 $required=['index.php','global_search.php','data_management.php','today_center.php','alerts_center.php','insights_center.php','export_center.php','data_quality.php','saved_views.php','audit_center.php','health_center.php','report_center.php'];$missing=[];foreach($required as $f)if(!is_file(__DIR__.'/'.$f))$missing[]=$f;hc_add($checks,'Business OS workspaces',!$missing,count($required).' core workspace files present',$missing?'Missing: '.implode(', ',$missing):'');
 $dumpCandidates=['C:\\xampp\\mysql\\bin\\mysqldump.exe','/usr/bin/mysqldump','/usr/local/bin/mysqldump'];$dumpFound='';foreach($dumpCandidates as $p)if(is_file($p)){$dumpFound=$p;break;}hc_add($checks,'Database dump tool',$dumpFound!=='',$dumpFound!==''?'Detected: '.$dumpFound:'Not detected','mysqldump not detected in common paths; hosting backup can still be used.');
}catch(Throwable $e){$error=$e->getMessage();}
$failed=count(array_filter($checks,static fn($c)=>!$c['ok']));$passed=count($checks)-$failed;$healthy=$error===null&&$failed===0;
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>System Health - Healthcare Wellness Club</title><link rel="stylesheet" href="assets/dashboard.css"><link rel="stylesheet" href="assets/step10.css"></head><body>
<header class="os-topbar"><div class="os-topbar-inner"><a class="os-brand" href="index.php"><img src="../img/logo.png" alt="Healthcare Wellness Club logo"><span><strong>Healthcare Wellness Club</strong><small>Business OS • System Health & Backup Readiness</small></span></a><div class="os-top-actions"><a class="os-btn" href="export_center.php">Export</a><a class="os-btn" href="step10_audit.php">Completion Audit</a><a class="os-btn primary" href="index.php">Dashboard</a></div></div></header>
<div class="os-layout"><aside class="os-sidebar"><div class="os-nav-label">Business OS</div><nav class="os-nav"><a href="index.php"><i class="dot"></i>Dashboard</a><a href="today_center.php"><i class="dot"></i>Today Center</a><a href="alerts_center.php"><i class="dot"></i>Alerts</a><a href="insights_center.php"><i class="dot"></i>Insights</a><a href="export_center.php"><i class="dot"></i>Export</a><a href="data_quality.php"><i class="dot"></i>Data Quality</a><a href="saved_views.php"><i class="dot"></i>Saved Views</a><a class="active" href="health_center.php"><i class="dot"></i>System Health</a><a href="step10_audit.php"><i class="dot"></i>Step 10 Audit</a></nav><div class="os-sidebar-status"><b>Environment diagnostics</b><span>Health Center is read-only except safe CREATE IF NOT EXISTS for Step 10 support tables.</span></div></aside><main class="os-main">
<section class="os-hero s10-hero"><div class="os-kicker">Step 10W • System Health</div><h1>Check database, extensions, workspaces and backup readiness before a problem reaches daily operations.</h1><p>Health Center validates the environment without changing legacy or normalized business facts.</p><div class="os-status-row"><span class="os-chip <?= $healthy?'good':'' ?>"><?= $healthy?'SYSTEM HEALTH PASS':'Review recommended' ?></span><span class="os-chip good"><?= number_format($passed) ?> checks pass</span><span class="os-chip"><?= number_format($failed) ?> review</span><span class="os-chip">PHP <?= step10_h(PHP_VERSION) ?></span></div></section>
<?php if($error):?><div class="s10-alert bad"><strong>Health diagnostic:</strong> <?= step10_h($error) ?></div><?php else:?>
<section class="s10-kpis"><div class="s10-kpi"><small>Database Tables</small><strong><?= number_format($tableCount) ?></strong><span>Current schema objects</span></div><div class="s10-kpi"><small>Database Size</small><strong><?= number_format($dbSize/1048576,1) ?> MB</strong><span>Data + indexes</span></div><div class="s10-kpi"><small>Schema Version</small><strong style="font-size:1rem"><?= step10_h($schemaVersion) ?></strong><span>schema_meta</span></div><div class="s10-kpi"><small>Manual Raw</small><strong><?= number_format($manualRaw) ?></strong><span>Business OS source records</span></div></section>
<section class="s10-grid"><article class="s10-card s10-span-8"><h2>Environment & Engine Checks</h2><p>Core runtime and data architecture readiness.</p><div class="s10-checks"><?php foreach($checks as $c):?><div class="s10-check <?= $c['ok']?'good':'warn' ?>"><div><b><?= step10_h($c['name']) ?></b><span><?= step10_h($c['detail']) ?></span></div><strong><?= $c['ok']?'PASS':'REVIEW' ?></strong></div><?php endforeach;?></div></article><aside class="s10-card s10-span-4"><h2>Backup Readiness</h2><p>STEP 10 prepares safe export and environment visibility; it does not silently schedule server backups.</p><div class="s10-list"><div class="s10-row"><div><b>CSV/Print Export</b><small>Operational data can be exported from Export Center.</small></div><a class="s10-link" href="export_center.php">Open →</a></div><div class="s10-row"><div><b>Raw Source Preservation</b><small>Legacy and MANUAL raw records remain traceable.</small></div><span class="s10-badge">ACTIVE</span></div><div class="s10-row"><div><b>Reverse/Restore Safety</b><small>No hard-delete workflow for MANUAL facts.</small></div><span class="s10-badge">ACTIVE</span></div><div class="s10-row"><div><b>Production Backup</b><small>Configure hosting/database scheduled backups when cloud deployment begins.</small></div><span class="s10-badge warn">DEPLOYMENT</span></div></div></aside></section>
<?php endif;?></main></div></body></html>
