<?php
declare(strict_types=1);

require_once __DIR__ . '/config/database.php';
require_once __DIR__ . '/xlsx_reader.php';

const MAX_WORKBOOK_BYTES = 20 * 1024 * 1024;

$mappingConfig = require __DIR__ . '/config/import_mapping.php';
$sourceMapping = is_array($mappingConfig['source_sheets'] ?? null) ? $mappingConfig['source_sheets'] : [];
$mappingVersion = (string)($mappingConfig['version'] ?? 'unknown');
$schemaSupportRequired = is_array($mappingConfig['schema_support_required'] ?? null) ? $mappingConfig['schema_support_required'] : [];

$derivedSheets = [
    'Master_Tracking' => 'Overall business summary generated from normalized source records.',
    'SP_House' => 'Supervisor / PC / AS / Team VP summary generated by the calculation engine.',
    'Name_Wise_Tracking' => 'Member-wise report generated from members, UMS, orders, VP and renewals.',
    'Master_Business_Tracking' => 'Business-level report generated from operational transactions.',
    'UMS_Renewal' => 'Renewal status report generated from UMS and renewal history.',
    'UMS_Active_Duration' => 'Active-duration report generated from UMS dates and renewal history.',
];

$sourcePlan = [];
foreach ($sourceMapping as $sheetName => $sheetConfig) {
    $sourcePlan[$sheetName] = (string)($sheetConfig['target'] ?? 'Raw source only');
}

$status = business_db_status();
$error = null;
$workbookName = null;
$workbookHash = null;
$workbookSize = null;
$sheetPreviews = [];
$foundSourceSheets = [];
$foundDerivedSheets = [];
$totalSourceRows = 0;
$totalMappingIssues = 0;

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    try {
        if (!isset($_FILES['workbook']) || !is_array($_FILES['workbook'])) {
            throw new RuntimeException('Choose an XLSX workbook first.');
        }

        $file = $_FILES['workbook'];
        $uploadError = (int)($file['error'] ?? UPLOAD_ERR_NO_FILE);
        if ($uploadError !== UPLOAD_ERR_OK) {
            throw new RuntimeException(match ($uploadError) {
                UPLOAD_ERR_INI_SIZE, UPLOAD_ERR_FORM_SIZE => 'The workbook is larger than the server upload limit.',
                UPLOAD_ERR_PARTIAL => 'The workbook upload was incomplete. Please try again.',
                UPLOAD_ERR_NO_FILE => 'Choose an XLSX workbook first.',
                default => 'The workbook upload failed. Error code: ' . $uploadError,
            });
        }

        $tmpPath = (string)($file['tmp_name'] ?? '');
        $originalName = basename((string)($file['name'] ?? 'workbook.xlsx'));
        $size = (int)($file['size'] ?? 0);
        $extension = strtolower(pathinfo($originalName, PATHINFO_EXTENSION));

        if (!is_uploaded_file($tmpPath)) {
            throw new RuntimeException('The workbook upload could not be verified.');
        }
        if ($extension !== 'xlsx') {
            throw new RuntimeException('Only .xlsx workbooks are accepted in this import preview.');
        }
        if ($size <= 0 || $size > MAX_WORKBOOK_BYTES) {
            throw new RuntimeException('Workbook size must be between 1 byte and 20 MB.');
        }

        $workbookName = $originalName;
        $workbookSize = $size;
        $workbookHash = hash_file('sha256', $tmpPath) ?: null;

        $reader = new XlsxPreviewReader($tmpPath);
        foreach ($reader->sheets() as $sheet) {
            $name = (string)$sheet['name'];
            $trimmed = trim($name);

            if (array_key_exists($name, $derivedSheets)) {
                $foundDerivedSheets[] = $name;
                continue;
            }

            if (array_key_exists($trimmed, $sourceMapping)) {
                $sheetMap = $sourceMapping[$trimmed];
                $preview = $reader->previewSheet((string)$sheet['path'], $name, 3);
                $preview['plan'] = (string)($sheetMap['target'] ?? 'Raw source only');
                $preview['normalization_status'] = (string)($sheetMap['normalization_status'] ?? 'review');
                $preview['mapping_issues'] = mappingHeaderIssues($preview, $sheetMap);
                $preview['mapping_notes'] = (string)($sheetMap['notes'] ?? '');
                $sheetPreviews[] = $preview;
                $foundSourceSheets[] = $trimmed;
                $totalSourceRows += (int)$preview['record_count'];
                $totalMappingIssues += count($preview['mapping_issues']);
            }
        }
    } catch (Throwable $e) {
        $error = $e->getMessage();
    }
}

function h(?string $value): string
{
    return htmlspecialchars((string)$value, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8');
}

function formatBytes(?int $bytes): string
{
    if (!$bytes) {
        return '—';
    }
    if ($bytes >= 1024 * 1024) {
        return number_format($bytes / (1024 * 1024), 2) . ' MB';
    }
    return number_format($bytes / 1024, 1) . ' KB';
}

function previewValue(string $header, ?string $value): string
{
    if ($value === null || trim($value) === '') {
        return '—';
    }

    if (stripos($header, 'date') !== false && is_numeric($value)) {
        $serial = (int)floor((float)$value);
        if ($serial > 20000 && $serial < 90000) {
            try {
                return (new DateTimeImmutable('1899-12-30'))->modify('+' . $serial . ' days')->format('d M Y');
            } catch (Throwable) {
                // Fall through to the cached raw value.
            }
        }
    }

    if (is_numeric($value)) {
        $number = (float)$value;
        if (abs($number - round($number)) < 0.0000001) {
            return (string)(int)round($number);
        }
        return rtrim(rtrim(number_format($number, 3, '.', ''), '0'), '.');
    }

    return $value;
}

/**
 * @param array<string,mixed> $preview
 * @param array<string,mixed> $sheetMap
 * @return array<int,string>
 */
function mappingHeaderIssues(array $preview, array $sheetMap): array
{
    $issues = [];
    $actualHeaders = is_array($preview['headers'] ?? null) ? $preview['headers'] : [];
    $expectedColumns = is_array($sheetMap['columns'] ?? null) ? $sheetMap['columns'] : [];

    foreach ($expectedColumns as $column => $columnConfig) {
        $role = (string)($columnConfig['role'] ?? '');
        $expected = trim((string)($columnConfig['header'] ?? ''));

        if (!array_key_exists($column, $actualHeaders)) {
            if ($role !== 'ignore') {
                $issues[] = $column . ' missing (expected ' . ($expected !== '' ? $expected : 'blank heading') . ')';
            }
            continue;
        }

        $actual = trim((string)$actualHeaders[$column]);
        if ($actual !== $expected) {
            $issues[] = $column . ' heading changed: expected "' . ($expected !== '' ? $expected : '(blank)') . '", found "' . ($actual !== '' ? $actual : '(blank)') . '"';
        }
    }

    return $issues;
}

function statusLabel(string $status): string
{
    return match ($status) {
        'ready' => 'NORMALIZATION READY',
        'support_table' => 'SUPPORT TABLE NEEDED',
        'partial' => 'PARTIAL • RAW SAFE',
        default => 'REVIEW',
    };
}

$missingSourceSheets = array_values(array_diff(array_keys($sourcePlan), array_unique($foundSourceSheets)));
$missingDerivedSheets = array_values(array_diff(array_keys($derivedSheets), array_unique($foundDerivedSheets)));
?>
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <meta name="robots" content="noindex,nofollow">
  <title>Excel Import Preview - Healthcare Wellness Club</title>
  <link rel="stylesheet" href="assets/import.css">
</head>
<body>
<header class="imp-topbar">
  <div class="imp-topbar-inner">
    <a class="imp-brand" href="index.php">
      <img src="../img/logo.png" alt="Healthcare Wellness Club logo">
      <span><strong>Healthcare Wellness Club</strong><small>Business OS • Safe Excel Import Preview</small></span>
    </a>
    <nav class="imp-nav" aria-label="Business navigation">
      <a href="index.php">← Business OS</a>
      <a href="../index.html">Public Website</a>
    </nav>
  </div>
</header>

<main class="imp-shell">
  <section class="imp-hero">
    <div>
      <div class="imp-kicker">Step 8 • Reviewed Source Mapping</div>
      <h1>Inspect first. Preserve the original rows. Normalize only what the workbook proves.</h1>
      <p>The eight operational sheets now have an exact column-letter mapping. Duplicate headings, blank helper columns and uncertain financial semantics are preserved instead of being guessed.</p>
    </div>
    <div class="imp-safety">
      <span class="imp-chip good">Database write is OFF</span>
      <span class="imp-chip good">Mapping <?= h($mappingVersion) ?></span>
      <span class="imp-chip good">Sheets 1–6 are skipped</span>
    </div>
  </section>

  <section class="imp-grid">
    <article class="imp-card imp-upload">
      <h2>Choose the master workbook</h2>
      <p>Use the downloaded <strong>Master_Personal_Tracking.xlsx</strong>. This step only validates the workbook against the reviewed mapping; it does not create members, orders, UMS, VP or income records.</p>

      <form method="post" enctype="multipart/form-data" class="imp-drop">
        <label for="workbook">Excel workbook (.xlsx)</label>
        <input id="workbook" name="workbook" type="file" accept=".xlsx,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" required>
        <button class="imp-submit" type="submit">Validate Workbook Mapping →</button>
        <div class="imp-hint">Maximum preview size: 20 MB. The uploaded file remains temporary and is removed automatically by PHP after the request.</div>
      </form>

      <?php if ($error !== null): ?>
        <div class="imp-alert"><strong>Preview could not run:</strong> <?= h($error) ?></div>
      <?php elseif ($workbookName !== null): ?>
        <div class="imp-alert good"><strong>Validation completed:</strong> <?= h($workbookName) ?> was read successfully. No business data was written to MySQL.</div>
      <?php endif; ?>
    </article>

    <aside class="imp-card imp-plan">
      <h2>Reviewed source mapping</h2>
      <p>Each source sheet now has a deliberate normalization status instead of being forced into a generic table.</p>
      <div class="imp-plan-list">
        <?php foreach ($sourceMapping as $sheet => $sheetConfig): ?>
          <div class="imp-plan-row">
            <div><b><?= h($sheet) ?></b><span><?= h((string)($sheetConfig['target'] ?? 'Raw source only')) ?> • <?= h(statusLabel((string)($sheetConfig['normalization_status'] ?? 'review'))) ?></span></div>
            <em>Mapped</em>
          </div>
        <?php endforeach; ?>
      </div>
    </aside>

    <?php if ($workbookName !== null && $error === null): ?>
      <section class="imp-summary" aria-label="Workbook preview summary">
        <article class="imp-kpi green"><small>Workbook</small><strong><?= h($workbookName) ?></strong><span><?= h(formatBytes($workbookSize)) ?></span></article>
        <article class="imp-kpi blue"><small>Source Sheets Found</small><strong><?= count($sheetPreviews) ?> / <?= count($sourceMapping) ?></strong><span><?= number_format($totalSourceRows) ?> operational rows</span></article>
        <article class="imp-kpi gold"><small>Derived Sheets Found</small><strong><?= count($foundDerivedSheets) ?> / <?= count($derivedSheets) ?></strong><span>Skipped from source import</span></article>
        <article class="imp-kpi"><small>Mapping Check</small><strong><?= $totalMappingIssues === 0 ? 'PASS' : number_format($totalMappingIssues) . ' ISSUE(S)' ?></strong><span><?= h($mappingVersion) ?></span></article>
      </section>

      <?php if ($missingSourceSheets || $missingDerivedSheets || $totalMappingIssues > 0): ?>
        <div class="imp-alert" style="grid-column:span 12">
          <strong>Workbook structure needs review.</strong>
          <?php if ($missingSourceSheets): ?> Missing source sheet(s): <?= h(implode(', ', $missingSourceSheets)) ?>.<?php endif; ?>
          <?php if ($missingDerivedSheets): ?> Missing derived sheet(s): <?= h(implode(', ', $missingDerivedSheets)) ?>.<?php endif; ?>
          <?php if ($totalMappingIssues > 0): ?> <?= number_format($totalMappingIssues) ?> mapped column heading(s) changed from the reviewed workbook.<?php endif; ?>
        </div>
      <?php endif; ?>

      <section class="imp-results">
        <?php foreach ($sheetPreviews as $preview): ?>
          <article class="imp-sheet">
            <div class="imp-sheet-head">
              <div class="imp-sheet-title">
                <b><?= h(trim((string)$preview['name'])) ?></b>
                <span><?= number_format((int)$preview['record_count']) ?> records • Target: <?= h((string)$preview['plan']) ?></span>
              </div>
              <span class="imp-sheet-status"><?= h(statusLabel((string)$preview['normalization_status'])) ?></span>
            </div>

            <?php if ($preview['duplicate_headers'] || $preview['blank_header_columns'] || $preview['mapping_issues']): ?>
              <div class="imp-issues">
                <?php if ($preview['duplicate_headers']): ?>
                  <span class="imp-issue">Duplicate headings preserved: <?= h(implode(', ', $preview['duplicate_headers'])) ?></span>
                <?php endif; ?>
                <?php if ($preview['blank_header_columns']): ?>
                  <span class="imp-issue">Blank heading column(s): <?= h(implode(', ', $preview['blank_header_columns'])) ?></span>
                <?php endif; ?>
                <?php foreach ($preview['mapping_issues'] as $mappingIssue): ?>
                  <span class="imp-issue"><?= h((string)$mappingIssue) ?></span>
                <?php endforeach; ?>
              </div>
            <?php endif; ?>

            <?php if ((string)$preview['mapping_notes'] !== ''): ?>
              <div class="imp-hint" style="margin-top:10px"><strong>Mapping note:</strong> <?= h((string)$preview['mapping_notes']) ?></div>
            <?php endif; ?>

            <div class="imp-headers">
              <?php foreach ($preview['headers'] as $column => $header): ?>
                <span class="imp-header"><code><?= h((string)$column) ?></code> · <?= h($header !== '' ? (string)$header : '(blank)') ?></span>
              <?php endforeach; ?>
            </div>

            <?php if ($preview['samples']): ?>
              <div class="imp-table-wrap">
                <table class="imp-table">
                  <thead><tr>
                    <?php foreach ($preview['headers'] as $column => $header): ?>
                      <th><?= h((string)$column) ?> · <?= h($header !== '' ? (string)$header : '(blank)') ?></th>
                    <?php endforeach; ?>
                  </tr></thead>
                  <tbody>
                    <?php foreach ($preview['samples'] as $row): ?>
                      <tr>
                        <?php foreach ($preview['headers'] as $column => $header): ?>
                          <td><?= h(previewValue((string)$header, $row[$column] ?? null)) ?></td>
                        <?php endforeach; ?>
                      </tr>
                    <?php endforeach; ?>
                  </tbody>
                </table>
              </div>
            <?php endif; ?>
          </article>
        <?php endforeach; ?>
      </section>
    <?php endif; ?>

    <article class="imp-card imp-derived">
      <h2>Schema support identified before live import</h2>
      <p>The reviewed workbook exposed two operational datasets that deserve dedicated fact tables. We will add these before enabling database writes rather than forcing them into the wrong entities.</p>
      <div class="imp-derived-list">
        <?php foreach ($schemaSupportRequired as $table => $description): ?>
          <div class="imp-derived-item"><b><?= h((string)$table) ?></b><span><?= h((string)$description) ?></span></div>
        <?php endforeach; ?>
      </div>
    </article>

    <article class="imp-card imp-derived">
      <h2>Six calculation/report sheets — intentionally not imported</h2>
      <p>These remain calculation references. In a later phase their formulas will be translated into versioned Business OS calculation rules.</p>
      <div class="imp-derived-list">
        <?php foreach ($derivedSheets as $sheet => $description): ?>
          <div class="imp-derived-item"><b><?= h($sheet) ?></b><span><?= h($description) ?></span></div>
        <?php endforeach; ?>
      </div>
    </article>

    <div class="imp-footer-note">
      <strong>Safety rule for Step 8:</strong> this page still writes nothing to <code>raw_source_records</code> or normalized business tables. The reviewed mapping uses column letters as the authority, preserves every original source row, and refuses to guess ambiguous financial/product fields. Database import will be enabled only after the two support tables are added and this mapping remains clean.
      Database status: <?= h($status['connected'] ? 'Online' : 'Pending') ?> • Schema: <?= h((string)$status['schema_version']) ?>.
    </div>
  </section>
</main>
<script src="assets/business-collapsible.js?v=20260820-1" defer></script>
</body>
</html>
