<?php
declare(strict_types=1);

require_once __DIR__ . '/config/step10_services.php';

$error=null;$status=business_db_status();$ctx=['organization_id'=>0,'club_id'=>0];$legacy=['total'=>0,'mapped'=>0,'pending'=>0];$recent=[];$metrics=[
 'members'=>0,'vp_facts'=>0,'orders'=>0,'renewals'=>0,'income'=>0,'royalty'=>0,'active_snapshots'=>0,'manual_raw'=>0,'reports'=>0,'open_followups'=>0,'due_today'=>0,'overdue'=>0,'reversed'=>0
];
$rev=defined('BUSINESS_REVERSED_SOURCE_SHEET')?BUSINESS_REVERSED_SOURCE_SHEET:'Manual Entry • Reversed';
$requiredStep10=['report_center.php','members.php','sponsor_network.php','member_profile.php','operations_center.php','data_entry_center.php','report_integration_audit.php','correction_center.php','reversal_center.php','restore_center.php','audit_center.php','data_management.php','global_search.php','alerts_center.php','insights_center.php','export_center.php','data_quality.php','today_center.php','saved_views.php','health_center.php','step10_audit.php'];

try{
 if(!$status['connected'])throw new RuntimeException('Database connection is not ready.');
 $pdo=business_db();$ctx=step10_org_context($pdo);step10_ensure_tables($pdo);$orgId=(int)$ctx['organization_id'];$legacy=step10_legacy_state($pdo,$orgId);
 $queries=[
  'members'=>"SELECT COUNT(*) FROM members WHERE organization_id=? AND COALESCE(source_sheet,'')<>?",
  'vp_facts'=>"SELECT COUNT(*) FROM volume_point_entries WHERE organization_id=? AND COALESCE(source_sheet,'')<>?",
  'orders'=>"SELECT COUNT(*) FROM orders WHERE organization_id=? AND COALESCE(source_sheet,'')<>?",
  'renewals'=>"SELECT COUNT(*) FROM renewals WHERE organization_id=? AND COALESCE(source_sheet,'')<>?",
  'income'=>"SELECT COUNT(*) FROM income_entries WHERE organization_id=? AND COALESCE(source_sheet,'')<>?",
  'royalty'=>"SELECT COUNT(*) FROM royalty_entries WHERE organization_id=? AND COALESCE(source_sheet,'')<>?",
 ];
 foreach($queries as $k=>$sql){if(!business_table_exists($pdo,$k==='vp_facts'?'volume_point_entries':($k==='income'?'income_entries':($k==='royalty'?'royalty_entries':$k))))continue;$stmt=$pdo->prepare($sql);$stmt->execute([$orgId,$rev]);$metrics[$k]=(int)$stmt->fetchColumn();}
 if(business_table_exists($pdo,'ums_activity_snapshots')){$stmt=$pdo->prepare("SELECT COUNT(*) FROM ums_activity_snapshots WHERE organization_id=?");$stmt->execute([$orgId]);$metrics['active_snapshots']=(int)$stmt->fetchColumn();}
 if(business_table_exists($pdo,'report_definitions')){$stmt=$pdo->prepare("SELECT COUNT(*) FROM report_definitions WHERE organization_id=? AND is_active=1");$stmt->execute([$orgId]);$metrics['reports']=(int)$stmt->fetchColumn();}
 $stmt=$pdo->prepare("SELECT id FROM data_sources WHERE organization_id=? AND source_code='MANUAL' LIMIT 1");$stmt->execute([$orgId]);$manualId=(int)$stmt->fetchColumn();if($manualId>0){$stmt=$pdo->prepare("SELECT COUNT(*) FROM raw_source_records WHERE organization_id=? AND data_source_id=?");$stmt->execute([$orgId,$manualId]);$metrics['manual_raw']=(int)$stmt->fetchColumn();}
 $today=date('Y-m-d');
 $stmt=$pdo->prepare("SELECT COUNT(*) FROM business_followups WHERE organization_id=? AND status='open'");$stmt->execute([$orgId]);$metrics['open_followups']=(int)$stmt->fetchColumn();
 $stmt=$pdo->prepare("SELECT COUNT(*) FROM business_followups WHERE organization_id=? AND status='open' AND due_date=?");$stmt->execute([$orgId,$today]);$metrics['due_today']=(int)$stmt->fetchColumn();
 $stmt=$pdo->prepare("SELECT COUNT(*) FROM business_followups WHERE organization_id=? AND status='open' AND due_date<?");$stmt->execute([$orgId,$today]);$metrics['overdue']=(int)$stmt->fetchColumn();
 foreach(['members','volume_point_entries','orders','renewals','income_entries','royalty_entries'] as $table){if(!business_table_exists($pdo,$table))continue;$stmt=$pdo->prepare("SELECT COUNT(*) FROM `{$table}` WHERE organization_id=? AND source_sheet=?");$stmt->execute([$orgId,$rev]);$metrics['reversed']+=(int)$stmt->fetchColumn();}
 if(business_table_exists($pdo,'audit_logs')){$stmt=$pdo->prepare("SELECT id,event_type,entity_type,entity_id,created_at FROM audit_logs WHERE organization_id=? ORDER BY id DESC LIMIT 8");$stmt->execute([$orgId]);$recent=$stmt->fetchAll();}
}catch(Throwable $e){$error=$e->getMessage();}

$sourceReady=$legacy['total']===757&&$legacy['mapped']===757&&$legacy['pending']===0;$reportsReady=$metrics['reports']===6;$filesReady=true;foreach($requiredStep10 as $f)if(!is_file(__DIR__.'/'.$f)){$filesReady=false;break;}$step10Ready=$error===null&&$sourceReady&&$reportsReady&&$filesReady;
$liveReports=[['Master Tracking','master_tracking.php'],['SP House','sp_house.php'],['Name Wise Tracking','name_wise_tracking.php'],['Master Business','master_business_tracking.php'],['UMS Renewal','ums_renewal.php'],['Active Duration','ums_active_duration.php']];
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>Business OS Dashboard - Healthcare Wellness Club</title><link rel="stylesheet" href="assets/dashboard.css"><link rel="stylesheet" href="assets/step10.css"></head><body>
<header class="os-topbar"><div class="os-topbar-inner"><a class="os-brand" href="../index.html"><img src="../img/logo.png" alt="Healthcare Wellness Club logo"><span><strong>Healthcare Wellness Club</strong><small>Business OS • STEP 10 COMPLETE</small></span></a><div class="os-top-actions"><a class="os-btn" href="today_center.php">Today</a><a class="os-btn" href="global_search.php">⌕ Search</a><a class="os-btn" href="alerts_center.php">Alerts</a><a class="os-btn primary" href="report_center.php">Reports</a></div></div></header>
<div class="os-layout"><aside class="os-sidebar"><div class="os-nav-label">Command</div><nav class="os-nav"><a class="active" href="index.php"><i class="dot"></i>Dashboard</a><a href="today_center.php"><i class="dot"></i>Today Center</a><a href="global_search.php"><i class="dot"></i>Global Search</a><a href="alerts_center.php"><i class="dot"></i>Alerts & Follow-ups</a><a href="saved_views.php"><i class="dot"></i>Saved Views</a></nav><div class="os-nav-label" style="margin-top:8px">Business</div><nav class="os-nav"><a href="insights_center.php"><i class="dot"></i>Insights</a><a href="operations_center.php"><i class="dot"></i>Operations</a><a href="members.php"><i class="dot"></i>Members & Network</a><a href="member_profile.php"><i class="dot"></i>Profile 360°</a><a href="sponsor_network.php"><i class="dot"></i>Sponsor Network</a><a href="data_management.php"><i class="dot"></i>Data Management</a><a href="report_center.php"><i class="dot"></i>Report Center</a><a href="export_center.php"><i class="dot"></i>Export</a><a href="data_quality.php"><i class="dot"></i>Data Quality</a><a href="health_center.php"><i class="dot"></i>System Health</a><a href="step10_audit.php"><i class="dot"></i>Step 10 Audit</a></nav><div class="os-sidebar-status"><b><?= $step10Ready?'STEP 10 operational':'Review required' ?></b><span><?= number_format($legacy['mapped']) ?> / 757 legacy mapped • <?= number_format($metrics['reports']) ?> / 6 reports.</span></div></aside><main class="os-main">
<section class="os-hero s10-hero"><div class="os-kicker">STEP 10 COMPLETE • Business OS Foundation</div><h1>Daily operations, members, reports, search, alerts, insights and audited data management now work as one connected system.</h1><p>The legacy workbook remains preserved as historical evidence, while new MANUAL facts use a traceable create → correct → reverse → restore → audit lifecycle. STEP 10 adds the command, quality, export and health layer around that foundation.</p><div class="os-status-row"><span class="os-chip <?= $step10Ready?'good':'' ?>"><?= $step10Ready?'STEP 10 COMPLETE':'Completion review' ?></span><span class="os-chip good"><?= number_format($legacy['mapped']) ?> / 757 legacy mapped</span><span class="os-chip good"><?= number_format($metrics['reports']) ?> / 6 live reports</span><span class="os-chip"><?= number_format($metrics['open_followups']) ?> open follow-ups</span><span class="os-chip"><?= number_format($metrics['manual_raw']) ?> manual raw</span><span class="os-chip">Schema <?= step10_h((string)$status['schema_version']) ?></span></div></section>
<?php if($error):?><div class="s10-alert bad"><strong>Dashboard diagnostic:</strong> <?= step10_h($error) ?></div><?php endif;?>
<section class="s10-kpis"><div class="s10-kpi"><small>Members</small><strong><?= number_format($metrics['members']) ?></strong><span>Legacy + active MANUAL</span></div><div class="s10-kpi"><small>VP Facts</small><strong><?= number_format($metrics['vp_facts']) ?></strong><span>Normalized active facts</span></div><div class="s10-kpi"><small>Orders</small><strong><?= number_format($metrics['orders']) ?></strong><span>Reversed excluded</span></div><div class="s10-kpi"><small>Renewals</small><strong><?= number_format($metrics['renewals']) ?></strong><span>Verified/source-preserved</span></div></section>
<section class="s10-grid"><article class="s10-card s10-span-8"><div class="os-title-row"><div><h2>Start Here</h2><p>The five workspaces used most often in daily Business OS operation.</p></div><a class="os-btn primary" href="today_center.php">Open Today</a></div><div class="os-report-grid"><a class="os-report" href="today_center.php"><div class="os-report-head"><b>Today Center</b><em>DAILY</em></div><span>Today facts, follow-ups, recent activity and quick commands.</span><small>Open →</small></a><a class="os-report" href="global_search.php"><div class="os-report-head"><b>Global Search</b><em>READ</em></div><span>Find member, order, VP, renewal, report or command.</span><small>Search →</small></a><a class="os-report" href="alerts_center.php"><div class="os-report-head"><b>Alerts & Follow-ups</b><em>ACTION</em></div><span>Fact-safe alerts and persistent audited reminders.</span><small>Review →</small></a><a class="os-report" href="insights_center.php"><div class="os-report-head"><b>Insights & Trends</b><em>LIVE</em></div><span>Month-to-month VP, orders, profit, income and royalty.</span><small>Analyze →</small></a><a class="os-report" href="data_management.php"><div class="os-report-head"><b>Data Management</b><em>SAFE WRITE</em></div><span>Create, Correct, Reverse, Restore and Audit MANUAL facts.</span><small>Manage →</small></a><a class="os-report" href="saved_views.php"><div class="os-report-head"><b>Saved Views</b><em>FAVORITES</em></div><span>One-click shortcuts for recurring filtered workspaces.</span><small>Open →</small></a></div></article>
<aside class="s10-card s10-span-4"><h2>Attention Queue</h2><p>Daily follow-up and preservation state.</p><div class="s10-list"><div class="s10-row"><div><b>Due Today</b><small>Open follow-ups</small></div><strong><?= number_format($metrics['due_today']) ?></strong></div><div class="s10-row"><div><b>Overdue</b><small>Open follow-ups before today</small></div><strong><?= number_format($metrics['overdue']) ?></strong></div><div class="s10-row"><div><b>Reversed Facts</b><small>Preserved, excluded from active effect</small></div><strong><?= number_format($metrics['reversed']) ?></strong></div><div class="s10-row"><div><b>Active Snapshots</b><small>Monthly UMS activity facts</small></div><strong><?= number_format($metrics['active_snapshots']) ?></strong></div></div><div class="s10-actions" style="margin-top:12px"><a href="alerts_center.php">Alerts →</a><a href="restore_center.php">Restore →</a></div></aside>
<article class="s10-card s10-span-7"><div class="os-title-row"><div><h2>Business Workspaces</h2><p>Operational and analytical views built on normalized facts.</p></div><a class="os-btn" href="operations_center.php">Operations</a></div><div class="os-links"><a class="os-link" href="members.php"><div><b>Members & Network</b><span>Identity-safe UMS, sponsor and activity context</span></div><span>→</span></a><a class="os-link" href="member_profile.php"><div><b>Member Profile 360°</b><span>Verified lifecycle and business timeline</span></div><span>→</span></a><a class="os-link" href="sponsor_network.php"><div><b>Sponsor Network</b><span>Verified exact-safe links and interactive tree</span></div><span>→</span></a><a class="os-link" href="export_center.php"><div><b>Export & Share</b><span>Filtered UTF-8 CSV + Print/Save PDF</span></div><span>→</span></a><a class="os-link" href="data_quality.php"><div><b>Data Quality</b><span>Duplicate/shared-mobile/sponsor/source diagnostics</span></div><span>→</span></a><a class="os-link" href="health_center.php"><div><b>System Health</b><span>Database, PHP extension and backup readiness</span></div><span>→</span></a></div></article>
<aside class="s10-card s10-span-5"><div class="os-title-row"><div><h2>Recent System Activity</h2><p>Latest audit events.</p></div><a class="os-btn" href="audit_center.php">Full Audit</a></div><div class="s10-list"><?php if(!$recent):?><div class="s10-row"><div><b>No recent activity</b><small>Audit events will appear here.</small></div></div><?php endif;?><?php foreach($recent as $a):?><div class="s10-row"><div><b><?= step10_h(ucwords(str_replace('_',' ',(string)$a['event_type']))) ?></b><small><?= step10_h((string)($a['entity_type']??'system')) ?><?= $a['entity_id']?' #'.(int)$a['entity_id']:'' ?></small></div><strong><?= step10_h(substr((string)$a['created_at'],5,11)) ?></strong></div><?php endforeach;?></div></aside>
<article class="s10-card s10-span-12"><div class="os-title-row"><div><h2>Six Live Derived Reports</h2><p>Workbook Sheets 1–6 are live derived views; they are not copied back as facts.</p></div><a class="os-btn primary" href="report_center.php">Report Center</a></div><div class="rc-report-grid"><?php foreach($liveReports as $i=>$r):?><div class="rc-card"><span class="num"><?= str_pad((string)($i+1),2,'0',STR_PAD_LEFT) ?></span><h3><?= step10_h($r[0]) ?></h3><p>Live derived report from normalized operational sources.</p><a href="<?= step10_h($r[1]) ?>">Open Live Report →</a></div><?php endforeach;?></div></article>
<article class="s10-card s10-span-12"><div class="os-title-row"><div><h2>STEP 10 Completion</h2><p>Run the A–Z completion audit after pulling this final batch.</p></div><a class="os-btn primary" href="step10_audit.php">Run STEP 10 Audit</a></div><div class="s10-list"><div class="s10-row"><div><b>Source-of-truth architecture</b><small>Legacy raw evidence + normalized facts + MANUAL lifecycle + audit trail.</small></div><span class="s10-badge">READY</span></div><div class="s10-row"><div><b>Desktop workspace width</b><small>1720px maximum with responsive tablet/mobile navigation strip.</small></div><span class="s10-badge">READY</span></div><div class="s10-row"><div><b>Next major phase</b><small>Product / Price / Order Commerce System can start after audit PASS.</small></div><span class="s10-badge violet">NEXT</span></div></div></article></section>
<div class="os-footer-note"><strong>STEP 10 COMPLETE:</strong> Business OS foundation now includes reports, members/network, operations, audited data management, global search, alerts/follow-ups, insights, exports, data quality, saved views, Today Center, system health and final completion audit. Legacy Excel rows remain isolated and reconciled.</div>
</main></div></body></html>
