<?php
declare(strict_types=1);
session_start();
require_once __DIR__ . '/config/inventory_step13.php';
if(empty($_SESSION['inventory_count_csrf']))$_SESSION['inventory_count_csrf']=bin2hex(random_bytes(24));
$csrf=(string)$_SESSION['inventory_count_csrf'];$error=null;$success=null;$rows=[];$counts=[];
try{
 $pdo=business_db();inventory_step13_ensure($pdo);$ctx=inventory_step13_context($pdo);$orgId=(int)$ctx['organization_id'];$locationId=(int)$ctx['location_id'];
 if($_SERVER['REQUEST_METHOD']==='POST'){
  if(!hash_equals($csrf,(string)($_POST['csrf']??'')))throw new RuntimeException('Security token mismatch.');
  $productId=(int)($_POST['product_id']??0);$counted=(float)($_POST['counted_quantity']??-1);$date=(string)($_POST['count_date']??date('Y-m-d'));$ref=trim((string)($_POST['reference_no']??''));$notes=trim((string)($_POST['notes']??''));
  $countId=inventory_step13_post_stock_count($pdo,$productId,$counted,$date,$ref,$notes);$success='Physical stock count #'.$countId.' posted.';
 }
 $rows=inventory_step13_stock_rows($pdo,$orgId,$locationId);
 $stmt=$pdo->prepare("SELECT c.id,c.count_date,c.reference_no,l.system_quantity,l.counted_quantity,l.variance_quantity,p.product_name,p.sku FROM inventory_stock_counts c JOIN inventory_stock_count_lines l ON l.stock_count_id=c.id JOIN products p ON p.id=l.product_id WHERE c.organization_id=? ORDER BY c.id DESC LIMIT 80");$stmt->execute([$orgId]);$counts=$stmt->fetchAll();
}catch(Throwable $e){$error=$e->getMessage();}
function st_h(mixed $v):string{return htmlspecialchars((string)$v,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8');}function st_n(mixed $v):string{$x=number_format((float)$v,3,'.','');return rtrim(rtrim($x,'0'),'.');}
?>
<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>Physical Stocktake - Healthcare Wellness Club</title><link rel="stylesheet" href="assets/dashboard.css"><link rel="stylesheet" href="assets/product_pro.css"></head><body>
<header class="os-topbar"><div class="os-topbar-inner"><a class="os-brand" href="inventory_center.php"><img src="../img/logo.png" alt="logo"><span><strong>Healthcare Wellness Club</strong><small>STEP 13 • Physical Stocktake</small></span></a><div class="os-top-actions"><a class="os-btn" href="inventory_center.php">Inventory</a><a class="os-btn primary" href="inventory_adjustments.php">Adjustments</a></div></div></header>
<div class="os-layout"><aside class="os-sidebar"><div class="os-nav-label">Inventory</div><nav class="os-nav"><a href="inventory_center.php"><i class="dot"></i>Inventory Center</a><a href="inventory_inward.php"><i class="dot"></i>Stock Inward</a><a href="inventory_adjustments.php"><i class="dot"></i>Damage / Returns</a><a class="active" href="inventory_stocktake.php"><i class="dot"></i>Physical Stocktake</a><a href="inventory_settings.php"><i class="dot"></i>Reorder Settings</a><a href="inventory_analytics.php"><i class="dot"></i>Analytics</a></nav></aside>
<main class="os-main"><section class="os-hero pp-hero"><div class="os-kicker">STEP 13D • PHYSICAL COUNT</div><h1>Reconcile the system with real physical stock without erasing history.</h1><p>Each count stores system quantity, counted quantity and variance. Any difference becomes an auditable inventory movement.</p><div class="os-status-row"><span class="os-chip <?= $error===null?'good':'' ?>"><?= $error===null?'STOCKTAKE LIVE':'Review required' ?></span><span class="os-chip"><?= count($counts) ?> recent count lines</span></div></section>
<?php if($error):?><div class="pp-alert bad"><strong>Stocktake diagnostic:</strong> <?= st_h($error) ?></div><?php endif;?><?php if($success):?><div class="pp-alert good"><strong>Saved:</strong> <?= st_h($success) ?></div><?php endif;?>
<?php if(!$error):?><section class="pp-grid" style="margin-top:14px"><article class="os-card pp-span-5"><h2>Post Physical Count</h2><form method="post" class="pp-form"><input type="hidden" name="csrf" value="<?= st_h($csrf) ?>"><label>Product<select name="product_id" required><option value="">Choose product…</option><?php foreach($rows as $r):?><option value="<?= (int)$r['product_id'] ?>"><?= st_h(($r['sku']?:'—').' • '.$r['product_name'].' • System '.st_n($r['stock_total'])) ?></option><?php endforeach;?></select></label><label>Counted Quantity<input type="number" min="0" step="0.001" name="counted_quantity" required></label><label>Count Date<input type="date" name="count_date" value="<?= st_h(date('Y-m-d')) ?>" required></label><label>Reference No.<input name="reference_no" maxlength="120" placeholder="Optional stocktake sheet / approval"></label><label>Notes<textarea name="notes" rows="3"></textarea></label><button>Post Count & Variance →</button></form></article><article class="os-card pp-span-7"><h2>Count History</h2><div class="pp-table-wrap"><table class="pp-table"><thead><tr><th>Date</th><th>Product</th><th>System</th><th>Counted</th><th>Variance</th><th>Reference</th></tr></thead><tbody><?php foreach($counts as $c):?><tr><td><?= st_h($c['count_date']) ?></td><td><b><?= st_h($c['sku']) ?></b><small><?= st_h($c['product_name']) ?></small></td><td><?= st_h(st_n($c['system_quantity'])) ?></td><td><?= st_h(st_n($c['counted_quantity'])) ?></td><td><b><?= (float)$c['variance_quantity']>0?'+':'' ?><?= st_h(st_n($c['variance_quantity'])) ?></b></td><td><?= st_h($c['reference_no']?:'—') ?></td></tr><?php endforeach;?><?php if(!$counts):?><tr><td colspan="6">No physical stock counts yet.</td></tr><?php endif;?></tbody></table></div></article></section><?php endif;?>
<div class="os-footer-note"><strong>Stocktake rule:</strong> count variance changes the current stock, but the original purchase/opening/sale movements remain preserved in the ledger.</div></main></div></body></html>