<?php
declare(strict_types=1);
session_start();
require_once __DIR__ . '/config/inventory_step13.php';
if(empty($_SESSION['inventory_settings_csrf']))$_SESSION['inventory_settings_csrf']=bin2hex(random_bytes(24));
$csrf=(string)$_SESSION['inventory_settings_csrf'];$error=null;$success=null;$rows=[];
try{
 $pdo=business_db();inventory_step13_ensure($pdo);$ctx=inventory_step13_context($pdo);$orgId=(int)$ctx['organization_id'];$locationId=(int)$ctx['location_id'];
 if($_SERVER['REQUEST_METHOD']==='POST'){
  if(!hash_equals($csrf,(string)($_POST['csrf']??'')))throw new RuntimeException('Security token mismatch.');
  $productId=(int)($_POST['product_id']??0);$track=isset($_POST['track_stock']);$reorder=(float)($_POST['reorder_level']??0);$target=(float)($_POST['target_stock']??0);$days=(int)($_POST['expiry_alert_days']??60);
  inventory_step13_update_setting($pdo,$productId,$track,$reorder,$target,$days);$success='Inventory setting saved.';
 }
 $rows=inventory_step13_stock_rows($pdo,$orgId,$locationId);
}catch(Throwable $e){$error=$e->getMessage();}
function is_h(mixed $v):string{return htmlspecialchars((string)$v,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8');}function is_n(mixed $v):string{$x=number_format((float)$v,3,'.','');return rtrim(rtrim($x,'0'),'.');}
?>
<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>Inventory Settings - Healthcare Wellness Club</title><link rel="stylesheet" href="assets/dashboard.css"><link rel="stylesheet" href="assets/product_pro.css"></head><body>
<header class="os-topbar"><div class="os-topbar-inner"><a class="os-brand" href="inventory_center.php"><img src="../img/logo.png" alt="logo"><span><strong>Healthcare Wellness Club</strong><small>STEP 13 • Inventory Settings</small></span></a><div class="os-top-actions"><a class="os-btn" href="inventory_center.php">Inventory</a><a class="os-btn primary" href="inventory_inward.php">+ Stock</a></div></div></header>
<div class="os-layout"><aside class="os-sidebar"><div class="os-nav-label">Inventory</div><nav class="os-nav"><a href="inventory_center.php"><i class="dot"></i>Inventory Center</a><a href="inventory_inward.php"><i class="dot"></i>Stock Inward</a><a href="inventory_adjustments.php"><i class="dot"></i>Damage / Returns</a><a href="inventory_stocktake.php"><i class="dot"></i>Physical Stocktake</a><a class="active" href="inventory_settings.php"><i class="dot"></i>Reorder Settings</a><a href="inventory_analytics.php"><i class="dot"></i>Analytics</a></nav></aside>
<main class="os-main"><section class="os-hero pp-hero"><div class="os-kicker">STEP 13C • INVENTORY POLICY</div><h1>Configure real reorder and expiry thresholds product by product.</h1><p>Default thresholds remain zero until you decide them. Tracking can be disabled for non-stock items without changing the Product Catalog.</p><div class="os-status-row"><span class="os-chip <?= $error===null?'good':'' ?>"><?= $error===null?'INVENTORY SETTINGS LIVE':'Review required' ?></span><span class="os-chip">No guessed thresholds</span></div></section>
<?php if($error):?><div class="pp-alert bad"><strong>Settings diagnostic:</strong> <?= is_h($error) ?></div><?php endif;?><?php if($success):?><div class="pp-alert good"><strong>Saved:</strong> <?= is_h($success) ?></div><?php endif;?>
<?php if(!$error):?><section class="os-card" style="margin-top:14px"><div class="pp-table-wrap"><table class="pp-table"><thead><tr><th>Stock</th><th>Product</th><th>Current</th><th>Tracking</th><th>Reorder</th><th>Target</th><th>Expiry Alert</th><th>Save</th></tr></thead><tbody><?php foreach($rows as $r):?><tr><form method="post"><input type="hidden" name="csrf" value="<?= is_h($csrf) ?>"><input type="hidden" name="product_id" value="<?= (int)$r['product_id'] ?>"><td><b><?= is_h($r['sku']?:'—') ?></b></td><td><?= is_h($r['product_name']) ?></td><td><?= is_h(is_n($r['sellable_stock'])) ?></td><td><label><input type="checkbox" name="track_stock" value="1" <?= $r['track_stock']?'checked':'' ?>> Track</label></td><td><input style="width:100px" type="number" min="0" step="0.001" name="reorder_level" value="<?= is_h(is_n($r['reorder_level'])) ?>"></td><td><input style="width:100px" type="number" min="0" step="0.001" name="target_stock" value="<?= is_h(is_n($r['target_stock'])) ?>"></td><td><input style="width:90px" type="number" min="0" max="3650" name="expiry_alert_days" value="<?= (int)$r['expiry_alert_days'] ?>"> days</td><td><button>Save</button></td></form></tr><?php endforeach;?></tbody></table></div></section><?php endif;?>
<div class="os-footer-note"><strong>Reorder suggestion:</strong> when Target Stock is set, suggested reorder quantity = Target Stock − current sellable stock, never below zero.</div></main></div><script src="assets/business-collapsible.js?v=20260820-1" defer></script></body></html>
