<?php
declare(strict_types=1);
require_once __DIR__ . '/config/inventory_step13.php';
$error=null;$rows=[];$ledger=[];$view=(string)($_GET['view']??'stock');if(!in_array($view,['stock','ledger'],true))$view='stock';
try{
 $pdo=business_db();inventory_step13_ensure($pdo);$ctx=inventory_step13_context($pdo);$orgId=(int)$ctx['organization_id'];$locationId=(int)$ctx['location_id'];$rows=inventory_step13_stock_rows($pdo,$orgId,$locationId);
 $stmt=$pdo->prepare("SELECT t.id,t.movement_date,t.movement_type,t.quantity_delta,t.unit_cost,t.reference_type,t.reference_id,t.source_reference,t.notes,p.product_name,p.sku,b.batch_code,b.expiry_date FROM inventory_transactions t JOIN products p ON p.id=t.product_id LEFT JOIN inventory_batches b ON b.id=t.batch_id WHERE t.organization_id=? AND t.location_id=? ORDER BY t.movement_date DESC,t.id DESC");$stmt->execute([$orgId,$locationId]);$ledger=$stmt->fetchAll();
 if(($_GET['format']??'')==='csv'){
  $filename=$view==='stock'?'inventory-current-stock.csv':'inventory-ledger.csv';header('Content-Type: text/csv; charset=UTF-8');header('Content-Disposition: attachment; filename="'.$filename.'"');echo "\xEF\xBB\xBF";$out=fopen('php://output','w');
  if($view==='stock'){fputcsv($out,['Stock No.','Product','Sellable','Total','Expired','Live Batches','Next Expiry','Reorder Level','Target Stock','Known Value']);foreach($rows as $r)fputcsv($out,[$r['sku'],$r['product_name'],$r['sellable_stock'],$r['stock_total'],$r['expired_stock'],$r['live_batches'],$r['next_expiry'],$r['reorder_level'],$r['target_stock'],$r['known_value']]);}
  else{fputcsv($out,['Transaction ID','Date','Type','Stock No.','Product','Batch','Expiry','Quantity Delta','Unit Cost','Reference Type','Reference ID','Source Reference','Notes']);foreach($ledger as $r)fputcsv($out,[$r['id'],$r['movement_date'],$r['movement_type'],$r['sku'],$r['product_name'],$r['batch_code'],$r['expiry_date'],$r['quantity_delta'],$r['unit_cost'],$r['reference_type'],$r['reference_id'],$r['source_reference'],$r['notes']]);}
  fclose($out);exit;
 }
}catch(Throwable $e){$error=$e->getMessage();}
function ex_h(mixed $v):string{return htmlspecialchars((string)$v,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8');}function ex_n(mixed $v):string{$x=number_format((float)$v,3,'.','');return rtrim(rtrim($x,'0'),'.');}function ex_m(mixed $v):string{return '₹'.number_format((float)$v,2,'.',',');}
?>
<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>Inventory Export - Healthcare Wellness Club</title><link rel="stylesheet" href="assets/dashboard.css"><link rel="stylesheet" href="assets/product_pro.css"><style>@media print{.os-topbar,.os-sidebar,.no-print{display:none!important}.os-layout{display:block;width:100%;margin:0}.os-main{width:100%}.os-card{box-shadow:none}}</style></head><body>
<header class="os-topbar"><div class="os-topbar-inner"><a class="os-brand" href="inventory_center.php"><img src="../img/logo.png" alt="logo"><span><strong>Healthcare Wellness Club</strong><small>STEP 13 • Inventory Export</small></span></a><div class="os-top-actions"><a class="os-btn" href="?view=<?= ex_h($view) ?>&format=csv">Download CSV</a><button class="os-btn" onclick="window.print()">Print / Save PDF</button><a class="os-btn primary" href="inventory_center.php">Inventory</a></div></div></header>
<div class="os-layout"><aside class="os-sidebar"><div class="os-nav-label">Inventory</div><nav class="os-nav"><a href="inventory_center.php"><i class="dot"></i>Inventory Center</a><a href="inventory_analytics.php"><i class="dot"></i>Analytics</a><a class="active" href="inventory_export.php"><i class="dot"></i>Export / Print</a><a href="step13_audit.php"><i class="dot"></i>STEP 13 Audit</a></nav></aside>
<main class="os-main"><section class="os-hero pp-hero no-print"><div class="os-kicker">STEP 13G • EXPORT & SHARE</div><h1>Export current stock or the full movement ledger.</h1><p>CSV is UTF-8 for spreadsheet use; Print / Save PDF uses the same visible source data.</p><div class="os-status-row"><span class="os-chip <?= $error===null?'good':'' ?>"><?= $error===null?'INVENTORY EXPORT LIVE':'Review required' ?></span><span class="os-chip"><?= count($rows) ?> stock rows</span><span class="os-chip"><?= count($ledger) ?> ledger movements</span></div></section>
<?php if($error):?><div class="pp-alert bad"><strong>Export diagnostic:</strong> <?= ex_h($error) ?></div><?php else:?><section class="os-card" style="margin-top:14px"><div class="os-title-row no-print"><div><h2><?= $view==='stock'?'Current Stock':'Stock Ledger' ?></h2></div><div><a class="os-btn <?= $view==='stock'?'primary':'' ?>" href="?view=stock">Current Stock</a> <a class="os-btn <?= $view==='ledger'?'primary':'' ?>" href="?view=ledger">Ledger</a></div></div><div class="pp-table-wrap"><table class="pp-table"><?php if($view==='stock'):?><thead><tr><th>Stock</th><th>Product</th><th>Sellable</th><th>Total</th><th>Expired</th><th>Batches</th><th>Next Expiry</th><th>Known Value</th></tr></thead><tbody><?php foreach($rows as $r):?><tr><td><b><?= ex_h($r['sku']) ?></b></td><td><?= ex_h($r['product_name']) ?></td><td><?= ex_h(ex_n($r['sellable_stock'])) ?></td><td><?= ex_h(ex_n($r['stock_total'])) ?></td><td><?= ex_h(ex_n($r['expired_stock'])) ?></td><td><?= number_format((int)$r['live_batches']) ?></td><td><?= ex_h($r['next_expiry']?:'—') ?></td><td><?= ex_m($r['known_value']) ?></td></tr><?php endforeach;?></tbody><?php else:?><thead><tr><th>ID</th><th>Date</th><th>Type</th><th>Product</th><th>Batch</th><th>Delta</th><th>Cost</th><th>Reference</th></tr></thead><tbody><?php foreach($ledger as $r):?><tr><td>#<?= (int)$r['id'] ?></td><td><?= ex_h($r['movement_date']) ?></td><td><?= ex_h(strtoupper(str_replace('_',' ',$r['movement_type']))) ?></td><td><b><?= ex_h($r['sku']) ?></b><small><?= ex_h($r['product_name']) ?></small></td><td><?= ex_h($r['batch_code']?:'—') ?></td><td><b><?= (float)$r['quantity_delta']>0?'+':'' ?><?= ex_h(ex_n($r['quantity_delta'])) ?></b></td><td><?= $r['unit_cost']!==null?ex_m($r['unit_cost']):'—' ?></td><td><?= ex_h($r['source_reference']?:(($r['reference_type']?:'').($r['reference_id']?' #'.$r['reference_id']:''))) ?></td></tr><?php endforeach;?></tbody><?php endif;?></table></div></section><?php endif;?>
<div class="os-footer-note"><strong>Export policy:</strong> inventory valuation shown here includes only batches with an explicit unit cost.</div></main></div><script src="assets/business-collapsible.js?v=20260820-1" defer></script></body></html>
