<?php
declare(strict_types=1);
session_start();
require_once __DIR__ . '/config/inventory_step13.php';

if (empty($_SESSION['inventory_adjust_csrf'])) $_SESSION['inventory_adjust_csrf'] = bin2hex(random_bytes(24));
$csrf=(string)$_SESSION['inventory_adjust_csrf'];$error=null;$success=null;$batches=[];$recent=[];
try{
 $pdo=business_db();inventory_step13_ensure($pdo);$ctx=inventory_step13_context($pdo);$orgId=(int)$ctx['organization_id'];$locationId=(int)$ctx['location_id'];
 if($_SERVER['REQUEST_METHOD']==='POST'){
  if(!hash_equals($csrf,(string)($_POST['csrf']??'')))throw new RuntimeException('Security token mismatch.');
  $batchId=(int)($_POST['batch_id']??0);$type=(string)($_POST['movement_type']??'damage');$qty=(float)($_POST['quantity']??0);$date=(string)($_POST['movement_date']??date('Y-m-d'));$reference=trim((string)($_POST['reference']??''));$notes=trim((string)($_POST['notes']??''));
  if($qty<=0)throw new RuntimeException('Quantity must be greater than zero.');
  $positive=in_array($type,['customer_return','adjustment_plus'],true);$delta=$positive?$qty:-$qty;
  $txId=inventory_step13_adjust_batch($pdo,$batchId,$delta,$date,$type,$reference,$notes);$success='Inventory adjustment #'.$txId.' posted.';
 }
 $stmt=$pdo->prepare("SELECT b.id,b.batch_code,b.current_quantity,b.expiry_date,p.product_name,p.sku FROM inventory_batches b JOIN products p ON p.id=b.product_id AND p.organization_id=b.organization_id WHERE b.organization_id=? AND b.location_id=? AND b.status='active' ORDER BY p.product_name,b.expiry_date,b.id");$stmt->execute([$orgId,$locationId]);$batches=$stmt->fetchAll();
 $stmt=$pdo->prepare("SELECT t.*,p.product_name,p.sku,b.batch_code FROM inventory_transactions t JOIN products p ON p.id=t.product_id LEFT JOIN inventory_batches b ON b.id=t.batch_id WHERE t.organization_id=? AND t.movement_type IN ('damage','loss','supplier_return','adjustment_minus','adjustment_plus','customer_return','stock_count') ORDER BY t.id DESC LIMIT 100");$stmt->execute([$orgId]);$recent=$stmt->fetchAll();
}catch(Throwable $e){$error=$e->getMessage();}
function ia_h(mixed $v):string{return htmlspecialchars((string)$v,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8');}function ia_n(mixed $v):string{$x=number_format((float)$v,3,'.','');return rtrim(rtrim($x,'0'),'.');}
?>
<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>Inventory Adjustments - Healthcare Wellness Club</title><link rel="stylesheet" href="assets/dashboard.css"><link rel="stylesheet" href="assets/product_pro.css"></head><body>
<header class="os-topbar"><div class="os-topbar-inner"><a class="os-brand" href="inventory_center.php"><img src="../img/logo.png" alt="logo"><span><strong>Healthcare Wellness Club</strong><small>STEP 13 • Damage, Returns & Adjustments</small></span></a><div class="os-top-actions"><a class="os-btn" href="inventory_inward.php">Stock Inward</a><a class="os-btn" href="inventory_stocktake.php">Stocktake</a><a class="os-btn primary" href="inventory_center.php">Inventory</a></div></div></header>
<div class="os-layout"><aside class="os-sidebar"><div class="os-nav-label">Inventory</div><nav class="os-nav"><a href="inventory_center.php"><i class="dot"></i>Inventory Center</a><a href="inventory_inward.php"><i class="dot"></i>Stock Inward</a><a class="active" href="inventory_adjustments.php"><i class="dot"></i>Damage / Returns</a><a href="inventory_stocktake.php"><i class="dot"></i>Physical Stocktake</a><a href="inventory_settings.php"><i class="dot"></i>Reorder Settings</a><a href="inventory_analytics.php"><i class="dot"></i>Analytics</a></nav></aside>
<main class="os-main"><section class="os-hero pp-hero"><div class="os-kicker">STEP 13B • CONTROLLED STOCK MOVEMENTS</div><h1>Record damage, loss, returns and corrections without deleting inventory history.</h1><p>Every adjustment targets a specific batch and creates a signed ledger movement. Negative stock is blocked unless a future explicit policy enables it.</p><div class="os-status-row"><span class="os-chip <?= $error===null?'good':'' ?>"><?= $error===null?'ADJUSTMENT CENTER LIVE':'Review required' ?></span><span class="os-chip">No hard delete</span><span class="os-chip">Batch-specific</span></div></section>
<?php if($error):?><div class="pp-alert bad"><strong>Adjustment diagnostic:</strong> <?= ia_h($error) ?></div><?php endif;?><?php if($success):?><div class="pp-alert good"><strong>Saved:</strong> <?= ia_h($success) ?></div><?php endif;?>
<?php if(!$error):?><section class="pp-grid" style="margin-top:14px"><article class="os-card pp-span-5"><h2>Post Adjustment</h2><form method="post" class="pp-form"><input type="hidden" name="csrf" value="<?= ia_h($csrf) ?>"><label>Movement Type<select name="movement_type"><option value="damage">Damage / Unsellable</option><option value="loss">Loss / Missing</option><option value="supplier_return">Return to Supplier</option><option value="adjustment_minus">Negative Correction</option><option value="customer_return">Customer Return (+)</option><option value="adjustment_plus">Positive Correction (+)</option></select></label><label>Batch<select name="batch_id" required><option value="">Choose batch…</option><?php foreach($batches as $b):?><option value="<?= (int)$b['id'] ?>"><?= ia_h(($b['sku']?:'—').' • '.$b['product_name'].' • '.$b['batch_code'].' • Qty '.ia_n($b['current_quantity']).($b['expiry_date']?' • Exp '.$b['expiry_date']:'')) ?></option><?php endforeach;?></select></label><label>Quantity<input type="number" name="quantity" min="0.001" step="0.001" required></label><label>Date<input type="date" name="movement_date" value="<?= ia_h(date('Y-m-d')) ?>" required></label><label>Reference<input name="reference" maxlength="190" placeholder="Return note, damage record, approval…"></label><label>Notes<textarea name="notes" rows="3"></textarea></label><button>Post Audited Adjustment →</button></form></article><article class="os-card pp-span-7"><h2>Adjustment History</h2><div class="pp-table-wrap"><table class="pp-table"><thead><tr><th>Date</th><th>Product</th><th>Batch</th><th>Type</th><th>Delta</th><th>Reference</th></tr></thead><tbody><?php foreach($recent as $r):?><tr><td><?= ia_h($r['movement_date']) ?></td><td><b><?= ia_h($r['sku']) ?></b><small><?= ia_h($r['product_name']) ?></small></td><td><?= ia_h($r['batch_code']?:'—') ?></td><td><?= ia_h(strtoupper(str_replace('_',' ',$r['movement_type']))) ?></td><td><b><?= (float)$r['quantity_delta']>0?'+':'' ?><?= ia_h(ia_n($r['quantity_delta'])) ?></b></td><td><?= ia_h($r['source_reference']?:'—') ?></td></tr><?php endforeach;?><?php if(!$recent):?><tr><td colspan="6">No inventory adjustments yet.</td></tr><?php endif;?></tbody></table></div></article></section><?php endif;?>
<div class="os-footer-note"><strong>Safety:</strong> damage/loss/supplier-return never rewrites the original inward record. It adds a new negative movement so the complete stock trail remains visible.</div></main></div><script src="assets/business-collapsible.js?v=20260820-1" defer></script></body></html>
