<?php
declare(strict_types=1);
require_once __DIR__ . '/config/inventory_step13.php';
$error=null;$rows=[];$movement=[];$metrics=['value'=>0.0,'sellable'=>0.0,'expired'=>0.0,'low'=>0,'reorder_qty'=>0.0,'moves30'=>0,'sold30'=>0.0,'in30'=>0.0];
try{
 $pdo=business_db();inventory_step13_ensure($pdo);$ctx=inventory_step13_context($pdo);$orgId=(int)$ctx['organization_id'];$locationId=(int)$ctx['location_id'];$rows=inventory_step13_stock_rows($pdo,$orgId,$locationId);
 foreach($rows as &$r){$r['suggested_reorder']=max(0,(float)$r['target_stock']-(float)$r['sellable_stock']);$metrics['value']+=(float)$r['known_value'];$metrics['sellable']+=(float)$r['sellable_stock'];$metrics['expired']+=(float)$r['expired_stock'];if((float)$r['reorder_level']>0&&(float)$r['sellable_stock']<=(float)$r['reorder_level']+0.0005){$metrics['low']++;$metrics['reorder_qty']+=(float)$r['suggested_reorder'];}}unset($r);
 $stmt=$pdo->prepare("SELECT t.listing_id,p.product_name,p.sku,COUNT(*) movement_count,SUM(CASE WHEN t.quantity_delta<0 THEN ABS(t.quantity_delta) ELSE 0 END) qty_out,SUM(CASE WHEN t.quantity_delta>0 THEN t.quantity_delta ELSE 0 END) qty_in FROM inventory_transactions t JOIN products p ON p.id=t.product_id WHERE t.organization_id=? AND t.location_id=? AND t.status='active' AND t.movement_date>=DATE_SUB(CURDATE(),INTERVAL 30 DAY) GROUP BY t.listing_id,p.product_name,p.sku ORDER BY qty_out DESC,movement_count DESC LIMIT 40");$stmt->execute([$orgId,$locationId]);$movement=$stmt->fetchAll();
 foreach($movement as $m){$metrics['moves30']+=(int)$m['movement_count'];$metrics['sold30']+=(float)$m['qty_out'];$metrics['in30']+=(float)$m['qty_in'];}
}catch(Throwable $e){$error=$e->getMessage();}
function an_h(mixed $v):string{return htmlspecialchars((string)$v,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8');}function an_n(mixed $v):string{$x=number_format((float)$v,3,'.','');return rtrim(rtrim($x,'0'),'.');}function an_m(mixed $v):string{return '₹'.number_format((float)$v,2,'.',',');}
?>
<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>Inventory Analytics - Healthcare Wellness Club</title><link rel="stylesheet" href="assets/dashboard.css"><link rel="stylesheet" href="assets/product_pro.css"></head><body>
<header class="os-topbar"><div class="os-topbar-inner"><a class="os-brand" href="inventory_center.php"><img src="../img/logo.png" alt="logo"><span><strong>Healthcare Wellness Club</strong><small>STEP 13 • Inventory Analytics</small></span></a><div class="os-top-actions"><a class="os-btn" href="inventory_settings.php">Reorder Settings</a><a class="os-btn" href="inventory_export.php">Export</a><a class="os-btn primary" href="inventory_center.php">Inventory</a></div></div></header>
<div class="os-layout"><aside class="os-sidebar"><div class="os-nav-label">Inventory</div><nav class="os-nav"><a href="inventory_center.php"><i class="dot"></i>Inventory Center</a><a href="inventory_inward.php"><i class="dot"></i>Stock Inward</a><a href="inventory_adjustments.php"><i class="dot"></i>Damage / Returns</a><a href="inventory_stocktake.php"><i class="dot"></i>Physical Stocktake</a><a href="inventory_settings.php"><i class="dot"></i>Reorder Settings</a><a class="active" href="inventory_analytics.php"><i class="dot"></i>Inventory Analytics</a><a href="inventory_export.php"><i class="dot"></i>Export / Print</a></nav></aside>
<main class="os-main"><section class="os-hero pp-hero"><div class="os-kicker">STEP 13F • INVENTORY INSIGHTS</div><h1>See stock health, movement velocity, expiry exposure and reorder needs.</h1><p>Valuation uses actual batch unit cost only. Suggested reorder quantity appears only when Target Stock has been explicitly configured.</p><div class="os-status-row"><span class="os-chip <?= $error===null?'good':'' ?>"><?= $error===null?'INVENTORY ANALYTICS LIVE':'Review required' ?></span><span class="os-chip"><?= number_format($metrics['moves30']) ?> movements / 30d</span><span class="os-chip"><?= number_format($metrics['low']) ?> low stock</span></div></section>
<?php if($error):?><div class="pp-alert bad"><strong>Analytics diagnostic:</strong> <?= an_h($error) ?></div><?php else:?>
<section class="s10-kpis" style="margin-top:14px"><div class="s10-kpi"><small>Known Stock Value</small><strong><?= an_m($metrics['value']) ?></strong><span>Actual batch costs only</span></div><div class="s10-kpi"><small>Sellable Stock</small><strong><?= an_h(an_n($metrics['sellable'])) ?></strong><span><?= an_h(an_n($metrics['expired'])) ?> expired units excluded</span></div><div class="s10-kpi"><small>30-Day Outflow</small><strong><?= an_h(an_n($metrics['sold30'])) ?></strong><span><?= an_h(an_n($metrics['in30'])) ?> units inward</span></div><div class="s10-kpi"><small>Suggested Reorder</small><strong><?= an_h(an_n($metrics['reorder_qty'])) ?></strong><span>Only configured targets</span></div></section>
<section class="pp-grid" style="margin-top:14px"><article class="os-card pp-span-7"><h2>30-Day Product Movement</h2><div class="pp-table-wrap"><table class="pp-table"><thead><tr><th>Stock</th><th>Product</th><th>Movements</th><th>In</th><th>Out</th></tr></thead><tbody><?php foreach($movement as $m):?><tr><td><b><?= an_h($m['sku']) ?></b></td><td><?= an_h($m['product_name']) ?></td><td><?= number_format((int)$m['movement_count']) ?></td><td><?= an_h(an_n($m['qty_in'])) ?></td><td><b><?= an_h(an_n($m['qty_out'])) ?></b></td></tr><?php endforeach;?><?php if(!$movement):?><tr><td colspan="5">No inventory movement in the last 30 days.</td></tr><?php endif;?></tbody></table></div></article><article class="os-card pp-span-5"><h2>Reorder Queue</h2><div class="s10-list"><?php $shown=0;foreach($rows as $r):if((float)$r['reorder_level']<=0||(float)$r['sellable_stock']>(float)$r['reorder_level']+0.0005)continue;$shown++;?><div class="s10-row"><div><b><?= an_h($r['sku'].' • '.$r['product_name']) ?></b><small>Current <?= an_h(an_n($r['sellable_stock'])) ?> • Reorder at <?= an_h(an_n($r['reorder_level'])) ?></small></div><strong><?= (float)$r['target_stock']>0?'Buy '.an_h(an_n($r['suggested_reorder'])):'Target not set' ?></strong></div><?php endforeach;?><?php if(!$shown):?><div class="s10-row"><div><b>No configured reorder alert is currently due.</b><small>Set real thresholds in Inventory Settings.</small></div></div><?php endif;?></div></article></section>
<section class="os-card" style="margin-top:14px"><h2>Stock Health by Product</h2><div class="pp-table-wrap"><table class="pp-table"><thead><tr><th>Stock</th><th>Product</th><th>Sellable</th><th>Expired</th><th>Known Value</th><th>Next Expiry</th><th>Suggested Reorder</th></tr></thead><tbody><?php foreach($rows as $r):?><tr><td><b><?= an_h($r['sku']?:'—') ?></b></td><td><?= an_h($r['product_name']) ?></td><td><?= an_h(an_n($r['sellable_stock'])) ?></td><td><?= an_h(an_n($r['expired_stock'])) ?></td><td><?= an_m($r['known_value']) ?></td><td><?= an_h($r['next_expiry']?:'—') ?></td><td><?= (float)$r['target_stock']>0?an_h(an_n($r['suggested_reorder'])):'—' ?></td></tr><?php endforeach;?></tbody></table></div></section>
<?php endif;?>
<div class="os-footer-note"><strong>Analytics policy:</strong> missing unit cost is shown as unvalued rather than estimated from MRP or selling price.</div></main></div></body></html>