<?php
declare(strict_types=1);
require_once __DIR__ . '/config/role_portal_auth.php';
$error=null;$success=null;$rows=[];$csrf='';$pending=0;
try{
    $pdo=role_portal_db();role_portal_ensure($pdo);security_step17_session_start();
    $actor=security_step17_session_user($pdo,true);
    if(!$actor){header('Location: ../login.php');exit;}
    if((int)($actor['must_change_password']??0)===1){header('Location: ../change_password.php?required=1');exit;}
    if((string)($actor['role_code']??'')!=='admin'){header('Location: ../'.role_portal_home($actor));exit;}
    $ctx=security_step17_context($pdo);$orgId=(int)$ctx['organization_id'];$csrf=security_step17_csrf();
    if($_SERVER['REQUEST_METHOD']==='POST'){
        security_step17_verify_csrf((string)($_POST['csrf']??''));$action=(string)($_POST['action']??'');$requestId=(int)($_POST['request_id']??0);
        if($action==='reset'){
            $p=(string)($_POST['temporary_password']??'');$c=(string)($_POST['confirm_password']??'');
            if(!hash_equals($p,$c))throw new RuntimeException('Temporary password confirmation does not match.');
            role_portal_handle_recovery($pdo,$requestId,'reset',$p);$success='Password recovery completed. Existing sessions were revoked and the user must change the temporary password at next sign-in.';
        }elseif($action==='dismiss'){
            role_portal_handle_recovery($pdo,$requestId,'dismiss');$success='Recovery request dismissed.';
        }
    }
    $rows=role_portal_recovery_rows($pdo,$orgId);$pending=role_portal_pending_recovery_count($pdo,$orgId);
}catch(Throwable $e){$error=$e->getMessage();}
function pr_status(string $v):string{return strtoupper(str_replace('_',' ',$v));}
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>Password Recovery - Healthcare Wellness Club</title><link rel="stylesheet" href="assets/dashboard.css"><link rel="stylesheet" href="assets/product_pro.css"><link rel="stylesheet" href="assets/step10.css"><style>.recovery-grid{display:grid;gap:12px}.recovery-card{border:1px solid #dbe7e1;border-radius:16px;padding:16px;background:linear-gradient(145deg,#fff,#f7fbff)}.recovery-card.pending{background:linear-gradient(145deg,#fff,#eef9f3)}.recovery-card.unmatched{background:linear-gradient(145deg,#fff,#fff8e8)}.recovery-head{display:flex;justify-content:space-between;gap:12px;align-items:flex-start}.recovery-meta{display:flex;gap:8px;flex-wrap:wrap;margin-top:8px}.recovery-actions{display:grid;grid-template-columns:1fr auto;gap:10px;align-items:end;margin-top:12px}.recovery-actions .pp-form{display:grid;grid-template-columns:1fr 1fr auto;gap:8px;align-items:end}.recovery-actions .dismiss{align-self:end}.muted{color:#6d7d75;font-size:.76rem}@media(max-width:900px){.recovery-actions,.recovery-actions .pp-form{grid-template-columns:1fr}}</style></head><body>
<header class="os-topbar"><div class="os-topbar-inner"><a class="os-brand" href="role_accounts.php"><img src="../img/logo.png" alt="logo"><span><strong>Healthcare Wellness Club</strong><small>Advanced Login • Password Recovery</small></span></a><div class="os-top-actions"><a class="os-btn" href="role_accounts.php">Role Accounts</a><a class="os-btn" href="security_sessions.php">Sessions</a><a class="os-btn primary" href="security_center.php">Security</a></div></div></header>
<div class="os-layout"><aside class="os-sidebar"><div class="os-nav-label">Role Login</div><nav class="os-nav"><a href="role_accounts.php"><i class="dot"></i>Role Accounts</a><a class="active" href="password_recovery.php"><i class="dot"></i>Password Recovery</a><a href="security_sessions.php"><i class="dot"></i>Sessions</a><a href="security_audit.php"><i class="dot"></i>Audit</a></nav><div class="os-sidebar-status"><b>Admin-assisted recovery</b><span>No reset link or password is emailed by this local system. Temporary passwords are created by an Administrator and force a change at next sign-in.</span></div></aside>
<main class="os-main"><section class="os-hero pp-hero"><div class="os-kicker">FORGOT PASSWORD • SECURE RECOVERY</div><h1>Review recovery requests without exposing account existence on the public login page.</h1><p>Matched requests can receive a temporary password. Resetting revokes existing sessions and forces the user to choose a new password at next sign-in.</p><div class="os-status-row"><span class="os-chip <?=$pending>0?'warn':'good'?>"><?=$pending?> open request(s)</span><span class="os-chip good">ADMIN ONLY</span><span class="os-chip">RATE LIMITED</span></div></section>
<?php if($error):?><div class="pp-alert bad"><strong>Password recovery:</strong> <?=security_step17_h($error)?></div><?php endif;?><?php if($success):?><div class="pp-alert good"><strong>Done:</strong> <?=security_step17_h($success)?></div><?php endif;?>
<section class="os-card" style="margin-top:14px"><div class="os-title-row"><div><h2>Recovery Queue</h2><p><?=count($rows)?> recent request(s). Unmatched requests never reveal the submitted email here; only the one-way identifier hash is retained by the engine.</p></div><a class="os-btn" href="../forgot_password.php" target="_blank">Open Forgot Password →</a></div><div class="recovery-grid">
<?php foreach($rows as $r):$status=(string)$r['status'];$matched=(int)($r['user_id']??0)>0;?><article class="recovery-card <?=security_step17_h($status)?>"><div class="recovery-head"><div><h3 style="margin:0"><?=$matched?security_step17_h((string)$r['full_name']):'Unmatched recovery request'?></h3><div class="muted"><?=$matched?security_step17_h((string)$r['email'].' • '.strtoupper((string)($r['role_code']??'unknown'))):'No matching active account • submitted identifier hidden'?></div></div><span class="pp-badge <?=$status==='pending'?'':($status==='unmatched'?'warn':'')?>"><?=security_step17_h(pr_status($status))?></span></div><div class="recovery-meta"><span class="pp-badge">Requested <?=security_step17_h((string)$r['requested_at'])?></span><?php if($r['handled_at']):?><span class="pp-badge">Handled <?=security_step17_h((string)$r['handled_at'])?></span><?php endif;?><?php if($r['handled_by_name']):?><span class="pp-badge">By <?=security_step17_h((string)$r['handled_by_name'])?></span><?php endif;?></div>
<?php if(in_array($status,['pending','unmatched'],true)):?><div class="recovery-actions"><?php if($matched):?><form method="post" class="pp-form" autocomplete="off"><input type="hidden" name="csrf" value="<?=security_step17_h($csrf)?>"><input type="hidden" name="action" value="reset"><input type="hidden" name="request_id" value="<?=(int)$r['id']?>"><label>Temporary Password<input type="password" name="temporary_password" required autocomplete="new-password"></label><label>Confirm<input type="password" name="confirm_password" required autocomplete="new-password"></label><button>Reset & Revoke Sessions</button></form><?php else:?><div class="pp-alert" style="margin:0">This request cannot reset any account because no active account matched. You can safely dismiss it.</div><?php endif;?><form method="post" class="dismiss"><input type="hidden" name="csrf" value="<?=security_step17_h($csrf)?>"><input type="hidden" name="action" value="dismiss"><input type="hidden" name="request_id" value="<?=(int)$r['id']?>"><button class="os-btn" type="submit">Dismiss</button></form></div><?php elseif($r['resolution_note']):?><p class="muted" style="margin:10px 0 0"><?=security_step17_h((string)$r['resolution_note'])?></p><?php endif;?></article><?php endforeach;?>
<?php if(!$rows):?><div class="pp-alert">No password recovery requests yet.</div><?php endif;?></div></section><div class="os-footer-note"><strong>Security rule:</strong> never send a permanent password. Give the temporary password only through a trusted channel; the account must change it at next sign-in.</div></main></div></body></html>
