<?php
declare(strict_types=1);
require_once __DIR__.'/config/database.php';
$error=null;$success=null;
try{
    $pdo=business_db();security_step17_ensure($pdo);$user=security_step17_current_user($pdo);$csrf=security_step17_csrf();
    if($_SERVER['REQUEST_METHOD']==='POST'){
        security_step17_verify_csrf((string)($_POST['csrf']??''));$new=(string)($_POST['new_password']??'');$confirm=(string)($_POST['confirm_password']??'');
        if(!hash_equals($new,$confirm))throw new RuntimeException('New password confirmation does not match.');
        security_step17_change_password($pdo,(int)$user['id'],(string)($_POST['current_password']??''),$new);$success='Password changed. Other active sessions were revoked.';$user=security_step17_current_user($pdo);
    }
}catch(Throwable $e){$error=$e->getMessage();$csrf=$csrf??'';}
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>Change Password - Healthcare Wellness Club</title><link rel="stylesheet" href="assets/dashboard.css"><link rel="stylesheet" href="assets/product_pro.css"></head><body><header class="os-topbar"><div class="os-topbar-inner"><a class="os-brand" href="index.php"><img src="../img/logo.png" alt="logo"><span><strong>Healthcare Wellness Club</strong><small>STEP 17 • Account Security</small></span></a><div class="os-top-actions"><a class="os-btn" href="index.php">Dashboard</a><a class="os-btn" href="logout.php">Sign Out</a></div></div></header><main class="os-main" style="max-width:760px;margin:24px auto"><section class="os-card"><div class="os-kicker">PASSWORD SECURITY</div><h1>Change your password</h1><p>Use a unique password. Changing it revokes your other active Business OS sessions.</p><?php if(isset($_GET['required'])):?><div class="pp-alert" style="background:#fff7e8;color:#765716"><strong>Required:</strong> your administrator issued a temporary password. Change it before continuing.</div><?php endif;?><?php if($error):?><div class="pp-alert bad"><strong>Unable to change:</strong> <?= security_step17_h($error) ?></div><?php endif;?><?php if($success):?><div class="pp-alert good"><strong>Done:</strong> <?= security_step17_h($success) ?> <a href="index.php">Continue to Dashboard →</a></div><?php endif;?><form method="post" class="pp-form" autocomplete="off"><input type="hidden" name="csrf" value="<?= security_step17_h($csrf??'') ?>"><label>Current Password<input type="password" name="current_password" required autocomplete="current-password"></label><label>New Password<input type="password" name="new_password" required autocomplete="new-password"></label><label>Confirm New Password<input type="password" name="confirm_password" required autocomplete="new-password"></label><div class="pp-alert"><strong>Policy:</strong> minimum 12 characters including uppercase, lowercase, number and special character. Recent passwords cannot be reused.</div><button>Change Password Securely</button></form></section></main><script src="assets/business-collapsible.js?v=20260820-1" defer></script></body></html>
