<?php
declare(strict_types=1);
session_start();
require_once __DIR__ . '/config/product_step12.php';
if (empty($_SESSION['product_sales_csrf'])) $_SESSION['product_sales_csrf']=bin2hex(random_bytes(24));
$csrf=(string)$_SESSION['product_sales_csrf'];
$error=null;$success=null;$quotes=[];$members=[];$selected=null;$ctx=[];
$quoteId=(int)($_GET['quote']??$_POST['quote_id']??0);
try{
    $pdo=business_db();product_step12_ensure($pdo);$ctx=product_step12_context($pdo);$orgId=(int)$ctx['organization_id'];
    if($_SERVER['REQUEST_METHOD']==='POST'){
        if(!hash_equals($csrf,(string)($_POST['csrf']??'')))throw new RuntimeException('Security token mismatch.');
        $memberRaw=trim((string)($_POST['member_id']??''));$memberId=$memberRaw===''?null:(int)$memberRaw;
        if($memberRaw!==''&&$memberId<=0)throw new RuntimeException('Choose a valid member or leave member link empty.');
        $orderDate=(string)($_POST['order_date']??date('Y-m-d'));
        $orderId=product_step12_finalize_quote($pdo,$quoteId,$memberId,$orderDate);
        header('Location: product_sales_center.php?quote='.$quoteId.'&order='.$orderId.'&saved=1');exit;
    }
    $stmt=$pdo->prepare("SELECT q.id,q.quote_code,q.customer_name,q.customer_type,q.pricing_tier_code,q.grand_total,q.total_vp,q.status,q.created_at,l.order_id,m.full_name member_name
        FROM product_quotes q
        LEFT JOIN product_quote_order_links l ON l.organization_id=q.organization_id AND l.quote_id=q.id
        LEFT JOIN orders o ON o.id=l.order_id AND o.organization_id=q.organization_id
        LEFT JOIN members m ON m.id=o.member_id AND m.organization_id=o.organization_id
        WHERE q.organization_id=? ORDER BY q.id DESC LIMIT 100");
    $stmt->execute([$orgId]);$quotes=$stmt->fetchAll();$members=product_step12_members($pdo,$orgId);
    if($quoteId>0)$selected=product_step12_quote($pdo,$orgId,$quoteId);
    if(isset($_GET['saved']))$success='Product quote finalized into Business OS Order #'.(int)($_GET['order']??0).'.';
}catch(Throwable $e){$error=$e->getMessage();}
function ps_money(mixed $v):string{return '₹'.number_format((float)$v,2,'.',',');}
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>Product Sales Integration - Healthcare Wellness Club</title><link rel="stylesheet" href="assets/dashboard.css"><link rel="stylesheet" href="assets/product_pro.css"></head><body>
<header class="os-topbar"><div class="os-topbar-inner"><a class="os-brand" href="index.php"><img src="../img/logo.png" alt="Healthcare Wellness Club logo"><span><strong>Healthcare Wellness Club</strong><small>STEP 12A • Product Sales → Business OS</small></span></a><div class="os-top-actions"><a class="os-btn" href="product_quotes.php">Saved Quotes</a><a class="os-btn" href="operations_center.php">Operations</a><a class="os-btn primary" href="product_order_builder.php">Order Builder</a></div></div></header>
<div class="os-layout"><aside class="os-sidebar"><div class="os-nav-label">Product Integration</div><nav class="os-nav"><a href="product_catalog.php"><i class="dot"></i>Product Catalog</a><a href="product_order_builder.php"><i class="dot"></i>Order Builder</a><a href="product_quotes.php"><i class="dot"></i>Saved Quotes</a><a class="active" href="product_sales_center.php"><i class="dot"></i>Finalize Sale</a><a href="operations_center.php"><i class="dot"></i>Business Operations</a></nav><div class="os-sidebar-status"><b>Identity-safe finalization</b><span>Member linkage is explicit only. Customer names are never auto-matched.</span></div></aside>
<main class="os-main"><section class="os-hero pp-hero"><div class="os-kicker">STEP 12A • Product Order → Business OS</div><h1>Turn a saved Product & Price Pro quote into a traceable Business OS order.</h1><p>Finalization preserves the quote and product line snapshots, writes a new Product Sales raw-source record, creates the normalized order and maps exact VP/payable totals. Profit stays zero until a real cost basis is defined.</p><div class="os-status-row"><span class="os-chip <?= $error===null?'good':'' ?>"><?= $error===null?'PRODUCT SALES INTEGRATION LIVE':'Review required' ?></span><span class="os-chip good">No legacy rewrite</span><span class="os-chip">Explicit member link</span><span class="os-chip">Profit: deferred</span></div></section>
<?php if($error):?><div class="pp-alert bad"><strong>Integration diagnostic:</strong> <?= product_h($error) ?></div><?php endif;?><?php if($success):?><div class="pp-alert good"><strong>Saved:</strong> <?= product_h($success) ?> <a href="product_sale_detail.php?order=<?= (int)($_GET['order']??0) ?>">Open sale detail →</a></div><?php endif;?>
<?php if(!$error):?><section class="pp-grid" style="margin-top:14px"><article class="os-card pp-span-7"><div class="os-title-row"><div><h2>Saved Quotes</h2><p>Select a quote to review before finalizing it into Business OS.</p></div><a class="os-btn" href="product_order_builder.php">+ New Quote</a></div><div class="pp-table-wrap"><table class="pp-table"><thead><tr><th>Quote</th><th>Customer</th><th>Tier</th><th>Total</th><th>VP</th><th>Status</th><th></th></tr></thead><tbody><?php foreach($quotes as $q):?><tr><td><b><?= product_h($q['quote_code']) ?></b><small><?= product_h(substr((string)$q['created_at'],0,16)) ?></small></td><td><?= product_h($q['customer_name']?:'—') ?><?= $q['member_name']?'<small>Linked: '.product_h($q['member_name']).'</small>':'' ?></td><td><?= product_h($q['pricing_tier_code']) ?></td><td><?= ps_money($q['grand_total']) ?></td><td><?= product_h(rtrim(rtrim(number_format((float)$q['total_vp'],3,'.',''),'0'),'.')) ?></td><td><span class="pp-badge <?= $q['order_id']?'':'warn' ?>"><?= $q['order_id']?'ORDER #'.(int)$q['order_id']:strtoupper((string)$q['status']) ?></span></td><td><a href="?quote=<?= (int)$q['id'] ?>">Review →</a></td></tr><?php endforeach;?><?php if(!$quotes):?><tr><td colspan="7">No saved product quotes yet.</td></tr><?php endif;?></tbody></table></div></article>
<aside class="os-card pp-span-5"><?php if(!$selected):?><h2>Choose a Quote</h2><p>Select a saved quote from the table. Nothing is written until you explicitly finalize it.</p><?php else:?><div class="os-title-row"><div><h2><?= product_h($selected['quote_code']) ?></h2><p><?= product_h($selected['customer_name']?:'No customer name') ?> • <?= product_h($selected['pricing_tier_code']) ?></p></div><span class="pp-badge"><?= count($selected['items']) ?> ITEMS</span></div><div class="pp-source"><b>MRP subtotal</b><span><?= ps_money($selected['subtotal_mrp']) ?></span></div><div class="pp-source"><b>Product payable</b><span><?= ps_money($selected['payable_amount']) ?></span></div><div class="pp-source"><b>Saving</b><span><?= ps_money($selected['saving_amount']) ?></span></div><div class="pp-source"><b>Delivery</b><span><?= ps_money($selected['delivery_charge']) ?></span></div><div class="pp-source"><b>Grand total</b><span><?= ps_money($selected['grand_total']) ?></span></div><div class="pp-source"><b>Total VP</b><span><?= product_h(rtrim(rtrim(number_format((float)$selected['total_vp'],3,'.',''),'0'),'.')) ?></span></div>
<?php if((int)($selected['order_id']??0)>0):?><div class="pp-alert good" style="margin-top:12px"><strong>Already finalized.</strong> Business OS Order #<?= (int)$selected['order_id'] ?>. <a href="product_sale_detail.php?order=<?= (int)$selected['order_id'] ?>">Open detail →</a></div><?php else:?><form method="post" class="pp-form" style="margin-top:14px"><input type="hidden" name="csrf" value="<?= product_h($csrf) ?>"><input type="hidden" name="quote_id" value="<?= (int)$selected['id'] ?>"><label>Business Order Date<input type="date" name="order_date" value="<?= product_h(date('Y-m-d')) ?>" required></label><label>Link verified Member (optional)<select name="member_id"><option value="">No member link — preserve customer snapshot only</option><?php foreach($members as $m):?><option value="<?= (int)$m['id'] ?>"><?= product_h($m['full_name'].' • #'.$m['id'].($m['mobile']?' • '.$m['mobile']:'')) ?></option><?php endforeach;?></select></label><div class="pp-alert" style="background:#fff7ea;color:#805a20"><strong>Important:</strong> member identity is never guessed from the quote customer name. Select a member only when you know it is the same person.</div><button type="submit">Finalize into Business OS →</button></form><?php endif;?><?php endif;?></aside></section><div class="os-footer-note"><strong>Accounting policy:</strong> Business Order gross = MRP subtotal + delivery; discount = quoted saving; net = quote grand total; VP = quote total VP. Profit/Income is deliberately not auto-created until a real cost/profit rule is defined.</div><?php endif;?></main></div></body></html>