<?php
declare(strict_types=1);
session_start();
require_once __DIR__ . '/config/product_step11.php';
if(empty($_SESSION['product_seed_csrf'])) $_SESSION['product_seed_csrf']=bin2hex(random_bytes(24));
$csrf=(string)$_SESSION['product_seed_csrf'];$error=null;$success=null;$metrics=[];$data=[];
try{
 $pdo=business_db();product_step11_ensure($pdo);$ctx=product_org_context($pdo);$data=product_step11_seed_data();
 if($_SERVER['REQUEST_METHOD']==='POST'){
  if(!hash_equals($csrf,(string)($_POST['csrf']??''))) throw new RuntimeException('Security token mismatch. Refresh and try again.');
  if(($_POST['confirm']??'')!=='yes') throw new RuntimeException('Confirm the reviewed PDF source before seeding.');
  $result=product_step11_apply_seed($pdo);$success=$result['products'].' products/listings were seeded from the reviewed April 2026 PDFs.';
 }
 $metrics=product_foundation_metrics($pdo,(int)$ctx['organization_id']);
}catch(Throwable $e){$error=$e->getMessage();}
?>
<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>Product PDF Seed - Healthcare Wellness Club</title><link rel="stylesheet" href="assets/dashboard.css"><link rel="stylesheet" href="assets/product_pro.css"></head><body>
<header class="os-topbar"><div class="os-topbar-inner"><a class="os-brand" href="product_catalog.php"><img src="../img/logo.png" alt="logo"><span><strong>Healthcare Wellness Club</strong><small>Product & Price Pro • PDF Source Seed</small></span></a><div class="os-top-actions"><a class="os-btn" href="product_catalog.php">Catalog</a><a class="os-btn" href="product_import_center.php">Import Center</a><a class="os-btn primary" href="index.php">Dashboard</a></div></div></header>
<div class="os-layout"><aside class="os-sidebar"><div class="os-nav-label">Product System</div><nav class="os-nav"><a href="product_catalog.php"><i class="dot"></i>Catalog</a><a class="active" href="product_seed.php"><i class="dot"></i>PDF Seed</a><a href="product_data_center.php"><i class="dot"></i>Data Center</a><a href="product_images.php"><i class="dot"></i>Images</a><a href="product_price_history.php"><i class="dot"></i>Price History</a><a href="product_order_builder.php"><i class="dot"></i>Order Builder</a><a href="product_audit.php"><i class="dot"></i>STEP 11 Audit</a></nav><div class="os-sidebar-status"><b>Source-first pricing</b><span>MRP/VP/tier prices come from the reviewed user-supplied PDFs. No price is calculated from a discount percentage.</span></div></aside><main class="os-main">
<section class="os-hero pp-hero"><div class="os-kicker">STEP 11 • Authoritative PDF Seed</div><h1>Seed the India catalog from the two reviewed 15 April 2026 price lists.</h1><p>The operation is idempotent: products are keyed by Stock No., price versions by effective date, and exact tier prices are updated without inventing missing values.</p><div class="os-status-row"><span class="os-chip <?= $error===null?'good':'' ?>"><?= $error===null?'PDF SEED READY':'Review required' ?></span><span class="os-chip good"><?= number_format(count($data['products']??[])) ?> source products/items</span><span class="os-chip">Effective <?= product_h($data['effective_date']??'—') ?></span><span class="os-chip"><?= number_format($metrics['products']??0) ?> currently seeded</span></div></section>
<?php if($success):?><div class="pp-alert good"><strong>Seed complete:</strong> <?= product_h($success) ?></div><?php endif;?><?php if($error):?><div class="pp-alert bad"><strong>Seed diagnostic:</strong> <?= product_h($error) ?></div><?php endif;?>
<?php if(!$error):?><section class="pp-grid"><article class="os-card pp-span-7"><h2>Reviewed Sources</h2><div class="pp-source"><b>Associate Price List - India</b><span>SHA-256: <?= product_h($data['associate_pdf_sha256']) ?></span><small>VP, MRP, Retail, Earn Base, 25%, 35%, 42%, 50%, plus Applications / Art of Promotion.</small></div><div class="pp-source"><b>Preferred Customers Price List</b><span>SHA-256: <?= product_h($data['preferred_pdf_sha256']) ?></span><small>MRP, Bronze, Silver and Gold exact listed prices.</small></div></article><aside class="os-card pp-span-5"><h2>Apply Seed</h2><p>Safe to run again after a pull. Existing April 2026 rows are updated in place; another effective date will create a new price version.</p><form method="post" class="pp-form"><input type="hidden" name="csrf" value="<?= product_h($csrf) ?>"><label class="pp-check"><input type="checkbox" name="confirm" value="yes" required><span>I confirm these are the reviewed 15 April 2026 PDFs.</span></label><button type="submit">Seed / Reconcile Catalog →</button></form></aside></section><?php endif;?>
<div class="os-footer-note"><strong>Important:</strong> the seed stores source-listed values exactly. It does not infer Bronze/Silver/Gold or Associate prices from MRP percentages.</div></main></div></body></html>