<?php
declare(strict_types=1);
session_start();require_once __DIR__ . '/config/product_step12.php';
if(empty($_SESSION['product_payment_csrf']))$_SESSION['product_payment_csrf']=bin2hex(random_bytes(24));$csrf=(string)$_SESSION['product_payment_csrf'];
$error=null;$success=null;$sales=[];$payments=[];$selectedOrder=(int)($_GET['order']??$_POST['order_id']??0);
try{
 $pdo=business_db();product_step12_ensure($pdo);$ctx=product_step12_context($pdo);$orgId=(int)$ctx['organization_id'];
 if($_SERVER['REQUEST_METHOD']==='POST'){
  if(!hash_equals($csrf,(string)($_POST['csrf']??'')))throw new RuntimeException('Security token mismatch.');$action=(string)($_POST['action']??'add');
  if($action==='add'){$amount=(float)($_POST['amount']??0);$date=(string)($_POST['payment_date']??date('Y-m-d'));$method=(string)($_POST['payment_method']??'other');$reference=trim((string)($_POST['reference_no']??''));$notes=trim((string)($_POST['notes']??''));$id=product_step12_add_payment($pdo,$selectedOrder,$date,$amount,$method,$reference,$notes);$success='Payment #'.$id.' recorded.';}
  elseif($action==='reverse'){$pid=(int)($_POST['payment_id']??0);product_step12_reverse_payment($pdo,$pid,trim((string)($_POST['reason']??'')));$success='Payment #'.$pid.' reversed with audit history preserved.';}
 }
 $sales=product_step12_sales_rows($pdo,$orgId,'active');foreach($sales as &$s){$s['payment_state']=product_step12_sync_payment_status($pdo,(int)$s['order_id']);}unset($s);
 $stmt=$pdo->prepare("SELECT p.*,q.quote_code,q.customer_name,m.full_name member_name FROM product_sale_payments p JOIN product_sale_ledger l ON l.id=p.sale_ledger_id AND l.organization_id=p.organization_id JOIN orders o ON o.id=p.order_id AND o.organization_id=p.organization_id LEFT JOIN product_quotes q ON q.id=l.quote_id AND q.organization_id=l.organization_id LEFT JOIN members m ON m.id=o.member_id AND m.organization_id=o.organization_id WHERE p.organization_id=? ORDER BY p.payment_date DESC,p.id DESC LIMIT 200");$stmt->execute([$orgId]);$payments=$stmt->fetchAll();
}catch(Throwable $e){$error=$e->getMessage();}
function ppay_money(mixed $v):string{return '₹'.number_format((float)$v,2,'.',',');}
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>Product Sale Payments - Healthcare Wellness Club</title><link rel="stylesheet" href="assets/dashboard.css"><link rel="stylesheet" href="assets/product_pro.css"></head><body>
<header class="os-topbar"><div class="os-topbar-inner"><a class="os-brand" href="index.php"><img src="../img/logo.png" alt="logo"><span><strong>Healthcare Wellness Club</strong><small>STEP 12 • Product Sale Payments</small></span></a><div class="os-top-actions"><a class="os-btn" href="product_sales_center.php">Sales</a><a class="os-btn" href="product_cost_center.php">Cost Basis</a><a class="os-btn primary" href="product_sales_analytics.php">Analytics</a></div></div></header>
<div class="os-layout"><aside class="os-sidebar"><div class="os-nav-label">STEP 12</div><nav class="os-nav"><a href="product_sales_center.php"><i class="dot"></i>Sales Center</a><a href="product_cost_center.php"><i class="dot"></i>Cost Basis</a><a class="active" href="product_payments.php"><i class="dot"></i>Payments</a><a href="product_sales_analytics.php"><i class="dot"></i>Sales Analytics</a><a href="step12_audit.php"><i class="dot"></i>STEP 12 Audit</a></nav><div class="os-sidebar-status"><b>Collection tracking only</b><span>Payments do not create duplicate Income entries automatically.</span></div></aside>
<main class="os-main"><section class="os-hero pp-hero"><div class="os-kicker">STEP 12D • PAYMENT COLLECTION</div><h1>Track actual money received against finalized product sales.</h1><p>Payments are separate from order revenue, so recording a payment never double-counts income. Reversal changes payment status but preserves the original evidence.</p><div class="os-status-row"><span class="os-chip <?= $error===null?'good':'' ?>"><?= $error===null?'PAYMENTS CENTER LIVE':'Review required' ?></span><span class="os-chip"><?= count($sales) ?> active sales</span><span class="os-chip"><?= count($payments) ?> payment records</span></div></section>
<?php if($error):?><div class="pp-alert bad"><strong>Payment diagnostic:</strong> <?= product_h($error) ?></div><?php endif;?><?php if($success):?><div class="pp-alert good"><strong>Saved:</strong> <?= product_h($success) ?></div><?php endif;?>
<?php if(!$error):?><section class="pp-grid" style="margin-top:14px"><article class="os-card pp-span-5"><h2>Add Payment</h2><form method="post" class="pp-form"><input type="hidden" name="csrf" value="<?= product_h($csrf) ?>"><input type="hidden" name="action" value="add"><label>Active Product Sale<select name="order_id" required><option value="">Choose sale…</option><?php foreach($sales as $s):$st=$s['payment_state'];?><option value="<?= (int)$s['order_id'] ?>" <?= (int)$s['order_id']===$selectedOrder?'selected':'' ?>>Order #<?= (int)$s['order_id'] ?> • <?= product_h($s['quote_code']?:'Product Sale') ?> • <?= product_h($s['member_name']?:$s['customer_name']?:'Customer') ?> • Due <?= ppay_money($st['outstanding']) ?></option><?php endforeach;?></select></label><label>Payment Date<input type="date" name="payment_date" value="<?= product_h(date('Y-m-d')) ?>" required></label><label>Amount<input type="number" name="amount" min="0.01" step="0.01" required></label><label>Method<select name="payment_method"><option value="cash">Cash</option><option value="upi">UPI</option><option value="bank">Bank Transfer</option><option value="card">Card</option><option value="other">Other</option></select></label><label>Reference No.<input name="reference_no" maxlength="120" placeholder="Optional transaction/reference"></label><label>Notes<textarea name="notes" rows="2"></textarea></label><button>Record Payment →</button></form></article>
<article class="os-card pp-span-7"><h2>Collection Status</h2><div class="pp-table-wrap"><table class="pp-table"><thead><tr><th>Order</th><th>Customer</th><th>Sale Total</th><th>Paid</th><th>Outstanding</th><th>Status</th></tr></thead><tbody><?php foreach($sales as $s):$st=$s['payment_state'];?><tr><td><a href="product_sale_detail.php?order=<?= (int)$s['order_id'] ?>"><b>#<?= (int)$s['order_id'] ?></b></a><small><?= product_h($s['quote_code']?:'') ?></small></td><td><?= product_h($s['member_name']?:$s['customer_name']?:'—') ?></td><td><?= ppay_money($st['due']) ?></td><td><?= ppay_money($st['paid']) ?></td><td><?= ppay_money($st['outstanding']) ?></td><td><span class="pp-badge"><?= product_h(strtoupper($st['status'])) ?></span></td></tr><?php endforeach;?><?php if(!$sales):?><tr><td colspan="6">No active finalized product sales yet.</td></tr><?php endif;?></tbody></table></div></article></section>
<section class="os-card" style="margin-top:14px"><div class="os-title-row"><div><h2>Payment History</h2><p>Reversed payments remain visible; no hard delete.</p></div></div><div class="pp-table-wrap"><table class="pp-table"><thead><tr><th>Date</th><th>Payment</th><th>Order</th><th>Customer</th><th>Amount</th><th>Method</th><th>Status</th><th>Action</th></tr></thead><tbody><?php foreach($payments as $p):?><tr><td><?= product_h($p['payment_date']) ?></td><td>#<?= (int)$p['id'] ?></td><td><a href="product_sale_detail.php?order=<?= (int)$p['order_id'] ?>">#<?= (int)$p['order_id'] ?></a></td><td><?= product_h($p['member_name']?:$p['customer_name']?:'—') ?></td><td><?= ppay_money($p['amount']) ?></td><td><?= product_h(strtoupper($p['payment_method'])) ?><?= $p['reference_no']?'<small>'.product_h($p['reference_no']).'</small>':'' ?></td><td><span class="pp-badge <?= $p['status']==='active'?'':'warn' ?>"><?= product_h(strtoupper($p['status'])) ?></span></td><td><?php if($p['status']==='active'):?><details><summary>Reverse</summary><form method="post" class="pp-form"><input type="hidden" name="csrf" value="<?= product_h($csrf) ?>"><input type="hidden" name="action" value="reverse"><input type="hidden" name="payment_id" value="<?= (int)$p['id'] ?>"><input name="reason" minlength="5" placeholder="Reason" required><button>Confirm</button></form></details><?php else:?>—<?php endif;?></td></tr><?php endforeach;?><?php if(!$payments):?><tr><td colspan="8">No payment records yet.</td></tr><?php endif;?></tbody></table></div></section><?php endif;?>
<div class="os-footer-note"><strong>Payment rule:</strong> active payments cannot exceed the sale outstanding amount. Payment reversal is audited and recalculates Unpaid/Partial/Paid status.</div></main></div><script src="assets/business-collapsible.js?v=20260820-1" defer></script></body></html>
