<?php
declare(strict_types=1);
session_start();
require_once __DIR__ . '/config/product_step12.php';
if(empty($_SESSION['product_cost_csrf']))$_SESSION['product_cost_csrf']=bin2hex(random_bytes(24));
$csrf=(string)$_SESSION['product_cost_csrf'];$error=null;$success=null;$rows=[];$costs=[];$q=trim((string)($_GET['q']??''));
try{
    $pdo=business_db();product_step12_ensure($pdo);$ctx=product_step12_context($pdo);$orgId=(int)$ctx['organization_id'];
    if($_SERVER['REQUEST_METHOD']==='POST'){
        if(!hash_equals($csrf,(string)($_POST['csrf']??'')))throw new RuntimeException('Security token mismatch.');
        $productId=(int)($_POST['product_id']??0);$date=trim((string)($_POST['effective_from']??''));$cost=(float)($_POST['unit_cost']??0);$source=trim((string)($_POST['source_reference']??''));$notes=trim((string)($_POST['notes']??''));
        $costId=product_step12_add_cost($pdo,$productId,$date,$cost,$source,$notes);$success='Explicit cost version #'.$costId.' saved and affected active sales recalculated.';
    }
    $rows=product_step11_catalog_rows($pdo,$orgId,$q,'ALL');
    $stmt=$pdo->prepare("SELECT cv.*,p.product_name,p.sku FROM product_cost_versions cv JOIN products p ON p.id=cv.product_id AND p.organization_id=cv.organization_id WHERE cv.organization_id=? AND cv.status='active' ORDER BY cv.effective_from DESC,cv.id DESC LIMIT 150");$stmt->execute([$orgId]);$costs=$stmt->fetchAll();
}catch(Throwable $e){$error=$e->getMessage();}
function pcc_money(mixed $v):string{return '₹'.number_format((float)$v,2,'.',',');}
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>Product Cost Basis - Healthcare Wellness Club</title><link rel="stylesheet" href="assets/dashboard.css"><link rel="stylesheet" href="assets/product_pro.css"></head><body>
<header class="os-topbar"><div class="os-topbar-inner"><a class="os-brand" href="index.php"><img src="../img/logo.png" alt="logo"><span><strong>Healthcare Wellness Club</strong><small>STEP 12 • Explicit Cost & Profit Basis</small></span></a><div class="os-top-actions"><a class="os-btn" href="product_sales_center.php">Sales</a><a class="os-btn" href="product_sales_analytics.php">Analytics</a><a class="os-btn primary" href="index.php">Dashboard</a></div></div></header>
<div class="os-layout"><aside class="os-sidebar"><div class="os-nav-label">STEP 12</div><nav class="os-nav"><a href="product_sales_center.php"><i class="dot"></i>Sales Center</a><a class="active" href="product_cost_center.php"><i class="dot"></i>Cost Basis</a><a href="product_payments.php"><i class="dot"></i>Payments</a><a href="product_sales_analytics.php"><i class="dot"></i>Sales Analytics</a><a href="step12_audit.php"><i class="dot"></i>STEP 12 Audit</a></nav><div class="os-sidebar-status"><b>Explicit cost only</b><span>MRP, Earn Base, discount tier and VP are never treated as cost automatically.</span></div></aside>
<main class="os-main"><section class="os-hero pp-hero"><div class="os-kicker">STEP 12C • REAL COST BASIS</div><h1>Profit appears only when every sold product has an explicit dated cost.</h1><p>Enter cost from a real purchase bill, invoice or approved cost sheet. Each cost is versioned by effective date, so past sales keep the cost that was valid on their sale date.</p><div class="os-status-row"><span class="os-chip <?= $error===null?'good':'' ?>"><?= $error===null?'COST BASIS CENTER LIVE':'Review required' ?></span><span class="os-chip">No inferred cost</span><span class="os-chip">Versioned by date</span><span class="os-chip"><?= count($costs) ?> cost versions</span></div></section>
<?php if($error):?><div class="pp-alert bad"><strong>Cost diagnostic:</strong> <?= product_h($error) ?></div><?php endif;?><?php if($success):?><div class="pp-alert good"><strong>Saved:</strong> <?= product_h($success) ?></div><?php endif;?>
<?php if(!$error):?><section class="pp-grid" style="margin-top:14px"><article class="os-card pp-span-5"><h2>Add / Update Explicit Cost</h2><p>Select the exact product and effective date. Reusing the same product/date updates that version rather than creating a duplicate.</p><form method="post" class="pp-form"><input type="hidden" name="csrf" value="<?= product_h($csrf) ?>"><label>Product<select name="product_id" required><option value="">Choose product…</option><?php foreach($rows as $r):?><option value="<?= (int)$r['id'] ?>"><?= product_h($r['sku'].' • '.$r['product_name'].' • MRP ₹'.number_format((float)$r['mrp'],2)) ?></option><?php endforeach;?></select></label><label>Effective From<input type="date" name="effective_from" value="<?= product_h(date('Y-m-d')) ?>" required></label><label>Actual Unit Cost (INR)<input type="number" name="unit_cost" min="0" step="0.01" required></label><label>Cost Source / Reference<input name="source_reference" maxlength="700" placeholder="Purchase invoice no., bill, approved cost sheet…" required></label><label>Notes<textarea name="notes" rows="3" placeholder="Optional context"></textarea></label><button>Save Explicit Cost →</button></form><div class="pp-alert" style="margin-top:12px;background:#fff7ea;color:#805a20"><strong>Rule:</strong> no cost source = no profit. The system will keep Profit Deferred rather than guess.</div></article>
<article class="os-card pp-span-7"><div class="os-title-row"><div><h2>Cost Version History</h2><p>Latest explicit cost entries. These values drive product-sale profit only for matching effective dates.</p></div><form method="get"><input name="q" value="<?= product_h($q) ?>" placeholder="Filter product…"></form></div><div class="pp-table-wrap"><table class="pp-table"><thead><tr><th>Effective</th><th>Stock</th><th>Product</th><th>Unit Cost</th><th>Basis</th><th>Source</th></tr></thead><tbody><?php foreach($costs as $c):if($q!==''&&!str_contains(strtolower($c['product_name'].' '.$c['sku']),strtolower($q)))continue;?><tr><td><?= product_h($c['effective_from']) ?></td><td><b><?= product_h($c['sku']) ?></b></td><td><?= product_h($c['product_name']) ?></td><td><b><?= pcc_money($c['unit_cost']) ?></b></td><td><?= product_h($c['basis_code']) ?></td><td><?= product_h($c['source_reference']) ?></td></tr><?php endforeach;?><?php if(!$costs):?><tr><td colspan="6">No explicit cost versions yet. Product sales will correctly remain Profit Deferred.</td></tr><?php endif;?></tbody></table></div></article></section><?php endif;?>
<div class="os-footer-note"><strong>Profit formula when fully covered:</strong> line profit = exact sold line price − explicit unit cost × quantity. Delivery is excluded from product profit unless a future explicit delivery-cost rule is added.</div></main></div><script src="assets/business-collapsible.js?v=20260820-1" defer></script></body></html>
