<?php
declare(strict_types=1);
session_start();
require_once __DIR__ . '/config/sales_step15.php';
if(empty($_SESSION['product_sales_csrf']))$_SESSION['product_sales_csrf']=bin2hex(random_bytes(24));
$csrf=(string)$_SESSION['product_sales_csrf'];$error=null;$success=null;$quotes=[];$members=[];$selected=null;$sales=[];$ctx=[];
$quoteId=(int)($_GET['quote']??$_POST['quote_id']??0);
try{
    $pdo=business_db();product_step12_ensure($pdo);product_step12_bridge_backfill($pdo);$ctx=product_step12_context($pdo);$orgId=(int)$ctx['organization_id'];
    if($_SERVER['REQUEST_METHOD']==='POST'){
        if(!hash_equals($csrf,(string)($_POST['csrf']??'')))throw new RuntimeException('Security token mismatch.');$action=(string)($_POST['action']??'finalize');
        if($action==='finalize'){$memberRaw=trim((string)($_POST['member_id']??''));$memberId=$memberRaw===''?null:(int)$memberRaw;if($memberRaw!==''&&$memberId<=0)throw new RuntimeException('Choose a valid member or leave member link empty.');$orderDate=(string)($_POST['order_date']??date('Y-m-d'));$orderId=sales_step15_finalize_quote($pdo,$quoteId,$memberId,$orderDate);header('Location: product_sales_center.php?quote='.$quoteId.'&order='.$orderId.'&saved=1');exit;}
        if($action==='cancel'){$orderId=(int)($_POST['order_id']??0);sales_step15_cancel_sale($pdo,$orderId,trim((string)($_POST['reason']??'')));$success='Product Sale Order #'.$orderId.' cancelled safely; active business effect removed and evidence preserved.';}
        if($action==='restore'){$orderId=(int)($_POST['order_id']??0);sales_step15_restore_sale($pdo,$orderId,trim((string)($_POST['reason']??'')));$success='Product Sale Order #'.$orderId.' restored with exact quote totals and report VP effect.';}
    }
    product_step12_bridge_backfill($pdo);
    $stmt=$pdo->prepare("SELECT q.id,q.quote_code,q.customer_name,q.customer_type,q.pricing_tier_code,q.grand_total,q.total_vp,q.status,q.created_at,l.order_id,m.full_name member_name,sl.sale_status,sl.payment_status,sl.cost_status,sl.profit_total FROM product_quotes q LEFT JOIN product_quote_order_links l ON l.organization_id=q.organization_id AND l.quote_id=q.id LEFT JOIN orders o ON o.id=l.order_id AND o.organization_id=q.organization_id LEFT JOIN members m ON m.id=o.member_id AND m.organization_id=o.organization_id LEFT JOIN product_sale_ledger sl ON sl.organization_id=q.organization_id AND sl.order_id=o.id WHERE q.organization_id=? ORDER BY q.id DESC LIMIT 120");$stmt->execute([$orgId]);$quotes=$stmt->fetchAll();$members=product_step12_members($pdo,$orgId);$sales=product_step12_sales_rows($pdo,$orgId,'all');if($quoteId>0)$selected=product_step12_quote($pdo,$orgId,$quoteId);if(isset($_GET['saved']))$success='Product quote finalized into Business OS Order #'.(int)($_GET['order']??0).'.';
}catch(Throwable $e){$error=$e->getMessage();}
function ps_money(mixed $v):string{return '₹'.number_format((float)$v,2,'.',',');}function ps_num(mixed $v):string{$x=number_format((float)$v,3,'.','');return rtrim(rtrim($x,'0'),'.');}
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>Product Sales Integration - Healthcare Wellness Club</title><link rel="stylesheet" href="assets/dashboard.css"><link rel="stylesheet" href="assets/product_pro.css"></head><body>
<header class="os-topbar"><div class="os-topbar-inner"><a class="os-brand" href="index.php"><img src="../img/logo.png" alt="Healthcare Wellness Club logo"><span><strong>Healthcare Wellness Club</strong><small>STEP 12 + 15 • Product Sales → Customer Fulfillment</small></span></a><div class="os-top-actions"><a class="os-btn" href="product_cost_center.php">Cost Basis</a><a class="os-btn" href="product_payments.php">Payments</a><a class="os-btn" href="product_sales_analytics.php">Analytics</a><a class="os-btn" href="sales_fulfillment.php">Fulfillment</a><a class="os-btn primary" href="product_order_builder.php">+ Order Builder</a></div></div></header>
<div class="os-layout"><aside class="os-sidebar"><div class="os-nav-label">STEP 12</div><nav class="os-nav"><a href="product_catalog.php"><i class="dot"></i>Product Catalog</a><a href="product_order_builder.php"><i class="dot"></i>Order Builder</a><a href="product_quotes.php"><i class="dot"></i>Saved Quotes</a><a class="active" href="product_sales_center.php"><i class="dot"></i>Sales Center</a><a href="product_cost_center.php"><i class="dot"></i>Cost Basis</a><a href="product_payments.php"><i class="dot"></i>Payments</a><a href="product_sales_analytics.php"><i class="dot"></i>Sales Analytics</a><a href="step12_audit.php"><i class="dot"></i>STEP 12 Audit</a></nav><div class="os-sidebar-status"><b>Traceable lifecycle</b><span>Finalize → Reports → Pay → Cost/Profit → Cancel/Restore → Audit. No hard delete.</span></div></aside>
<main class="os-main"><section class="os-hero pp-hero"><div class="os-kicker">STEP 12 • PRODUCT SALES → BUSINESS OS</div><h1>Quotes, Business OS orders, report VP, payments, verified profit and lifecycle controls now work together.</h1><p>Member linkage is explicit only. Finalized sales create raw evidence, normalized order, frozen product lines and a report bridge. Profit remains Deferred until every line has a real explicit cost.</p><div class="os-status-row"><span class="os-chip <?= $error===null?'good':'' ?>"><?= $error===null?'PRODUCT SALES INTEGRATION LIVE':'Review required' ?></span><span class="os-chip good">6-report VP bridge</span><span class="os-chip">Explicit identity</span><span class="os-chip">No guessed profit</span><span class="os-chip">No hard delete</span></div></section>
<?php if($error):?><div class="pp-alert bad"><strong>Integration diagnostic:</strong> <?= product_h($error) ?></div><?php endif;?><?php if($success):?><div class="pp-alert good"><strong>Done:</strong> <?= product_h($success) ?><?php if(isset($_GET['order'])):?> <a href="product_sale_detail.php?order=<?= (int)$_GET['order'] ?>">Open sale detail →</a><?php endif;?></div><?php endif;?>
<?php if(!$error):?><section class="pp-grid" style="margin-top:14px"><article class="os-card pp-span-7"><div class="os-title-row"><div><h2>Saved Quotes</h2><p>Select a quote to finalize or inspect its converted sale.</p></div><a class="os-btn" href="product_order_builder.php">+ New Quote</a></div><div class="pp-table-wrap"><table class="pp-table"><thead><tr><th>Quote</th><th>Customer</th><th>Tier</th><th>Total</th><th>VP</th><th>Lifecycle</th><th></th></tr></thead><tbody><?php foreach($quotes as $q):?><tr><td><b><?= product_h($q['quote_code']) ?></b><small><?= product_h(substr((string)$q['created_at'],0,16)) ?></small></td><td><?= product_h($q['customer_name']?:'—') ?><?= $q['member_name']?'<small>Member: '.product_h($q['member_name']).'</small>':'' ?></td><td><?= product_h($q['pricing_tier_code']) ?></td><td><?= ps_money($q['grand_total']) ?></td><td><?= product_h(ps_num($q['total_vp'])) ?></td><td><?php if($q['order_id']):?><span class="pp-badge <?= $q['sale_status']==='cancelled'?'warn':'' ?>"><?= product_h(strtoupper((string)($q['sale_status']?:'ACTIVE'))) ?></span><small><?= product_h(strtoupper((string)($q['payment_status']?:'UNPAID'))) ?> • COST <?= product_h(strtoupper((string)($q['cost_status']?:'DEFERRED'))) ?></small><?php else:?><span class="pp-badge">DRAFT</span><?php endif;?></td><td><a href="?quote=<?= (int)$q['id'] ?>">Review →</a><?php if($q['order_id']):?> <a href="product_sale_detail.php?order=<?= (int)$q['order_id'] ?>">Sale →</a><?php endif;?></td></tr><?php endforeach;?><?php if(!$quotes):?><tr><td colspan="7">No saved product quotes yet.</td></tr><?php endif;?></tbody></table></div></article>
<aside class="os-card pp-span-5"><?php if(!$selected):?><h2>Choose a Quote</h2><p>Select a saved quote from the table. Nothing is written until you explicitly finalize it.</p><?php else:?><div class="os-title-row"><div><h2><?= product_h($selected['quote_code']) ?></h2><p><?= product_h($selected['customer_name']?:'No customer name') ?> • <?= product_h($selected['pricing_tier_code']) ?></p></div><span class="pp-badge"><?= count($selected['items']) ?> ITEMS</span></div><div class="pp-source"><b>MRP subtotal</b><span><?= ps_money($selected['subtotal_mrp']) ?></span></div><div class="pp-source"><b>Product payable</b><span><?= ps_money($selected['payable_amount']) ?></span></div><div class="pp-source"><b>Saving</b><span><?= ps_money($selected['saving_amount']) ?></span></div><div class="pp-source"><b>Delivery</b><span><?= ps_money($selected['delivery_charge']) ?></span></div><div class="pp-source"><b>Grand total</b><span><?= ps_money($selected['grand_total']) ?></span></div><div class="pp-source"><b>Total VP</b><span><?= product_h(ps_num($selected['total_vp'])) ?></span></div>
<?php if((int)($selected['order_id']??0)>0):$ledger=null;foreach($sales as $s)if((int)$s['order_id']===(int)$selected['order_id']){$ledger=$s;break;}?><div class="pp-alert good" style="margin-top:12px"><strong>Converted:</strong> Business OS Order #<?= (int)$selected['order_id'] ?>. <a href="product_sale_detail.php?order=<?= (int)$selected['order_id'] ?>">Open detail →</a></div><?php if($ledger):?><div class="pp-source"><b>Sale Status</b><span><?= product_h(strtoupper($ledger['sale_status'])) ?></span></div><div class="pp-source"><b>Payment</b><span><?= product_h(strtoupper($ledger['payment_status'])) ?> • <?= ps_money($ledger['paid_amount']) ?> paid</span></div><div class="pp-source"><b>Cost / Profit</b><span><?= product_h(strtoupper($ledger['cost_status'])) ?><?= $ledger['profit_total']!==null?' • '.ps_money($ledger['profit_total']).' profit':'' ?></span></div><?php if($ledger['sale_status']==='active'):?><details style="margin-top:12px"><summary>Cancel Sale Safely</summary><form method="post" class="pp-form"><input type="hidden" name="csrf" value="<?= product_h($csrf) ?>"><input type="hidden" name="action" value="cancel"><input type="hidden" name="order_id" value="<?= (int)$ledger['order_id'] ?>"><input name="reason" minlength="5" placeholder="Cancellation reason" required><button>Confirm Cancellation</button></form></details><?php else:?><details style="margin-top:12px"><summary>Restore Cancelled Sale</summary><form method="post" class="pp-form"><input type="hidden" name="csrf" value="<?= product_h($csrf) ?>"><input type="hidden" name="action" value="restore"><input type="hidden" name="order_id" value="<?= (int)$ledger['order_id'] ?>"><input name="reason" minlength="5" placeholder="Restore reason" required><button>Restore Sale</button></form></details><?php endif;?><?php endif;?>
<?php else:?><form method="post" class="pp-form" style="margin-top:14px"><input type="hidden" name="csrf" value="<?= product_h($csrf) ?>"><input type="hidden" name="action" value="finalize"><input type="hidden" name="quote_id" value="<?= (int)$selected['id'] ?>"><label>Business Order Date<input type="date" name="order_date" value="<?= product_h(date('Y-m-d')) ?>" required></label><label>Link verified Member (optional)<select name="member_id"><option value="">No member link — preserve customer snapshot only</option><?php foreach($members as $m):?><option value="<?= (int)$m['id'] ?>"><?= product_h($m['full_name'].' • #'.$m['id'].($m['mobile']?' • '.$m['mobile']:'')) ?></option><?php endforeach;?></select></label><div class="pp-alert" style="background:#fff7ea;color:#805a20"><strong>Identity rule:</strong> customer name is never auto-matched. Select a member only when you know it is the same person.</div><button>Finalize into Business OS →</button></form><?php endif;?><?php endif;?></aside></section>
<section class="os-card" style="margin-top:14px"><div class="os-title-row"><div><h2>Finalized Product Sales</h2><p>Active and cancelled sales remain visible together; cancelled sale amounts/VP are removed from effective Business OS facts while evidence remains intact.</p></div><div class="pp-actions"><a href="product_payments.php">Payments →</a><a href="product_cost_center.php">Cost Basis →</a><a href="product_sales_analytics.php">Analytics →</a></div></div><div class="pp-table-wrap"><table class="pp-table"><thead><tr><th>Order</th><th>Date</th><th>Customer</th><th>Revenue</th><th>VP</th><th>Payment</th><th>Cost</th><th>Profit</th><th>Status</th></tr></thead><tbody><?php foreach($sales as $s):?><tr><td><a href="product_sale_detail.php?order=<?= (int)$s['order_id'] ?>"><b>#<?= (int)$s['order_id'] ?></b></a><small><?= product_h($s['quote_code']?:'') ?></small></td><td><?= product_h($s['order_date']) ?></td><td><?= product_h($s['member_name']?:$s['customer_name']?:'—') ?></td><td><?= ps_money($s['net_amount']) ?></td><td><?= product_h(ps_num($s['volume_points'])) ?></td><td><?= product_h(strtoupper($s['payment_status'])) ?><small><?= ps_money($s['paid_amount']) ?> paid</small></td><td><?= product_h(strtoupper($s['cost_status'])) ?></td><td><?= $s['profit_total']===null?'—':ps_money($s['profit_total']) ?></td><td><span class="pp-badge <?= $s['sale_status']==='cancelled'?'warn':'' ?>"><?= product_h(strtoupper($s['sale_status'])) ?></span></td></tr><?php endforeach;?><?php if(!$sales):?><tr><td colspan="9">No finalized product sales yet.</td></tr><?php endif;?></tbody></table></div></section>
<div class="os-footer-note"><strong>STEP 12 policy:</strong> Product Sale report VP is bridged without becoming a MANUAL-editable fact because its raw source remains PRODUCT-SALES. Cancel/restore updates effective business values while preserving evidence.</div><?php endif;?></main></div></body></html>