<?php
declare(strict_types=1);
require_once __DIR__ . '/config/product_step12.php';
$error=null;$quotes=[];$selected=null;$items=[];$id=isset($_GET['id'])&&is_numeric($_GET['id'])?(int)$_GET['id']:0;
try{
    $pdo=business_db();product_step12_ensure($pdo);$ctx=product_org_context($pdo);$orgId=(int)$ctx['organization_id'];
    $stmt=$pdo->prepare("SELECT q.*,m.market_name,m.currency_code,l.order_id FROM product_quotes q JOIN product_markets m ON m.id=q.market_id LEFT JOIN product_quote_order_links l ON l.organization_id=q.organization_id AND l.quote_id=q.id WHERE q.organization_id=? ORDER BY q.id DESC LIMIT 100");
    $stmt->execute([$orgId]);$quotes=$stmt->fetchAll();
    if($id>0){
        $stmt=$pdo->prepare("SELECT q.*,m.market_name,m.currency_code,l.order_id FROM product_quotes q JOIN product_markets m ON m.id=q.market_id LEFT JOIN product_quote_order_links l ON l.organization_id=q.organization_id AND l.quote_id=q.id WHERE q.organization_id=? AND q.id=? LIMIT 1");
        $stmt->execute([$orgId,$id]);$selected=$stmt->fetch()?:null;if(!$selected)throw new RuntimeException('Saved quote was not found.');
        $stmt=$pdo->prepare("SELECT * FROM product_quote_items WHERE quote_id=? ORDER BY id");$stmt->execute([$id]);$items=$stmt->fetchAll();
    }
}catch(Throwable $e){$error=$e->getMessage();}
?>
<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>Saved Product Quotes - Healthcare Wellness Club</title><link rel="stylesheet" href="assets/dashboard.css"><link rel="stylesheet" href="assets/product_pro.css"><style>@media print{.os-topbar,.os-sidebar,.no-print{display:none!important}.os-layout{display:block;width:100%;margin:0}.os-main{width:100%}.os-card{box-shadow:none}}</style></head><body>
<header class="os-topbar"><div class="os-topbar-inner"><a class="os-brand" href="product_catalog.php"><img src="../img/logo.png" alt="logo"><span><strong>Healthcare Wellness Club</strong><small>Product & Price Pro • Saved Quotes</small></span></a><div class="os-top-actions"><a class="os-btn" href="product_order_builder.php">+ New Quote</a><a class="os-btn" href="product_sales_center.php">Finalize Sale</a><button class="os-btn" onclick="window.print()">Print / Save PDF</button><a class="os-btn primary" href="product_catalog.php">Catalog</a></div></div></header>
<div class="os-layout"><aside class="os-sidebar"><div class="os-nav-label">Product System</div><nav class="os-nav"><a href="product_catalog.php"><i class="dot"></i>Catalog</a><a href="product_order_builder.php"><i class="dot"></i>Order Builder</a><a class="active" href="product_quotes.php"><i class="dot"></i>Saved Quotes</a><a href="product_sales_center.php"><i class="dot"></i>Finalize Sale</a><a href="product_favorites.php"><i class="dot"></i>Favorites</a></nav></aside><main class="os-main">
<section class="os-hero pp-hero no-print"><div class="os-kicker">STEP 11 + STEP 12A • Quote History</div><h1>Review, print or finalize a saved product estimate.</h1><p>Each quote freezes its price tier and product totals. STEP 12A can convert it into one traceable Business OS Product Sale without changing the saved quote snapshot.</p><div class="os-status-row"><span class="os-chip <?= $error===null?'good':'' ?>"><?= $error===null?'QUOTE HISTORY LIVE':'Review required' ?></span><span class="os-chip"><?= count($quotes) ?> saved quotes</span></div></section>
<?php if($error):?><div class="pp-alert bad"><?= product_h($error) ?></div><?php elseif($selected):?>
<section class="os-card" style="margin-top:14px"><div class="os-title-row"><div><span class="pp-stock"><?= product_h($selected['quote_code']) ?></span><h2><?= product_h($selected['customer_name']?:'Product Estimate') ?></h2><p><?= product_h($selected['market_name'].' • '.$selected['pricing_tier_code'].' • '.$selected['created_at']) ?></p></div><div class="no-print" style="display:flex;gap:8px;flex-wrap:wrap"><a class="os-btn" href="product_quotes.php">Back</a><?php if((int)($selected['order_id']??0)>0):?><a class="os-btn primary" href="product_sale_detail.php?order=<?= (int)$selected['order_id'] ?>">Business Order #<?= (int)$selected['order_id'] ?></a><?php else:?><a class="os-btn primary" href="product_sales_center.php?quote=<?= (int)$selected['id'] ?>">Finalize Sale →</a><?php endif;?></div></div>
<div class="pp-table-wrap"><table class="pp-table"><thead><tr><th>Stock</th><th>Product</th><th>Qty</th><th>MRP</th><th>Unit Price</th><th>VP</th><th>Line Price</th></tr></thead><tbody><?php foreach($items as $it):?><tr><td><?= product_h($it['stock_no']) ?></td><td><?= product_h($it['product_name']) ?></td><td><?= product_h($it['quantity']) ?></td><td>₹<?= number_format((float)$it['unit_mrp'],2) ?></td><td>₹<?= number_format((float)$it['unit_price'],2) ?></td><td><?= product_h($it['line_vp']) ?></td><td>₹<?= number_format((float)$it['line_price'],2) ?></td></tr><?php endforeach;?></tbody></table></div>
<div style="max-width:460px;margin:16px 0 0 auto"><div class="pp-total"><span>MRP Total</span><strong>₹<?= number_format((float)$selected['subtotal_mrp'],2) ?></strong></div><div class="pp-total"><span>Payable</span><strong>₹<?= number_format((float)$selected['payable_amount'],2) ?></strong></div><div class="pp-total"><span>Saving</span><strong>₹<?= number_format((float)$selected['saving_amount'],2) ?></strong></div><div class="pp-total"><span>Total VP</span><strong><?= product_h($selected['total_vp']) ?></strong></div><div class="pp-total"><span>Delivery</span><strong>₹<?= number_format((float)$selected['delivery_charge'],2) ?></strong></div><div class="pp-total pp-grand"><span>Grand Total</span><strong>₹<?= number_format((float)$selected['grand_total'],2) ?></strong></div></div><?php if($selected['notes']):?><div class="os-footer-note"><strong>Notes:</strong> <?= product_h($selected['notes']) ?></div><?php endif;?></section>
<?php else:?><section class="os-card" style="margin-top:14px"><div class="pp-table-wrap"><table class="pp-table"><thead><tr><th>Quote</th><th>Customer</th><th>Tier</th><th>MRP</th><th>Payable</th><th>VP</th><th>Grand Total</th><th>Status</th><th></th></tr></thead><tbody><?php foreach($quotes as $q):?><tr><td><b><?= product_h($q['quote_code']) ?></b><small><?= product_h($q['created_at']) ?></small></td><td><?= product_h($q['customer_name']?:'—') ?></td><td><?= product_h($q['pricing_tier_code']) ?></td><td>₹<?= number_format((float)$q['subtotal_mrp'],2) ?></td><td>₹<?= number_format((float)$q['payable_amount'],2) ?></td><td><?= product_h($q['total_vp']) ?></td><td>₹<?= number_format((float)$q['grand_total'],2) ?></td><td><span class="pp-badge"><?= $q['order_id']?'ORDER #'.(int)$q['order_id']:strtoupper((string)$q['status']) ?></span></td><td><a class="pp-badge" href="?id=<?= (int)$q['id'] ?>">Open</a></td></tr><?php endforeach;?></tbody></table></div><?php if(!$quotes):?><div class="pp-empty">No saved quotes yet. Build one in Order Builder.</div><?php endif;?></section><?php endif;?></main></div><script src="assets/business-collapsible.js?v=20260820-1" defer></script></body></html>
