<?php
declare(strict_types=1);require_once __DIR__ . '/config/product_step12.php';
$error=null;$rows=[];$top=[];$months=[];$metrics=['active'=>0,'cancelled'=>0,'revenue'=>0.0,'vp'=>0.0,'paid'=>0.0,'outstanding'=>0.0,'profit'=>0.0,'profit_sales'=>0,'deferred'=>0];
try{$pdo=business_db();product_step12_ensure($pdo);$ctx=product_step12_context($pdo);$orgId=(int)$ctx['organization_id'];$rows=product_step12_sales_rows($pdo,$orgId,'all');
 foreach($rows as $r){if($r['sale_status']==='cancelled'){$metrics['cancelled']++;continue;}$metrics['active']++;$metrics['revenue']+=(float)$r['net_amount'];$metrics['vp']+=(float)$r['volume_points'];$metrics['paid']+=(float)$r['paid_amount'];$metrics['outstanding']+=max(0,(float)$r['net_amount']-(float)$r['paid_amount']);if($r['cost_status']==='complete'&&$r['profit_total']!==null){$metrics['profit']+=(float)$r['profit_total'];$metrics['profit_sales']++;}else{$metrics['deferred']++;}$key=substr((string)$r['order_date'],0,7);if(!isset($months[$key]))$months[$key]=['sales'=>0,'revenue'=>0.0,'vp'=>0.0,'profit'=>0.0,'profit_sales'=>0];$months[$key]['sales']++;$months[$key]['revenue']+=(float)$r['net_amount'];$months[$key]['vp']+=(float)$r['volume_points'];if($r['cost_status']==='complete'&&$r['profit_total']!==null){$months[$key]['profit']+=(float)$r['profit_total'];$months[$key]['profit_sales']++;}}
 krsort($months);
 $stmt=$pdo->prepare("SELECT poi.product_id,poi.stock_no,poi.product_name_snapshot,SUM(poi.quantity) qty,SUM(poi.line_price) revenue,SUM(poi.line_vp) vp FROM product_order_items poi JOIN product_sale_ledger l ON l.organization_id=poi.organization_id AND l.order_id=poi.order_id WHERE poi.organization_id=? AND l.sale_status='active' GROUP BY poi.product_id,poi.stock_no,poi.product_name_snapshot ORDER BY revenue DESC,qty DESC LIMIT 12");$stmt->execute([$orgId]);$top=$stmt->fetchAll();
}catch(Throwable $e){$error=$e->getMessage();}
function psa_money(mixed $v):string{return '₹'.number_format((float)$v,2,'.',',');}function psa_num(mixed $v):string{$x=number_format((float)$v,3,'.','');return rtrim(rtrim($x,'0'),'.');}
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>Product Sales Analytics - Healthcare Wellness Club</title><link rel="stylesheet" href="assets/dashboard.css"><link rel="stylesheet" href="assets/product_pro.css"></head><body>
<header class="os-topbar"><div class="os-topbar-inner"><a class="os-brand" href="index.php"><img src="../img/logo.png" alt="logo"><span><strong>Healthcare Wellness Club</strong><small>STEP 12 • Product Sales Analytics</small></span></a><div class="os-top-actions"><a class="os-btn" href="product_sales_center.php">Sales</a><a class="os-btn" href="product_payments.php">Payments</a><a class="os-btn primary" href="product_cost_center.php">Cost Basis</a></div></div></header>
<div class="os-layout"><aside class="os-sidebar"><div class="os-nav-label">STEP 12</div><nav class="os-nav"><a href="product_sales_center.php"><i class="dot"></i>Sales Center</a><a href="product_cost_center.php"><i class="dot"></i>Cost Basis</a><a href="product_payments.php"><i class="dot"></i>Payments</a><a class="active" href="product_sales_analytics.php"><i class="dot"></i>Sales Analytics</a><a href="step12_audit.php"><i class="dot"></i>STEP 12 Audit</a></nav></aside>
<main class="os-main"><section class="os-hero pp-hero"><div class="os-kicker">STEP 12E • SALES + COLLECTION + PROFIT</div><h1>See product sales performance without mixing estimated profit with verified profit.</h1><p>Revenue and VP come from finalized active sales. Profit is included only for sales with complete explicit cost coverage; every uncovered sale remains visibly Deferred.</p><div class="os-status-row"><span class="os-chip <?= $error===null?'good':'' ?>"><?= $error===null?'PRODUCT SALES ANALYTICS LIVE':'Review required' ?></span><span class="os-chip"><?= number_format($metrics['active']) ?> active sales</span><span class="os-chip"><?= number_format($metrics['cancelled']) ?> cancelled</span><span class="os-chip"><?= number_format($metrics['deferred']) ?> profit deferred</span></div></section><?php if($error):?><div class="pp-alert bad"><strong>Analytics diagnostic:</strong> <?= product_h($error) ?></div><?php else:?>
<section class="s10-kpis" style="margin-top:14px"><div class="s10-kpi"><small>Active Revenue</small><strong><?= psa_money($metrics['revenue']) ?></strong><span>Finalized active product sales</span></div><div class="s10-kpi"><small>Total VP</small><strong><?= product_h(psa_num($metrics['vp'])) ?></strong><span>From active product lines</span></div><div class="s10-kpi"><small>Collected</small><strong><?= psa_money($metrics['paid']) ?></strong><span>Actual active payments</span></div><div class="s10-kpi"><small>Outstanding</small><strong><?= psa_money($metrics['outstanding']) ?></strong><span>Revenue not yet collected</span></div></section>
<section class="pp-grid"><article class="os-card pp-span-7"><div class="os-title-row"><div><h2>Monthly Product Sales</h2><p>Cancelled sales are excluded automatically.</p></div></div><div class="pp-table-wrap"><table class="pp-table"><thead><tr><th>Month</th><th>Sales</th><th>Revenue</th><th>VP</th><th>Verified Profit</th><th>Cost-covered Sales</th></tr></thead><tbody><?php foreach($months as $month=>$m):?><tr><td><b><?= product_h($month) ?></b></td><td><?= number_format($m['sales']) ?></td><td><?= psa_money($m['revenue']) ?></td><td><?= product_h(psa_num($m['vp'])) ?></td><td><?= psa_money($m['profit']) ?></td><td><?= number_format($m['profit_sales']) ?> / <?= number_format($m['sales']) ?></td></tr><?php endforeach;?><?php if(!$months):?><tr><td colspan="6">No finalized active product sales yet.</td></tr><?php endif;?></tbody></table></div></article><aside class="os-card pp-span-5"><h2>Profit Integrity</h2><div class="pp-source"><b>Verified Profit</b><span><?= psa_money($metrics['profit']) ?></span></div><div class="pp-source"><b>Sales with full cost</b><span><?= number_format($metrics['profit_sales']) ?></span></div><div class="pp-source"><b>Profit Deferred</b><span><?= number_format($metrics['deferred']) ?></span></div><p style="margin-top:12px">A deferred sale contributes Revenue and VP, but contributes <strong>nothing</strong> to verified profit until all its product lines have explicit dated cost.</p><div class="pp-actions"><a href="product_cost_center.php">Add Cost Basis →</a><a href="product_payments.php">Collections →</a></div></aside></section>
<section class="os-card" style="margin-top:14px"><h2>Top Products by Active Sale Revenue</h2><div class="pp-table-wrap"><table class="pp-table"><thead><tr><th>Stock</th><th>Product</th><th>Qty</th><th>Revenue</th><th>VP</th></tr></thead><tbody><?php foreach($top as $t):?><tr><td><b><?= product_h($t['stock_no']) ?></b></td><td><?= product_h($t['product_name_snapshot']) ?></td><td><?= product_h(psa_num($t['qty'])) ?></td><td><?= psa_money($t['revenue']) ?></td><td><?= product_h(psa_num($t['vp'])) ?></td></tr><?php endforeach;?><?php if(!$top):?><tr><td colspan="5">No product sales yet.</td></tr><?php endif;?></tbody></table></div></section><?php endif;?>
<div class="os-footer-note"><strong>Analytics policy:</strong> cancelled sales are excluded; reversed payments are excluded; verified profit requires complete explicit cost coverage.</div></main></div><script src="assets/business-collapsible.js?v=20260820-1" defer></script></body></html>
