<?php
declare(strict_types=1);
require_once __DIR__ . '/config/product_step12.php';
$error=null;$order=null;$items=[];$payments=[];$events=[];$ledger=null;$ctx=[];$orderId=(int)($_GET['order']??0);
try{
    if($orderId<=0)throw new RuntimeException('Choose a valid Product Sale order.');
    $pdo=business_db();product_step12_ensure($pdo);$ctx=product_step12_context($pdo);$orgId=(int)$ctx['organization_id'];
    $stmt=$pdo->prepare("SELECT o.*,m.full_name member_name,m.mobile member_mobile,l.quote_id,q.quote_code,q.customer_name,q.pricing_tier_code,q.payable_amount product_payable,q.delivery_charge,q.grand_total
        FROM orders o LEFT JOIN members m ON m.id=o.member_id AND m.organization_id=o.organization_id LEFT JOIN product_quote_order_links l ON l.organization_id=o.organization_id AND l.order_id=o.id LEFT JOIN product_quotes q ON q.id=l.quote_id AND q.organization_id=o.organization_id
        WHERE o.organization_id=? AND o.id=? AND o.order_type='product_sale' LIMIT 1");$stmt->execute([$orgId,$orderId]);$order=$stmt->fetch();if(!$order)throw new RuntimeException('Product Sale order was not found.');
    $ledger=product_step12_ledger($pdo,$orgId,$orderId);if($ledger)$paymentState=product_step12_sync_payment_status($pdo,$orderId);else $paymentState=['paid'=>0,'due'=>(float)$order['net_amount'],'outstanding'=>(float)$order['net_amount'],'status'=>'unpaid'];
    $stmt=$pdo->prepare("SELECT poi.*,cv.source_reference cost_source,cv.effective_from cost_effective FROM product_order_items poi LEFT JOIN product_cost_versions cv ON cv.id=poi.cost_version_id AND cv.organization_id=poi.organization_id WHERE poi.organization_id=? AND poi.order_id=? ORDER BY poi.id");$stmt->execute([$orgId,$orderId]);$items=$stmt->fetchAll();
    $stmt=$pdo->prepare("SELECT * FROM product_sale_payments WHERE organization_id=? AND order_id=? ORDER BY payment_date,id");$stmt->execute([$orgId,$orderId]);$payments=$stmt->fetchAll();
    if($ledger){$stmt=$pdo->prepare("SELECT * FROM product_sale_lifecycle_events WHERE organization_id=? AND sale_ledger_id=? ORDER BY id DESC");$stmt->execute([$orgId,(int)$ledger['id']]);$events=$stmt->fetchAll();}
}catch(Throwable $e){$error=$e->getMessage();$paymentState=['paid'=>0,'due'=>0,'outstanding'=>0,'status'=>'unpaid'];}
function psd_money(mixed $v):string{return '₹'.number_format((float)$v,2,'.',',');}function psd_num(mixed $v):string{$x=number_format((float)$v,3,'.','');return rtrim(rtrim($x,'0'),'.');}
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>Product Sale Detail - Healthcare Wellness Club</title><link rel="stylesheet" href="assets/dashboard.css"><link rel="stylesheet" href="assets/product_pro.css"></head><body>
<header class="os-topbar"><div class="os-topbar-inner"><a class="os-brand" href="index.php"><img src="../img/logo.png" alt="logo"><span><strong>Healthcare Wellness Club</strong><small>STEP 12 • Product Sale 360° Trace</small></span></a><div class="os-top-actions"><a class="os-btn" href="product_sales_center.php">Sales Center</a><a class="os-btn" href="product_payments.php?order=<?= $orderId ?>">Payments</a><a class="os-btn" href="operations_center.php">Operations</a><a class="os-btn primary" href="product_sales_analytics.php">Analytics</a></div></div></header>
<div class="os-layout"><aside class="os-sidebar"><div class="os-nav-label">STEP 12</div><nav class="os-nav"><a href="product_sales_center.php"><i class="dot"></i>Sales Center</a><a href="product_cost_center.php"><i class="dot"></i>Cost Basis</a><a href="product_payments.php"><i class="dot"></i>Payments</a><a href="product_sales_analytics.php"><i class="dot"></i>Sales Analytics</a><a class="active" href="product_sale_detail.php?order=<?= $orderId ?>"><i class="dot"></i>Sale Detail</a><a href="step12_audit.php"><i class="dot"></i>STEP 12 Audit</a></nav></aside>
<main class="os-main"><section class="os-hero pp-hero"><div class="os-kicker">STEP 12F • SALE 360° TRACE</div><h1><?= $error?'Product Sale review required':'Business OS Order #'.(int)$order['id'] ?></h1><p>Quote snapshot, member/customer identity, product lines, exact cost coverage, payment collection, lifecycle events and raw Business OS source trace remain connected here.</p><?php if(!$error):?><div class="os-status-row"><span class="os-chip <?= ($ledger['sale_status']??'active')==='active'?'good':'' ?>"><?= product_h(strtoupper((string)($ledger['sale_status']??'ACTIVE'))) ?></span><span class="os-chip"><?= product_h(strtoupper($paymentState['status'])) ?> • <?= psd_money($paymentState['paid']) ?> paid</span><span class="os-chip">Cost <?= product_h(strtoupper((string)($ledger['cost_status']??'DEFERRED'))) ?></span><span class="os-chip"><?= product_h(psd_num($order['volume_points'])) ?> VP</span></div><?php endif;?></section>
<?php if($error):?><div class="pp-alert bad"><strong>Sale diagnostic:</strong> <?= product_h($error) ?></div><?php else:?><section class="pp-grid" style="margin-top:14px"><article class="os-card pp-span-8"><div class="os-title-row"><div><h2><?= product_h($order['quote_code']?:'Product Sale') ?></h2><p><?= product_h((string)$order['order_date']) ?> • <?= product_h($order['pricing_tier_code']?:'—') ?></p></div><span class="pp-badge">ORDER #<?= (int)$order['id'] ?></span></div><div class="pp-table-wrap"><table class="pp-table"><thead><tr><th>Stock</th><th>Product</th><th>Qty</th><th>Unit Price</th><th>VP</th><th>Unit Cost</th><th>Line Profit</th><th>Profit State</th></tr></thead><tbody><?php foreach($items as $i):?><tr><td><b><?= product_h($i['stock_no']) ?></b></td><td><?= product_h($i['product_name_snapshot']) ?></td><td><?= product_h(psd_num($i['quantity'])) ?></td><td><?= psd_money($i['unit_price']) ?></td><td><?= product_h(psd_num($i['line_vp'])) ?></td><td><?= $i['unit_cost']===null?'—':psd_money($i['unit_cost']) ?><?= $i['cost_source']?'<small>'.product_h($i['cost_source']).'</small>':'' ?></td><td><?= $i['line_profit']===null?'—':psd_money($i['line_profit']) ?></td><td><span class="pp-badge"><?= product_h(strtoupper((string)$i['profit_status'])) ?></span></td></tr><?php endforeach;?><?php if(!$items):?><tr><td colspan="8">No line item snapshots found.</td></tr><?php endif;?></tbody></table></div></article>
<aside class="os-card pp-span-4"><h2>Business Mapping</h2><div class="pp-source"><b>Customer snapshot</b><span><?= product_h($order['customer_name']?:'—') ?></span></div><div class="pp-source"><b>Verified member</b><span><?= product_h($order['member_name']?:'Not linked') ?><?= $order['member_id']?' #'.(int)$order['member_id']:'' ?></span></div><div class="pp-source"><b>Gross</b><span><?= psd_money($order['gross_amount']) ?></span></div><div class="pp-source"><b>Discount/Saving</b><span><?= psd_money($order['discount_amount']) ?></span></div><div class="pp-source"><b>Net Revenue</b><span><?= psd_money($order['net_amount']) ?></span></div><div class="pp-source"><b>Paid / Outstanding</b><span><?= psd_money($paymentState['paid']) ?> / <?= psd_money($paymentState['outstanding']) ?></span></div><div class="pp-source"><b>Cost Status</b><span><?= product_h(strtoupper((string)($ledger['cost_status']??'deferred'))) ?></span></div><div class="pp-source"><b>Verified Profit</b><span><?= ($ledger['profit_total']??null)===null?'—':psd_money($ledger['profit_total']) ?></span></div><div class="pp-source"><b>Raw Source ID</b><span>#<?= (int)$order['source_record_id'] ?></span></div><div class="pp-actions"><a href="product_payments.php?order=<?= (int)$order['id'] ?>">Payments →</a><a href="product_cost_center.php">Cost Basis →</a></div></aside></section>
<section class="pp-grid"><article class="os-card pp-span-6"><h2>Payment History</h2><div class="pp-table-wrap"><table class="pp-table"><thead><tr><th>Date</th><th>Amount</th><th>Method</th><th>Status</th></tr></thead><tbody><?php foreach($payments as $p):?><tr><td><?= product_h($p['payment_date']) ?></td><td><?= psd_money($p['amount']) ?></td><td><?= product_h(strtoupper($p['payment_method'])) ?><?= $p['reference_no']?'<small>'.product_h($p['reference_no']).'</small>':'' ?></td><td><?= product_h(strtoupper($p['status'])) ?></td></tr><?php endforeach;?><?php if(!$payments):?><tr><td colspan="4">No payments recorded yet.</td></tr><?php endif;?></tbody></table></div></article><article class="os-card pp-span-6"><h2>Lifecycle Timeline</h2><div class="pp-table-wrap"><table class="pp-table"><thead><tr><th>Event</th><th>Reason</th><th>Time</th></tr></thead><tbody><?php foreach($events as $e):?><tr><td><b><?= product_h(ucwords(str_replace('_',' ',$e['event_type']))) ?></b></td><td><?= product_h($e['reason']?:'—') ?></td><td><?= product_h($e['created_at']) ?></td></tr><?php endforeach;?><?php if(!$events):?><tr><td colspan="3">No lifecycle events found.</td></tr><?php endif;?></tbody></table></div></article></section>
<div class="os-footer-note"><strong>Trace policy:</strong> cancellation never deletes this sale. It changes active business effect while preserving quote, raw source, order, product lines, payments and lifecycle evidence.</div><?php endif;?></main></div></body></html>