<?php
declare(strict_types=1);
require_once __DIR__ . '/config/product_step11.php';
$error=null;$autoSeeded=false;$metrics=[];$rows=[];$categories=[];$ctx=[];
$q=trim((string)($_GET['q']??''));$category=trim((string)($_GET['category']??'ALL'));$tier=trim((string)($_GET['tier']??'PC_GOLD'));
$allowedTiers=['MRP','PC_BRONZE','PC_SILVER','PC_GOLD','ASSOC_RETAIL','ASSOC_EARN_BASE','ASSOC_25','ASSOC_35','ASSOC_42','ASSOC_50','PU_PRICE'];if(!in_array($tier,$allowedTiers,true))$tier='PC_GOLD';
$tierLabels=['MRP'=>'MRP','PC_BRONZE'=>'Preferred Bronze','PC_SILVER'=>'Preferred Silver','PC_GOLD'=>'Preferred Gold','ASSOC_RETAIL'=>'Associate Retail','ASSOC_EARN_BASE'=>'Earn Base','ASSOC_25'=>'Associate 25%','ASSOC_35'=>'Senior Consultant 35%','ASSOC_42'=>'Qualified Producer / Success Builder 42%','ASSOC_50'=>'Supervisor 50%','PU_PRICE'=>'PU Price'];
try{$pdo=business_db();product_step11_ensure($pdo);$ctx=product_org_context($pdo);$orgId=(int)$ctx['organization_id'];$metrics=product_foundation_metrics($pdo,$orgId);if((int)$metrics['products']===0){product_step11_apply_seed($pdo);$autoSeeded=true;$metrics=product_foundation_metrics($pdo,$orgId);}$stmt=$pdo->prepare("SELECT category_name FROM product_categories WHERE organization_id=? AND status='active' ORDER BY sort_order,category_name");$stmt->execute([$orgId]);$categories=$stmt->fetchAll(PDO::FETCH_COLUMN);$rows=product_step11_catalog_rows($pdo,$orgId,$q,$category);}catch(Throwable $e){$error=$e->getMessage();}
function pc_img(array $r):string{return $r['image_url']?:('product_placeholder.php?'.http_build_query(['name'=>$r['product_name'],'stock'=>$r['sku'],'cat'=>$r['category_name']]));}
function pc_exact_price(array $r,string $tier):?float{if($tier==='MRP')return(float)$r['mrp'];return array_key_exists($tier,$r['tiers'])?(float)$r['tiers'][$tier]:null;}
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>Product & Price Pro - Healthcare Wellness Club</title><link rel="stylesheet" href="assets/dashboard.css"><link rel="stylesheet" href="assets/product_pro.css"></head><body>
<header class="os-topbar"><div class="os-topbar-inner"><a class="os-brand" href="index.php"><img src="../img/logo.png" alt="Healthcare Wellness Club logo"><span><strong>Healthcare Wellness Club</strong><small>Product & Price Pro • Live India Catalog</small></span></a><div class="os-top-actions"><a class="os-btn" href="product_master_manager.php">+ New / Update Product</a><a class="os-btn" href="product_order_builder.php">+ Order Builder</a><a class="os-btn" href="product_favorites.php">Favorites</a><a class="os-btn" href="product_images.php">Images</a><a class="os-btn primary" href="index.php">Dashboard</a></div></div></header>
<div class="os-layout"><aside class="os-sidebar"><div class="os-nav-label">Product System</div><nav class="os-nav"><a class="active" href="product_catalog.php"><i class="dot"></i>Product Catalog</a><a href="product_master_manager.php"><i class="dot"></i>New / Update Product</a><a href="product_order_builder.php"><i class="dot"></i>Order Builder</a><a href="product_compare.php"><i class="dot"></i>Compare</a><a href="product_favorites.php"><i class="dot"></i>Favorites</a><a href="product_quotes.php"><i class="dot"></i>Saved Quotes</a><a href="product_data_center.php"><i class="dot"></i>Product Data Center</a><a href="product_images.php"><i class="dot"></i>Image Manager</a><a href="product_price_history.php"><i class="dot"></i>Price History</a><a href="product_import_center.php"><i class="dot"></i>PDF Import</a><a href="product_audit.php"><i class="dot"></i>STEP 11 Audit</a></nav><div class="os-sidebar-status"><b><?= $error===null?'STEP 11 catalog live':'Catalog review required' ?></b><span>Exact PDF prices • effective 15 Apr 2026 • future launches can be added from New / Update Product.</span></div></aside><main class="os-main">
<section class="os-hero pp-hero"><div class="os-kicker">STEP 11 • Product & Price Pro</div><h1>Search a product, choose the customer level and see the exact PDF-listed price instantly.</h1><p>India Stock No., VP, MRP, Preferred Bronze/Silver/Gold and Associate Retail/Earn Base/25%/35%/42%/50% are connected to dated price versions. Future product launches can be added with complete master data, image and exact prices without replacing historical versions.</p><div class="os-status-row"><span class="os-chip <?= $error===null?'good':'' ?>"><?= $error===null?'PRODUCT CATALOG LIVE':'Review required' ?></span><span class="os-chip good"><?= number_format($metrics['products']??0) ?> products/items</span><span class="os-chip"><?= number_format($metrics['categories']??0) ?> categories</span><span class="os-chip"><?= number_format($metrics['price_versions']??0) ?> price versions</span><span class="os-chip"><?= number_format($metrics['images']??0) ?> online image matches</span></div></section>
<?php if($autoSeeded):?><div class="pp-alert good"><strong>First-run setup:</strong> the reviewed April 2026 PDF catalog was seeded automatically.</div><?php endif;?><?php if($error):?><div class="pp-alert bad"><strong>Catalog diagnostic:</strong> <?= product_h($error) ?></div><?php endif;?>
<?php if(!$error):?><section class="os-card" style="margin-top:14px"><form method="get" class="pp-toolbar"><input name="q" value="<?= product_h($q) ?>" placeholder="Search product name or Stock No…"><select name="category"><option value="ALL">All categories</option><?php foreach($categories as $c):?><option <?= $category===$c?'selected':'' ?>><?= product_h($c) ?></option><?php endforeach;?></select><select name="tier"><?php foreach($tierLabels as $code=>$label):?><option value="<?= product_h($code) ?>" <?= $tier===$code?'selected':'' ?>><?= product_h($label) ?></option><?php endforeach;?></select><button>Apply →</button></form><div class="pp-summary"><span><?= number_format(count($rows)) ?> visible</span><span>Selected: <?= product_h($tierLabels[$tier]) ?></span><span>Latest active dated price version</span><span>Currency: INR</span></div></section>
<section class="pp-catalog"><?php foreach($rows as $r):$selected=pc_exact_price($r,$tier);$state=$r['image_url']?($r['verification_status']?:'needs_review'):'placeholder';?><article class="pp-product"><div class="pp-img-wrap"><img src="<?= product_h(pc_img($r)) ?>" alt="<?= product_h($r['product_name']) ?>" loading="lazy" onerror="this.src='<?= product_h('product_placeholder.php?'.http_build_query(['name'=>$r['product_name'],'stock'=>$r['sku'],'cat'=>$r['category_name']])) ?>'"><span class="pp-img-state"><?= product_h(strtoupper(str_replace('_',' ',$state))) ?></span></div><div class="pp-product-body"><span class="pp-stock">Stock <?= product_h($r['sku']) ?></span><h3><?= product_h($r['product_name']) ?></h3><span class="cat"><?= product_h($r['category_name']) ?><?= $r['pack_size']?' • '.product_h(rtrim(rtrim(number_format((float)$r['pack_size'],3,'.',''),'0'),'.').' '.$r['pack_unit']):'' ?></span><div class="pp-price-row"><div class="pp-price"><small>MRP</small><b>₹<?= number_format((float)$r['mrp'],2) ?></b></div><div class="pp-price"><small><?= product_h($tierLabels[$tier]) ?></small><b><?= $selected===null?'—':'₹'.number_format($selected,2) ?></b></div><div class="pp-price"><small>Volume Points</small><b class="pp-vp"><?= product_h(rtrim(rtrim(number_format((float)$r['volume_points'],3,'.',''),'0'),'.')) ?> VP</b></div><div class="pp-price"><small>Effective</small><b><?= product_h(date('d M Y',strtotime((string)$r['effective_from']))) ?></b></div></div><?php if($selected===null):?><div class="pp-alert" style="margin-top:9px;background:#fff7ea;color:#805a20">This price level is not listed for this item in the reviewed source.</div><?php endif;?><div class="pp-card-actions"><a class="primary" href="product_detail.php?id=<?= (int)$r['id'] ?>">Details</a><a href="product_master_manager.php?edit=<?= (int)$r['id'] ?>">Edit Product</a><a href="product_order_builder.php?add=<?= (int)$r['id'] ?>&tier=<?= product_h($tier) ?>">Add to Order</a></div></div></article><?php endforeach;?></section><?php if(!$rows):?><div class="os-card pp-empty" style="margin-top:14px">No matching product found. Try a shorter Stock No. or product name.</div><?php endif;?><?php endif;?>
<div class="os-footer-note"><strong>Pricing policy:</strong> displayed prices are source-exact values from the reviewed PDFs or later authoritative launch/update sources. Missing customer/tier prices are shown as unlisted; Product & Price Pro does not replace them with a guessed percentage or MRP.</div></main></div></body></html>