<?php
declare(strict_types=1);

session_start();
require_once __DIR__ . '/config/step10_services.php';

if(empty($_SESSION['saved_views_csrf']))$_SESSION['saved_views_csrf']=bin2hex(random_bytes(24));$csrf=(string)$_SESSION['saved_views_csrf'];
$error=null;$success=null;$ctx=['organization_id'=>0,'club_id'=>0];$views=[];
$targets=[
 'global_search.php'=>'Global Search','members.php'=>'Members & Network','member_profile.php'=>'Member Profile 360°','operations_center.php'=>'Operations Center','insights_center.php'=>'Insights Center','alerts_center.php'=>'Alerts & Follow-ups','report_center.php'=>'Report Center','master_tracking.php'=>'Master Tracking','sp_house.php'=>'SP House','name_wise_tracking.php'=>'Name Wise Tracking','master_business_tracking.php'=>'Master Business Tracking','ums_renewal.php'=>'UMS Renewal','ums_active_duration.php'=>'UMS Active Duration','data_quality.php'=>'Data Quality','audit_center.php'=>'Audit Center','export_center.php'=>'Export Center'
];
try{
 $pdo=business_db();$ctx=step10_org_context($pdo);step10_ensure_tables($pdo);$orgId=(int)$ctx['organization_id'];$clubId=(int)$ctx['club_id'];
 if($_SERVER['REQUEST_METHOD']==='POST'){
  if(!hash_equals($csrf,(string)($_POST['csrf']??'')))throw new RuntimeException('Security token mismatch. Refresh and try again.');
  $action=step10_trim($_POST['action']??'');
  if($action==='save'){
   $name=preg_replace('/\s+/u',' ',step10_trim($_POST['view_name']??''))?:'';$target=step10_trim($_POST['target_page']??'');$query=ltrim(step10_trim($_POST['query_string']??''),'?');
   $len=function_exists('mb_strlen')?mb_strlen($name,'UTF-8'):strlen($name);if($len<2||$len>120)throw new RuntimeException('View name must be 2–120 characters.');if(!isset($targets[$target]))throw new RuntimeException('Target page is not allowed.');if(strlen($query)>1000)throw new RuntimeException('Saved query is too long.');
   if($query!==''&&preg_match('/(?:https?:|javascript:|\\|\.\.)/i',$query))throw new RuntimeException('Saved query contains an unsafe value.');
   $stmt=$pdo->prepare("INSERT INTO business_saved_views(organization_id,user_id,view_name,view_type,target_page,query_string,is_favorite) VALUES (?,NULL,?,'business_workspace',?,?,1)");$stmt->execute([$orgId,$name,$target,$query!==''?$query:null]);$id=(int)$pdo->lastInsertId();step10_audit($pdo,$orgId,$clubId,'business_saved_view_created','business_saved_view',$id,['name'=>$name,'target_page'=>$target,'query_string'=>$query]);$success='Saved view created.';
  }
  if($action==='delete'){$id=isset($_POST['view_id'])&&is_numeric($_POST['view_id'])?(int)$_POST['view_id']:0;$stmt=$pdo->prepare("DELETE FROM business_saved_views WHERE organization_id=? AND id=?");$stmt->execute([$orgId,$id]);if($stmt->rowCount()!==1)throw new RuntimeException('Saved view was not found.');step10_audit($pdo,$orgId,$clubId,'business_saved_view_deleted','business_saved_view',$id,[]);$success='Saved view removed.';}
 }
 $stmt=$pdo->prepare("SELECT * FROM business_saved_views WHERE organization_id=? AND is_favorite=1 ORDER BY updated_at DESC,id DESC");$stmt->execute([$orgId]);$views=$stmt->fetchAll();
}catch(Throwable $e){$error=$e->getMessage();}
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>Saved Views - Healthcare Wellness Club</title><link rel="stylesheet" href="assets/dashboard.css"><link rel="stylesheet" href="assets/step10.css"></head><body>
<header class="os-topbar"><div class="os-topbar-inner"><a class="os-brand" href="index.php"><img src="../img/logo.png" alt="Healthcare Wellness Club logo"><span><strong>Healthcare Wellness Club</strong><small>Business OS • Saved Views & Favorites</small></span></a><div class="os-top-actions"><a class="os-btn" href="global_search.php">Search</a><a class="os-btn" href="today_center.php">Today</a><a class="os-btn primary" href="index.php">Dashboard</a></div></div></header>
<div class="os-layout"><aside class="os-sidebar"><div class="os-nav-label">Business OS</div><nav class="os-nav"><a href="index.php"><i class="dot"></i>Dashboard</a><a href="today_center.php"><i class="dot"></i>Today Center</a><a href="global_search.php"><i class="dot"></i>Global Search</a><a class="active" href="saved_views.php"><i class="dot"></i>Saved Views</a><a href="alerts_center.php"><i class="dot"></i>Alerts</a><a href="insights_center.php"><i class="dot"></i>Insights</a><a href="data_management.php"><i class="dot"></i>Data Management</a></nav><div class="os-sidebar-status"><b>Personal shortcuts</b><span>Save recurring Business OS pages/filters without changing business data.</span></div></aside><main class="os-main">
<section class="os-hero s10-hero"><div class="os-kicker">Step 10V • Saved Views & Favorites</div><h1>Save recurring workspaces instead of rebuilding the same filters every day.</h1><p>A saved view stores only an internal Business OS target page and query string. It does not duplicate or modify business facts.</p><div class="os-status-row"><span class="os-chip <?= $error===null?'good':'' ?>"><?= $error===null?'SAVED VIEWS LIVE':'Review required' ?></span><span class="os-chip"><?= number_format(count($views)) ?> favorites</span></div></section>
<?php if($success):?><div class="s10-alert good"><?= step10_h($success) ?></div><?php endif;?><?php if($error):?><div class="s10-alert bad"><strong>Saved View diagnostic:</strong> <?= step10_h($error) ?></div><?php else:?>
<section class="s10-grid"><aside class="s10-card s10-span-4"><h2>Save a View</h2><p>Example query: <code>year=2026&amp;month=8</code></p><form class="s10-form-grid" method="post"><input type="hidden" name="csrf" value="<?= step10_h($csrf) ?>"><input type="hidden" name="action" value="save"><div class="s10-field full"><label>Name</label><input name="view_name" maxlength="120" required placeholder="August Operations"></div><div class="s10-field full"><label>Workspace</label><select name="target_page"><?php foreach($targets as $file=>$label):?><option value="<?= step10_h($file) ?>"><?= step10_h($label) ?></option><?php endforeach;?></select></div><div class="s10-field full"><label>Query string (optional)</label><input name="query_string" maxlength="1000" placeholder="year=2026&month=8"></div><div class="s10-field full"><button class="os-btn primary" type="submit">Save Favorite</button></div></form></aside>
<article class="s10-card s10-span-8"><h2>Favorite Workspaces</h2><p>Open a saved internal route with one click.</p><div class="s10-list"><?php if(!$views):?><div class="s10-row"><div><b>No saved views yet</b><small>Create your first recurring workspace shortcut.</small></div></div><?php endif;?><?php foreach($views as $v):$url=(string)$v['target_page'].($v['query_string']?'?'.(string)$v['query_string']:'');?><div class="s10-row"><div><b><?= step10_h($v['view_name']) ?></b><small><?= step10_h($url) ?></small></div><div class="s10-actions"><a class="primary" href="<?= step10_h($url) ?>">Open →</a><form method="post"><input type="hidden" name="csrf" value="<?= step10_h($csrf) ?>"><input type="hidden" name="action" value="delete"><input type="hidden" name="view_id" value="<?= (int)$v['id'] ?>"><button class="danger" type="submit">Remove</button></form></div></div><?php endforeach;?></div></article></section>
<?php endif;?></main></div><script src="assets/business-collapsible.js?v=20260820-1" defer></script></body></html>
