<?php
declare(strict_types=1);
require_once __DIR__.'/config/bi_step22.php';
require_once __DIR__.'/config/backup_step18.php';
require_once __DIR__.'/config/deployment_step19.php';
$error=null;$checks=[];$m=[];
function d22add(array &$a,string $n,bool $ok,string $d):void{$a[]=['name'=>$n,'ok'=>$ok,'detail'=>$d];}
try{
    $pdo=business_db();bi_step22_ensure($pdo);backup_step18_ensure($pdo);deployment_step19_ensure($pdo);$user=bi_step22_guard($pdo,'bi.view');$ctx=bi_step22_context($pdo);$orgId=(int)$ctx['organization_id'];$p=bi_step22_period();$metrics=bi_step22_metrics($pdo,$orgId,$p['start'],$p['end']);
    $scalar=function(string $sql,array $args=[])use($pdo):int{$s=$pdo->prepare($sql);$s->execute($args);return(int)$s->fetchColumn();};
    $s=$pdo->prepare("SELECT COUNT(*) total_rows,SUM(mapping_status='mapped') mapped_rows,SUM(mapping_status='pending') pending_rows FROM raw_source_records WHERE organization_id=? AND source_dataset IN ('New UMS','Volume Points','First & Second Set','Active UMS Month_Wise','Renewal UMS','Monthely_Income','Royalty_Tracking','Extra Order for Customer')");$s->execute([$orgId]);$legacy=$s->fetch()?:[];$m['legacy']=(int)($legacy['mapped_rows']??0);$m['legacy_total']=(int)($legacy['total_rows']??0);$m['legacy_pending']=(int)($legacy['pending_rows']??0);$m['products']=$scalar("SELECT COUNT(*) FROM products WHERE organization_id=? AND status='active'",[$orgId]);
    $biTables=true;foreach(bi_step22_tables() as $t)if(!business_table_exists($pdo,$t)){$biTables=false;break;}$secTables=true;foreach(security_step17_tables() as $t)if(!business_table_exists($pdo,$t)){$secTables=false;break;}$finTables=true;foreach(finance_step16_tables() as $t)if(!business_table_exists($pdo,$t)){$finTables=false;break;}$backupTables=true;foreach(backup_step18_support_tables() as $t)if(!business_table_exists($pdo,$t)){$backupTables=false;break;}$deployTables=true;foreach(deployment_step19_support_tables() as $t)if(!business_table_exists($pdo,$t)){$deployTables=false;break;}$leadTables=true;foreach(lead_step20_tables() as $t)if(!business_table_exists($pdo,$t)){$leadTables=false;break;}$commTables=true;foreach(comm_step21_tables() as $t)if(!business_table_exists($pdo,$t)){$commTables=false;break;}
    $perm=0;$adminPerm=0;foreach(['bi.view','bi.manage','bi.export'] as $pc){$perm+=$scalar("SELECT COUNT(*) FROM security_permissions WHERE permission_code=? AND is_active=1",[$pc]);$adminPerm+=$scalar("SELECT COUNT(*) FROM security_role_permissions WHERE organization_id=? AND role_code='admin' AND permission_code=? AND is_allowed=1",[$orgId,$pc]);}
    $invalidTargets=$scalar("SELECT COUNT(*) FROM bi_targets WHERE organization_id=? AND (period_end<period_start OR target_value<0 OR unit_code NOT IN ('currency','vp','count','percent','number') OR direction_code NOT IN ('higher_better','lower_better') OR status NOT IN ('active','archived'))",[$orgId]);
    $invalidSignals=$scalar("SELECT COUNT(*) FROM bi_signal_actions WHERE organization_id=? AND signal_status NOT IN ('acknowledged','resolved')",[$orgId]);$invalidNotes=$scalar("SELECT COUNT(*) FROM bi_executive_notes WHERE organization_id=? AND (title='' OR note_text='' OR status NOT IN ('active','archived'))",[$orgId]);
    $service=(string)file_get_contents(__DIR__.'/config/bi_step22.php');$migration=(string)file_get_contents(dirname(__DIR__).'/database/migrations/018_step22_executive_bi.sql');$index=(string)file_get_contents(__DIR__.'/index.php');$dashboard=(string)file_get_contents(__DIR__.'/dashboard_step22.php');$export=(string)file_get_contents(__DIR__.'/bi_export.php');
    $profitTruth=str_contains($service,"cost_status='complete'")&&str_contains($service,'profit_total');$inventoryTruth=str_contains($service,'unit_cost IS NOT NULL')&&str_contains($service,'inventory_value_known');$exposureTruth=str_contains($service,'sales_fulfillment_ledger')&&str_contains($service,'GREATEST(total_amount-return_credit-paid_amount,0)');$financeTruth=str_contains($service,'finance_journal_lines')&&str_contains($service,"account_class='income'")&&str_contains($service,"account_class='expense'");$leadTruth=str_contains($service,'crm_lead_conversions')&&str_contains($service,'converted_at');$trendTruth=str_contains($service,'bi_step22_monthly_trends')&&count(bi_step22_monthly_trends($pdo,$orgId,6))===6;$funnel=bi_step22_funnel($pdo,$orgId,$p['start'],$p['end']);$funnelTruth=isset($funnel['submissions'],$funnel['leads'],$funnel['converted']);$signalTruth=str_contains($service,'overdue_supplier_bills')&&str_contains($service,'out_of_stock')&&str_contains($service,'profit_deferred_sales')&&str_contains($service,'failed_outbox');$targetTruth=count(bi_step22_metric_catalog())>=12&&str_contains($service,'higher_better')&&str_contains($service,'lower_better');$noSnapshot=!str_contains(strtolower($migration),'snapshot_fact')&&!str_contains(strtolower($migration),'fact_snapshot');$noFakeTarget=!preg_match('/INSERT\s+INTO\s+bi_targets/i',$migration);$exportTruth=str_contains($export,'text/csv')&&str_contains($export,'Print / Save PDF')&&str_contains($export,'bi_step22_log_export');$indexTruth=str_contains($index,'dashboard_step22.php');$dashboardTruth=str_contains($dashboard,"security_step17_has_permission(\$pdo,'bi.view'")&&str_contains($dashboard,'Executive BI & Advanced Analytics');
    $required=['executive_bi.php','bi_targets.php','bi_trends.php','bi_funnel.php','bi_profitability.php','bi_exposure.php','bi_action_center.php','bi_export.php','step22_audit.php','dashboard_step22.php','config/bi_step22.php','assets/bi_step22.css'];$files=true;foreach($required as $f)if(!is_file(__DIR__.'/'.$f)){$files=false;break;}
    $guardFiles=['executive_bi.php'=>'bi.view','bi_targets.php'=>'bi.view','bi_trends.php'=>'bi.view','bi_funnel.php'=>'bi.view','bi_profitability.php'=>'bi.view','bi_exposure.php'=>'bi.view','bi_action_center.php'=>'bi.view','bi_export.php'=>'bi.export','step22_audit.php'=>'bi.view'];$guards=true;foreach($guardFiles as $f=>$pc){$txt=(string)file_get_contents(__DIR__.'/'.$f);if(!str_contains($txt,"bi_step22_guard(\$pdo,'$pc'")){$guards=false;break;}}
    $metricKeys=['sales_revenue','verified_profit','collections','purchase_spend','new_leads','lead_conversions','customer_receivable','supplier_payable','inventory_value_known','finance_net'];$metricShape=true;foreach($metricKeys as $k)if(!array_key_exists($k,$metrics)){$metricShape=false;break;}
    $targetRows=$scalar("SELECT COUNT(*) FROM bi_targets WHERE organization_id=?",[$orgId]);$signalRows=$scalar("SELECT COUNT(*) FROM bi_signal_actions WHERE organization_id=?",[$orgId]);$notes=$scalar("SELECT COUNT(*) FROM bi_executive_notes WHERE organization_id=?",[$orgId]);$exports=$scalar("SELECT COUNT(*) FROM bi_export_runs WHERE organization_id=?",[$orgId]);

    d22add($checks,'Legacy workbook preserved',$m['legacy_total']===757&&$m['legacy']===757&&$m['legacy_pending']===0,$m['legacy'].' / 757 mapped • '.$m['legacy_pending'].' pending');
    d22add($checks,'STEP 11 catalog preserved',$m['products']===64,$m['products'].' / 64 active products');
    d22add($checks,'STEP 16 Finance preserved',$finTables,count(finance_step16_tables()).' finance tables');
    d22add($checks,'STEP 17 Security preserved',$secTables,count(security_step17_tables()).' security tables');
    d22add($checks,'STEP 18 Recovery preserved',$backupTables,count(backup_step18_support_tables()).' recovery tables');
    d22add($checks,'STEP 19 Deployment preserved',$deployTables,count(deployment_step19_support_tables()).' deployment tables');
    d22add($checks,'STEP 20 Lead CRM preserved',$leadTables,count(lead_step20_tables()).' lead tables');
    d22add($checks,'STEP 21 Communications preserved',$commTables,count(comm_step21_tables()).' communication tables');
    d22add($checks,'STEP 22 management tables',$biTables,count(bi_step22_tables()).' BI management tables');
    d22add($checks,'Executive BI permission catalog',$perm===3,$perm.' / 3 permissions');
    d22add($checks,'Administrator has full BI access',$adminPerm===3,$adminPerm.' / 3 admin permissions');
    d22add($checks,'BI pages enforce explicit permissions',$guards,'View / Export page guards');
    d22add($checks,'Live KPI result shape',$metricShape,count($metricKeys).' core KPI keys');
    d22add($checks,'Sales revenue uses active Product Sales',str_contains($service,"sale_status='active'")&&str_contains($service,'o.net_amount'),'Product Sale ledger + order source');
    d22add($checks,'Verified profit requires complete cost',$profitTruth,'cost_status=complete only');
    d22add($checks,'Deferred-cost sales remain visible',array_key_exists('profit_deferred_sales',$metrics)&&str_contains($service,'deferred_sales'),'not silently counted as profit');
    d22add($checks,'Inventory valuation requires actual unit cost',$inventoryTruth,'unit_cost IS NOT NULL');
    d22add($checks,'Customer/Supplier exposure uses operational ledgers',$exposureTruth,'fulfillment receivable + purchase bill payable');
    d22add($checks,'Finance KPI uses double-entry ledger',$financeTruth,'posted journal lines by account class');
    d22add($checks,'Lead conversion uses conversion evidence',$leadTruth,'crm_lead_conversions.converted_at');
    d22add($checks,'Monthly trend engine is live',$trendTruth,'6-month live calculation returned');
    d22add($checks,'Lead funnel engine is available',$funnelTruth,'submissions → leads → converted');
    d22add($checks,'Top Product analytics engine exists',str_contains($service,'function bi_step22_top_products'),'revenue / VP / verified profit');
    d22add($checks,'Top Customer analytics engine exists',str_contains($service,'function bi_step22_top_customers'),'orders / revenue / receivable');
    d22add($checks,'Top Supplier analytics engine exists',str_contains($service,'function bi_step22_top_suppliers'),'billed / paid / outstanding');
    d22add($checks,'Management target catalog is explicit',$targetTruth,count(bi_step22_metric_catalog()).' supported target metrics');
    d22add($checks,'Target records are structurally valid',$invalidTargets===0,$invalidTargets.' invalid target(s)');
    d22add($checks,'No default/fake target is seeded',$noFakeTarget,$targetRows.' explicit target(s) currently stored');
    d22add($checks,'Action signals are source-backed',$signalTruth,'receivable • payable • stock • cost • follow-up • communication');
    d22add($checks,'Signal workflow records are valid',$invalidSignals===0,$invalidSignals.' invalid signal action(s)');
    d22add($checks,'Executive notes are separate from source facts',$invalidNotes===0,$notes.' management note(s)');
    d22add($checks,'BI does not create a duplicate fact snapshot warehouse',$noSnapshot,'operational tables remain source of truth');
    d22add($checks,'BI CSV/Print export is ready',$exportTruth,$exports.' recorded export run(s)');
    d22add($checks,'Business OS routes through STEP 22 dashboard',$indexTruth,'dashboard_step22.php active');
    d22add($checks,'Dashboard hides BI from unauthorized roles',$dashboardTruth,'bi.view permission-aware rendering');
    d22add($checks,'STEP 22 production workspaces',$files,count($required).' required files');
}catch(Throwable $e){$error=$e->getMessage();}
$passed=count(array_filter($checks,static fn($c)=>$c['ok']));$failed=count($checks)-$passed;$complete=$error===null&&$failed===0;
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>STEP 22 Audit - Healthcare Wellness Club</title><link rel="stylesheet" href="assets/dashboard.css"><link rel="stylesheet" href="assets/product_pro.css"><link rel="stylesheet" href="assets/bi_step22.css"></head><body><header class="os-topbar"><div class="os-topbar-inner"><a class="os-brand" href="index.php"><img src="../img/logo.png"><span><strong>Healthcare Wellness Club</strong><small>STEP 22 • Final Executive BI Audit</small></span></a><div class="os-top-actions"><a class="os-btn" href="executive_bi.php">Executive BI</a><a class="os-btn primary" href="index.php">Dashboard</a></div></div></header><main class="os-main" style="max-width:1450px;margin:auto"><section class="os-hero pp-hero"><div class="os-kicker">STEP 22Z • FINAL BI AUDIT</div><h1><?=$complete?'STEP 22 COMPLETE':'STEP 22 needs review'?></h1><p>Verifies cross-module KPI truth, cost boundaries, target integrity, action workflow, permissions and preservation of the previous Business OS.</p><div class="os-status-row"><span class="os-chip <?=$complete?'good':''?>"><?=$complete?'STEP 22 COMPLETE':'REVIEW REQUIRED'?></span><span class="os-chip good"><?=($m['legacy']??0)?> / 757 legacy</span><span class="os-chip good"><?=($m['products']??0)?> / 64 products</span><span class="os-chip"><?=$passed?> PASS / <?=$failed?> REVIEW</span></div></section><?php if($error):?><div class="pp-alert bad"><strong>Audit diagnostic:</strong> <?=bi_step22_h($error)?></div><?php endif;?><section class="os-card" style="margin-top:14px"><div class="os-title-row"><div><h2>Completion Checks</h2><p>Zero sales, targets or BI notes is a valid starting state. No fake management data is required.</p></div><span class="pp-badge <?=$failed?'warn':''?>"><?=$passed?> PASS / <?=$failed?> REVIEW</span></div><div class="pp-grid"><?php foreach($checks as $c):?><div class="pp-source pp-span-6"><div><b><?=bi_step22_h($c['name'])?></b><small><?=bi_step22_h($c['detail'])?></small></div><span class="pp-badge <?=$c['ok']?'':'warn'?>"><?=$c['ok']?'PASS':'REVIEW'?></span></div><?php endforeach;?></div></section><div class="os-footer-note"><strong>STEP 22 boundary:</strong> Executive BI derives management visibility from live operational sources. It does not invent targets, predict outcomes, estimate missing costs or rewrite operational facts.</div></main></body></html>