<?php
declare(strict_types=1);
require_once __DIR__ . '/config/inventory_step13.php';
$error=null;$checks=[];$metrics=[];
function i13add(array &$checks,string $name,bool $ok,string $detail):void{$checks[]=['name'=>$name,'ok'=>$ok,'detail'=>$detail];}
try{
 $pdo=business_db();inventory_step13_ensure($pdo);$ctx=inventory_step13_context($pdo);$orgId=(int)$ctx['organization_id'];$locationId=(int)$ctx['location_id'];$scalar=function(string $sql,array $args=[])use($pdo):int{$s=$pdo->prepare($sql);$s->execute($args);return(int)$s->fetchColumn();};
 $state=$pdo->prepare("SELECT COUNT(*) total_rows,SUM(mapping_status='mapped') mapped_rows,SUM(mapping_status='pending') pending_rows FROM raw_source_records WHERE organization_id=? AND source_dataset IN ('New UMS','Volume Points','First & Second Set','Active UMS Month_Wise','Renewal UMS','Monthely_Income','Royalty_Tracking','Extra Order for Customer')");$state->execute([$orgId]);$legacy=$state->fetch()?:[];$metrics['legacy_total']=(int)($legacy['total_rows']??0);$metrics['legacy_mapped']=(int)($legacy['mapped_rows']??0);$metrics['legacy_pending']=(int)($legacy['pending_rows']??0);
 $metrics['products']=$scalar("SELECT COUNT(*) FROM products WHERE organization_id=? AND status='active'",[$orgId]);$metrics['listings']=$scalar("SELECT COUNT(*) FROM product_market_listings WHERE organization_id=? AND status='active'",[$orgId]);$metrics['settings']=$scalar("SELECT COUNT(*) FROM inventory_product_settings WHERE organization_id=? AND location_id=?",[$orgId,$locationId]);$metrics['batches']=$scalar("SELECT COUNT(*) FROM inventory_batches WHERE organization_id=? AND location_id=?",[$orgId,$locationId]);$metrics['transactions']=$scalar("SELECT COUNT(*) FROM inventory_transactions WHERE organization_id=? AND location_id=?",[$orgId,$locationId]);$metrics['counts']=$scalar("SELECT COUNT(*) FROM inventory_stock_counts WHERE organization_id=? AND location_id=?",[$orgId,$locationId]);
 $tablesOk=true;foreach(inventory_step13_tables() as $t)if(!business_table_exists($pdo,$t)){$tablesOk=false;break;}
 $locationReady=$scalar("SELECT COUNT(*) FROM inventory_locations WHERE organization_id=? AND id=? AND location_code='MAIN' AND status='active'",[$orgId,$locationId])===1;
 $sourceReady=$scalar("SELECT COUNT(*) FROM data_sources WHERE organization_id=? AND source_code='INVENTORY' AND is_active=1",[$orgId])===1;inventory_step13_source($pdo,$orgId);$sourceReady=$scalar("SELECT COUNT(*) FROM data_sources WHERE organization_id=? AND source_code='INVENTORY' AND is_active=1",[$orgId])===1;
 $badNegative=$scalar("SELECT COUNT(*) FROM inventory_batches b JOIN inventory_product_settings s ON s.organization_id=b.organization_id AND s.location_id=b.location_id AND s.listing_id=b.listing_id WHERE b.organization_id=? AND b.location_id=? AND s.allow_negative=0 AND b.current_quantity<-0.0005",[$orgId,$locationId]);
 $badBalance=$scalar("SELECT COUNT(*) FROM inventory_batches b LEFT JOIN (SELECT batch_id,SUM(CASE WHEN status='active' THEN quantity_delta ELSE 0 END) ledger_qty FROM inventory_transactions WHERE organization_id=? GROUP BY batch_id) x ON x.batch_id=b.id WHERE b.organization_id=? AND b.location_id=? AND ABS(b.current_quantity-COALESCE(x.ledger_qty,0))>0.0005",[$orgId,$orgId,$locationId]);
 $expiredAllocated=$scalar("SELECT COUNT(*) FROM inventory_sale_allocations a JOIN inventory_batches b ON b.id=a.batch_id JOIN orders o ON o.id=a.order_id AND o.organization_id=a.organization_id WHERE a.organization_id=? AND a.status='active' AND b.expiry_date IS NOT NULL AND b.expiry_date<o.order_date",[$orgId]);
 $cancelledAllocated=$scalar("SELECT COUNT(*) FROM inventory_sale_allocations a JOIN product_sale_ledger l ON l.organization_id=a.organization_id AND l.order_id=a.order_id WHERE a.organization_id=? AND a.status='active' AND l.sale_status='cancelled'",[$orgId]);
 $badActiveAlloc=$scalar("SELECT COUNT(*) FROM product_order_items i JOIN orders o ON o.id=i.order_id AND o.organization_id=i.organization_id JOIN product_sale_ledger l ON l.order_id=o.id AND l.organization_id=o.organization_id JOIN inventory_product_settings s ON s.organization_id=i.organization_id AND s.location_id=? AND s.listing_id=i.listing_id AND s.track_stock=1 LEFT JOIN (SELECT organization_id,order_item_id,SUM(quantity) qty FROM inventory_sale_allocations WHERE status='active' GROUP BY organization_id,order_item_id) a ON a.organization_id=i.organization_id AND a.order_item_id=i.id WHERE i.organization_id=? AND l.sale_status='active' AND o.created_at>=COALESCE((SELECT meta_value FROM schema_meta WHERE meta_key='inventory_step13_activated_at' LIMIT 1),'9999-12-31') AND ABS(COALESCE(a.qty,0)-i.quantity)>0.0005",[$locationId,$orgId]);
 $pending=count(inventory_step13_pending_sales($pdo,$orgId));
 $badRaw=$scalar("SELECT COUNT(*) FROM inventory_transactions t LEFT JOIN raw_source_records r ON r.id=t.raw_source_id LEFT JOIN data_sources ds ON ds.id=r.data_source_id WHERE t.organization_id=? AND t.raw_source_id IS NOT NULL AND (r.id IS NULL OR ds.source_code<>'INVENTORY')",[$orgId]);
 $badCountMath=$scalar("SELECT COUNT(*) FROM inventory_stock_count_lines l JOIN inventory_stock_counts c ON c.id=l.stock_count_id WHERE c.organization_id=? AND ABS(l.variance_quantity-(l.counted_quantity-l.system_quantity))>0.0005",[$orgId]);
 $badSaleTx=$scalar("SELECT COUNT(*) FROM inventory_sale_allocations a JOIN inventory_transactions t ON t.id=a.inventory_transaction_id WHERE a.organization_id=? AND (t.movement_type<>'sale' OR t.quantity_delta>=0 OR ABS(ABS(t.quantity_delta)-a.quantity)>0.0005)",[$orgId]);
 $badExpiredSellable=$scalar("SELECT COUNT(*) FROM inventory_batches WHERE organization_id=? AND location_id=? AND expiry_date<CURDATE() AND current_quantity>0 AND status<>'active'",[$orgId,$locationId]);
 $tracked=$scalar("SELECT COUNT(*) FROM inventory_product_settings WHERE organization_id=? AND location_id=? AND track_stock=1",[$orgId,$locationId]);
 $requiredFiles=['inventory_center.php','inventory_inward.php','inventory_adjustments.php','inventory_stocktake.php','inventory_settings.php','inventory_sales_sync.php','inventory_analytics.php','inventory_export.php','config/inventory_step13.php'];$filesOk=true;foreach($requiredFiles as $f)if(!is_file(__DIR__.'/'.$f)){$filesOk=false;break;}
 i13add($checks,'Legacy workbook preserved',$metrics['legacy_total']===757&&$metrics['legacy_mapped']===757&&$metrics['legacy_pending']===0,$metrics['legacy_mapped'].' / 757 mapped • '.$metrics['legacy_pending'].' pending');
 i13add($checks,'STEP 13 inventory tables',$tablesOk,count(inventory_step13_tables()).' required tables');
 i13add($checks,'Main stock location',$locationReady,'MAIN location ready');
 i13add($checks,'Inventory source trace',$sourceReady,'Dedicated INVENTORY raw source');
 i13add($checks,'Catalog settings synchronized',$metrics['settings']===$metrics['listings'],$metrics['settings'].' settings / '.$metrics['listings'].' active listings');
 i13add($checks,'Tracked product coverage',$tracked===$metrics['settings'],$tracked.' tracked / '.$metrics['settings'].' configured');
 i13add($checks,'No unauthorized negative stock',$badNegative===0,$badNegative.' negative batch issue(s)');
 i13add($checks,'Batch balance equals ledger',$badBalance===0,$metrics['batches'].' batches • '.$badBalance.' balance issue(s)');
 i13add($checks,'Expired batches never allocated',$expiredAllocated===0,$expiredAllocated.' expired allocation(s)');
 i13add($checks,'Cancelled sales are restocked',$cancelledAllocated===0,$cancelledAllocated.' active allocation(s) on cancelled sales');
 i13add($checks,'Active STEP 13 sales fully allocated',$badActiveAlloc===0,$badActiveAlloc.' incomplete item allocation(s)');
 i13add($checks,'Sale stock sync queue clear',$pending===0,$pending.' post-activation sale(s) pending');
 i13add($checks,'Inventory transaction raw trace',$badRaw===0,$badRaw.' source isolation issue(s)');
 i13add($checks,'Sale allocation transaction integrity',$badSaleTx===0,$badSaleTx.' sale allocation issue(s)');
 i13add($checks,'Physical count variance math',$badCountMath===0,$metrics['counts'].' stock counts • '.$badCountMath.' variance issue(s)');
 i13add($checks,'Expired stock remains visible',$badExpiredSellable===0,'Expired quantity is retained in active batches for quarantine visibility');
 i13add($checks,'STEP 13 workspaces',$filesOk,count($requiredFiles).' required workspaces/services');
}catch(Throwable $e){$error=$e->getMessage();}
$passed=count(array_filter($checks,static fn($c)=>$c['ok']));$failed=count($checks)-$passed;$complete=$error===null&&$failed===0;
function au_h(mixed $v):string{return htmlspecialchars((string)$v,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8');}
?>
<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>STEP 13 Audit - Healthcare Wellness Club</title><link rel="stylesheet" href="assets/dashboard.css"><link rel="stylesheet" href="assets/product_pro.css"></head><body>
<header class="os-topbar"><div class="os-topbar-inner"><a class="os-brand" href="index.php"><img src="../img/logo.png" alt="logo"><span><strong>Healthcare Wellness Club</strong><small>STEP 13 • Final Inventory Audit</small></span></a><div class="os-top-actions"><a class="os-btn" href="inventory_center.php">Inventory</a><a class="os-btn" href="inventory_analytics.php">Analytics</a><a class="os-btn primary" href="index.php">Dashboard</a></div></div></header>
<div class="os-layout"><aside class="os-sidebar"><div class="os-nav-label">Completion</div><nav class="os-nav"><a href="inventory_center.php"><i class="dot"></i>Inventory Center</a><a href="inventory_inward.php"><i class="dot"></i>Stock Inward</a><a href="inventory_stocktake.php"><i class="dot"></i>Stocktake</a><a href="inventory_analytics.php"><i class="dot"></i>Analytics</a><a class="active" href="step13_audit.php"><i class="dot"></i>STEP 13 Audit</a></nav><div class="os-sidebar-status"><b><?= $complete?'STEP 13 complete':'Completion review' ?></b><span><?= $passed ?> pass • <?= $failed ?> review.</span></div></aside>
<main class="os-main"><section class="os-hero pp-hero"><div class="os-kicker">STEP 13Z • FINAL INVENTORY AUDIT</div><h1><?= $complete?'STEP 13 COMPLETE':'STEP 13 needs review' ?></h1><p>This audit verifies catalog coverage, stock ledger balance, sale FEFO allocation, expiry safety, cancellation restock, post-activation synchronization, physical-count math and legacy-data preservation.</p><div class="os-status-row"><span class="os-chip <?= $complete?'good':'' ?>"><?= $complete?'STEP 13 COMPLETE':'Review required' ?></span><span class="os-chip good"><?= number_format($metrics['legacy_mapped']??0) ?> / 757 legacy</span><span class="os-chip"><?= number_format($metrics['settings']??0) ?> product settings</span><span class="os-chip"><?= number_format($metrics['batches']??0) ?> batches</span><span class="os-chip"><?= number_format($metrics['transactions']??0) ?> movements</span></div></section>
<?php if($error):?><div class="pp-alert bad"><strong>Audit diagnostic:</strong> <?= au_h($error) ?></div><?php endif;?>
<section class="os-card" style="margin-top:14px"><div class="os-title-row"><div><h2>Completion Checks</h2><p>No fake opening stock is required. Zero batches and zero movements are valid until real stock is entered.</p></div><span class="pp-badge <?= $complete?'':'warn' ?>"><?= $passed ?> PASS / <?= $failed ?> REVIEW</span></div><div class="pp-audit-grid"><?php foreach($checks as $c):?><div class="pp-audit"><div><b><?= au_h($c['name']) ?></b><span><?= au_h($c['detail']) ?></span></div><strong class="<?= $c['ok']?'':'bad' ?>"><?= $c['ok']?'PASS':'REVIEW' ?></strong></div><?php endforeach;?></div></section>
<div class="os-footer-note"><strong>STEP 13 completion rule:</strong> stock quantity and valuation are never invented. The system can be complete with zero real stock; real opening/purchase quantities are entered only when you have actual stock evidence.</div></main></div><script src="assets/business-collapsible.js?v=20260820-1" defer></script></body></html>
