<?php
declare(strict_types=1);require_once __DIR__ . '/config/product_step12_bridge.php';
$error=null;$checks=[];$metrics=[];function s12add(array &$a,string $name,bool $ok,string $detail):void{$a[]=['name'=>$name,'ok'=>$ok,'detail'=>$detail];}
try{
 $pdo=business_db();product_step12_ensure($pdo);product_step12_bridge_backfill($pdo);$ctx=product_step12_context($pdo);$orgId=(int)$ctx['organization_id'];$clubId=(int)$ctx['club_id'];product_step12_source($pdo,$orgId);
 $scalar=function(string $sql,array $args=[])use($pdo):int{$s=$pdo->prepare($sql);$s->execute($args);return(int)$s->fetchColumn();};
 $state=$pdo->prepare("SELECT COUNT(*) total_rows,SUM(mapping_status='mapped') mapped_rows,SUM(mapping_status='pending') pending_rows FROM raw_source_records WHERE organization_id=? AND source_dataset IN ('New UMS','Volume Points','First & Second Set','Active UMS Month_Wise','Renewal UMS','Monthely_Income','Royalty_Tracking','Extra Order for Customer')");$state->execute([$orgId]);$legacy=$state->fetch()?:[];
 $metrics['legacy_total']=(int)($legacy['total_rows']??0);$metrics['legacy_mapped']=(int)($legacy['mapped_rows']??0);$metrics['legacy_pending']=(int)($legacy['pending_rows']??0);
 $metrics['products']=$scalar("SELECT COUNT(*) FROM products WHERE organization_id=?",[$orgId]);
 $market=product_step11_market($pdo,$orgId);$marketId=(int)$market['id'];$metrics['tiers']=$scalar("SELECT COUNT(*) FROM product_discount_tiers WHERE organization_id=? AND market_id=? AND status='active'",[$orgId,$marketId]);
 $metrics['sale_orders']=$scalar("SELECT COUNT(*) FROM orders WHERE organization_id=? AND order_type='product_sale'",[$orgId]);
 $metrics['ledgers']=$scalar("SELECT COUNT(*) FROM product_sale_ledger WHERE organization_id=?",[$orgId]);
 $metrics['active']=$scalar("SELECT COUNT(*) FROM product_sale_ledger WHERE organization_id=? AND sale_status='active'",[$orgId]);
 $metrics['cancelled']=$scalar("SELECT COUNT(*) FROM product_sale_ledger WHERE organization_id=? AND sale_status='cancelled'",[$orgId]);
 $metrics['payments']=$scalar("SELECT COUNT(*) FROM product_sale_payments WHERE organization_id=?",[$orgId]);
 $metrics['costs']=$scalar("SELECT COUNT(*) FROM product_cost_versions WHERE organization_id=? AND status='active'",[$orgId]);
 $metrics['profit_complete']=$scalar("SELECT COUNT(*) FROM product_sale_ledger WHERE organization_id=? AND sale_status='active' AND cost_status='complete'",[$orgId]);
 $metrics['profit_deferred']=$scalar("SELECT COUNT(*) FROM product_sale_ledger WHERE organization_id=? AND sale_status='active' AND cost_status<>'complete'",[$orgId]);
 $sourceCode=$pdo->prepare("SELECT COUNT(*) FROM data_sources WHERE organization_id=? AND source_code='PRODUCT-SALES' AND is_active=1");$sourceCode->execute([$orgId]);$sourceReady=(int)$sourceCode->fetchColumn()===1;
 $missingLedger=$scalar("SELECT COUNT(*) FROM orders o LEFT JOIN product_sale_ledger l ON l.organization_id=o.organization_id AND l.order_id=o.id WHERE o.organization_id=? AND o.order_type='product_sale' AND l.id IS NULL",[$orgId]);
 $missingLink=$scalar("SELECT COUNT(*) FROM orders o LEFT JOIN product_quote_order_links ql ON ql.organization_id=o.organization_id AND ql.order_id=o.id WHERE o.organization_id=? AND o.order_type='product_sale' AND ql.id IS NULL",[$orgId]);
 $missingItems=$scalar("SELECT COUNT(*) FROM orders o WHERE o.organization_id=? AND o.order_type='product_sale' AND NOT EXISTS(SELECT 1 FROM product_order_items i WHERE i.organization_id=o.organization_id AND i.order_id=o.id)",[$orgId]);
 $badBridge=$scalar("SELECT COUNT(*) FROM product_sale_ledger l JOIN orders o ON o.id=l.order_id AND o.organization_id=l.organization_id LEFT JOIN volume_point_entries v ON v.organization_id=o.organization_id AND v.source_key=CONCAT('product-sale-vp:',o.id) WHERE l.organization_id=? AND l.sale_status='active' AND (v.id IS NULL OR v.source_sheet<>'Manual Entry' OR ABS(v.volume_points-o.volume_points)>0.0005)",[$orgId]);
 $badBridgeSource=$scalar("SELECT COUNT(*) FROM volume_point_entries v JOIN raw_source_records r ON r.id=v.source_record_id JOIN data_sources ds ON ds.id=r.data_source_id WHERE v.organization_id=? AND v.source_key LIKE 'product-sale-vp:%' AND ds.source_code<>'PRODUCT-SALES'",[$orgId]);
 $badCancelled=$scalar("SELECT COUNT(*) FROM product_sale_ledger l JOIN orders o ON o.id=l.order_id AND o.organization_id=l.organization_id LEFT JOIN volume_point_entries v ON v.organization_id=o.organization_id AND v.source_key=CONCAT('product-sale-vp:',o.id) WHERE l.organization_id=? AND l.sale_status='cancelled' AND (o.source_sheet<>? OR ABS(o.gross_amount)>0.005 OR ABS(o.discount_amount)>0.005 OR ABS(o.net_amount)>0.005 OR ABS(o.profit_amount)>0.005 OR ABS(o.volume_points)>0.0005 OR (v.id IS NOT NULL AND (v.source_sheet='Manual Entry' OR ABS(v.volume_points)>0.0005)))",[$orgId,PRODUCT_SALE_REVERSED_SOURCE_SHEET]);
 $badPayments=$scalar("SELECT COUNT(*) FROM product_sale_ledger l JOIN orders o ON o.id=l.order_id AND o.organization_id=l.organization_id WHERE l.organization_id=? AND l.sale_status='active' AND l.paid_amount>o.net_amount+0.01",[$orgId]);
 $badPaymentState=$scalar("SELECT COUNT(*) FROM product_sale_ledger l JOIN orders o ON o.id=l.order_id AND o.organization_id=l.organization_id WHERE l.organization_id=? AND l.sale_status='active' AND ((l.paid_amount<=0.009 AND l.payment_status<>'unpaid') OR (l.paid_amount>0.009 AND l.paid_amount+0.009<o.net_amount AND l.payment_status<>'partial') OR (l.paid_amount+0.009>=o.net_amount AND o.net_amount>0 AND l.payment_status<>'paid'))",[$orgId]);
 $badProfit=$scalar("SELECT COUNT(*) FROM product_sale_ledger l JOIN orders o ON o.id=l.order_id AND o.organization_id=l.organization_id WHERE l.organization_id=? AND l.sale_status='active' AND ((l.cost_status='complete' AND (l.profit_total IS NULL OR ABS(o.profit_amount-l.profit_total)>0.01)) OR (l.cost_status<>'complete' AND ABS(o.profit_amount)>0.01))",[$orgId]);
 $badCompleteLines=$scalar("SELECT COUNT(*) FROM product_sale_ledger l WHERE l.organization_id=? AND l.sale_status='active' AND l.cost_status='complete' AND EXISTS(SELECT 1 FROM product_order_items i WHERE i.organization_id=l.organization_id AND i.order_id=l.order_id AND (i.cost_version_id IS NULL OR i.unit_cost IS NULL OR i.profit_status<>'explicit_cost'))",[$orgId]);
 $badCostSource=$scalar("SELECT COUNT(*) FROM product_cost_versions WHERE organization_id=? AND status='active' AND (source_reference IS NULL OR TRIM(source_reference)='')",[$orgId]);
 $incomeAuto=$scalar("SELECT COUNT(*) FROM income_entries WHERE organization_id=? AND source_sheet IN ('Product Sale','Product Sale • Reversed')",[$orgId]);
 $dupQuotes=$scalar("SELECT COUNT(*) FROM (SELECT quote_id FROM product_quote_order_links WHERE organization_id=? GROUP BY quote_id HAVING COUNT(*)>1) x",[$orgId]);
 $requiredFiles=['product_sales_center.php','product_sales_center_core.php','product_sale_detail.php','product_cost_center.php','product_payments.php','product_sales_analytics.php','product_sales_export.php','config/product_step12.php','config/product_step12_bridge.php'];$filesOk=true;foreach($requiredFiles as $f)if(!is_file(__DIR__.'/'.$f)){$filesOk=false;break;}
 $tablesOk=true;foreach(product_step12_tables() as $t)if(!business_table_exists($pdo,$t)){$tablesOk=false;break;}
 $colsOk=true;foreach(['cost_version_id','unit_cost','line_cost','line_profit','profit_status'] as $c)if(!business_column_exists($pdo,'product_order_items',$c)){$colsOk=false;break;}
 s12add($checks,'Legacy workbook preserved',$metrics['legacy_total']===757&&$metrics['legacy_mapped']===757&&$metrics['legacy_pending']===0,$metrics['legacy_mapped'].' / 757 mapped • '.$metrics['legacy_pending'].' pending');
 s12add($checks,'STEP 11 catalog still intact',$metrics['products']===64&&$metrics['tiers']===10,$metrics['products'].' products • '.$metrics['tiers'].' exact tiers');
 s12add($checks,'STEP 12 database tables',$tablesOk,count(product_step12_tables()).' / '.count(product_step12_tables()).' required tables');
 s12add($checks,'Product line cost/profit columns',$colsOk,'5 required cost/profit snapshot columns');
 s12add($checks,'PRODUCT-SALES source',$sourceReady,'Dedicated non-MANUAL raw source');
 s12add($checks,'Every Product Sale has ledger',$missingLedger===0,$metrics['sale_orders'].' orders • '.$metrics['ledgers'].' ledgers • '.$missingLedger.' missing');
 s12add($checks,'Every Product Sale has quote link',$missingLink===0,$missingLink.' missing quote links');
 s12add($checks,'Every Product Sale has line snapshots',$missingItems===0,$missingItems.' orders without line items');
 s12add($checks,'Six-report VP bridge',$badBridge===0,$metrics['active'].' active sales • '.$badBridge.' bridge issue(s)');
 s12add($checks,'Report bridge source isolation',$badBridgeSource===0,$badBridgeSource.' bridge rows outside PRODUCT-SALES');
 s12add($checks,'Cancelled sale effect removed',$badCancelled===0,$metrics['cancelled'].' cancelled • '.$badCancelled.' effective-state issue(s)');
 s12add($checks,'Payment cannot exceed active sale',$badPayments===0,$badPayments.' overpayment issue(s)');
 s12add($checks,'Payment status reconciles',$badPaymentState===0,$metrics['payments'].' payment records • '.$badPaymentState.' state issue(s)');
 s12add($checks,'Verified profit integrity',$badProfit===0,$metrics['profit_complete'].' complete • '.$metrics['profit_deferred'].' deferred');
 s12add($checks,'Complete profit has explicit cost lines',$badCompleteLines===0,$badCompleteLines.' incomplete line-cost issue(s)');
 s12add($checks,'Cost source references required',$badCostSource===0,$metrics['costs'].' active cost versions • '.$badCostSource.' missing source');
 s12add($checks,'No duplicate Income auto-posting',$incomeAuto===0,$incomeAuto.' Product Sale income rows');
 s12add($checks,'One quote converts once',$dupQuotes===0,$dupQuotes.' duplicate quote conversion group(s)');
 s12add($checks,'STEP 12 workspaces',$filesOk,count($requiredFiles).' required files');
}catch(Throwable $e){$error=$e->getMessage();}
$passed=count(array_filter($checks,static fn($c)=>$c['ok']));$failed=count($checks)-$passed;$complete=$error===null&&$failed===0;
?>
<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>STEP 12 Audit - Healthcare Wellness Club</title><link rel="stylesheet" href="assets/dashboard.css"><link rel="stylesheet" href="assets/product_pro.css"></head><body>
<header class="os-topbar"><div class="os-topbar-inner"><a class="os-brand" href="index.php"><img src="../img/logo.png" alt="logo"><span><strong>Healthcare Wellness Club</strong><small>STEP 12 • Final Sales Integration Audit</small></span></a><div class="os-top-actions"><a class="os-btn" href="product_sales_center.php">Sales</a><a class="os-btn" href="product_sales_analytics.php">Analytics</a><a class="os-btn primary" href="index.php">Dashboard</a></div></div></header>
<div class="os-layout"><aside class="os-sidebar"><div class="os-nav-label">Completion</div><nav class="os-nav"><a href="product_sales_center.php"><i class="dot"></i>Sales Center</a><a href="product_cost_center.php"><i class="dot"></i>Cost Basis</a><a href="product_payments.php"><i class="dot"></i>Payments</a><a href="product_sales_analytics.php"><i class="dot"></i>Analytics</a><a href="product_sales_export.php"><i class="dot"></i>Export</a><a class="active" href="step12_audit.php"><i class="dot"></i>STEP 12 Audit</a></nav><div class="os-sidebar-status"><b><?= $complete?'STEP 12 complete':'Completion review' ?></b><span><?= $passed ?> pass • <?= $failed ?> review.</span></div></aside>
<main class="os-main"><section class="os-hero pp-hero"><div class="os-kicker">STEP 12Z • FINAL SALES INTEGRATION AUDIT</div><h1><?= $complete?'STEP 12 COMPLETE':'STEP 12 needs review' ?></h1><p>This audit verifies quote-to-order integrity, PRODUCT-SALES source trace, six-report VP bridge, payment reconciliation, explicit-cost profit rules, safe cancellation/restore behavior and legacy workbook preservation.</p><div class="os-status-row"><span class="os-chip <?= $complete?'good':'' ?>"><?= $complete?'STEP 12 COMPLETE':'Review required' ?></span><span class="os-chip good"><?= number_format($metrics['legacy_mapped']??0) ?> / 757 legacy</span><span class="os-chip"><?= number_format($metrics['sale_orders']??0) ?> product sale orders</span><span class="os-chip"><?= number_format($metrics['active']??0) ?> active</span><span class="os-chip"><?= number_format($metrics['cancelled']??0) ?> cancelled</span><span class="os-chip"><?= number_format($metrics['costs']??0) ?> cost versions</span></div></section><?php if($error):?><div class="pp-alert bad"><strong>Audit diagnostic:</strong> <?= product_h($error) ?></div><?php endif;?>
<section class="os-card" style="margin-top:14px"><div class="os-title-row"><div><h2>Completion Checks</h2><p>No fake sale is required. When there are zero real sales, transactional integrity checks pass vacuously while the complete workflow remains ready.</p></div><span class="pp-badge <?= $complete?'':'warn' ?>"><?= $passed ?> PASS / <?= $failed ?> REVIEW</span></div><div class="pp-audit-grid"><?php foreach($checks as $c):?><div class="pp-audit"><div><b><?= product_h($c['name']) ?></b><span><?= product_h($c['detail']) ?></span></div><strong class="<?= $c['ok']?'':'bad' ?>"><?= $c['ok']?'PASS':'REVIEW' ?></strong></div><?php endforeach;?></div></section>
<div class="os-footer-note"><strong>STEP 12 completion rule:</strong> profit may remain Deferred with zero cost versions and still be correct. A sale is allowed to show verified profit only after every product line resolves to an explicit dated cost source.</div></main></div><script src="assets/business-collapsible.js?v=20260820-1" defer></script></body></html>
