<?php
declare(strict_types=1);session_start();require_once __DIR__.'/config/purchase_step14.php';if(empty($_SESSION['sup_csrf']))$_SESSION['sup_csrf']=bin2hex(random_bytes(24));$csrf=(string)$_SESSION['sup_csrf'];$error=null;$success=null;$rows=[];$edit=null;
try{$pdo=business_db();purchase_step14_ensure($pdo);$ctx=purchase_step14_context($pdo);$orgId=(int)$ctx['organization_id'];if($_SERVER['REQUEST_METHOD']==='POST'){if(!hash_equals($csrf,(string)($_POST['csrf']??'')))throw new RuntimeException('Security token mismatch.');$id=purchase_step14_save_supplier($pdo,(int)($_POST['supplier_id']??0),$_POST);$success='Supplier #'.$id.' saved.';}if((int)($_GET['edit']??0)>0)$edit=purchase_step14_supplier($pdo,$orgId,(int)$_GET['edit']);$rows=purchase_step14_suppliers($pdo,$orgId);}catch(Throwable $e){$error=$e->getMessage();}
function sc_h(mixed $v):string{return htmlspecialchars((string)$v,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8');}function sc_m(mixed $v):string{return '₹'.number_format((float)$v,2,'.',',');}
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>Supplier Center - Healthcare Wellness Club</title><link rel="stylesheet" href="assets/dashboard.css"><link rel="stylesheet" href="assets/product_pro.css"></head><body>
<header class="os-topbar"><div class="os-topbar-inner"><a class="os-brand" href="index.php"><img src="../img/logo.png" alt="logo"><span><strong>Healthcare Wellness Club</strong><small>STEP 14 • Supplier Master</small></span></a><div class="os-top-actions"><a class="os-btn" href="purchase_orders.php">Purchase Orders</a><a class="os-btn" href="purchase_bills.php">Bills</a><a class="os-btn primary" href="purchase_center.php">Purchase Center</a></div></div></header>
<div class="os-layout"><aside class="os-sidebar"><div class="os-nav-label">Purchases</div><nav class="os-nav"><a href="purchase_center.php"><i class="dot"></i>Purchase Center</a><a class="active" href="supplier_center.php"><i class="dot"></i>Suppliers</a><a href="purchase_orders.php"><i class="dot"></i>Purchase Orders</a><a href="purchase_bills.php"><i class="dot"></i>Bills / Invoices</a><a href="purchase_receipts.php"><i class="dot"></i>Receipts</a><a href="supplier_payments.php"><i class="dot"></i>Payables</a><a href="purchase_returns.php"><i class="dot"></i>Returns</a><a href="step14_audit.php"><i class="dot"></i>STEP 14 Audit</a></nav></aside><main class="os-main">
<section class="os-hero pp-hero"><div class="os-kicker">STEP 14A • SUPPLIER MASTER</div><h1>Keep every supplier identity, payment term and balance traceable.</h1><p>Supplier records are never merged by name automatically. Bills, receipts, payments and returns all link to the exact supplier ID.</p><div class="os-status-row"><span class="os-chip <?= $error===null?'good':'' ?>"><?= $error===null?'SUPPLIER CENTER LIVE':'Review required' ?></span><span class="os-chip"><?= count($rows) ?> suppliers</span></div></section>
<?php if($error):?><div class="pp-alert bad"><strong>Supplier diagnostic:</strong> <?= sc_h($error) ?></div><?php endif;?><?php if($success):?><div class="pp-alert good"><strong>Saved:</strong> <?= sc_h($success) ?></div><?php endif;?>
<?php if(!$error):?><section class="pp-grid" style="margin-top:14px"><article class="os-card pp-span-4"><h2><?= $edit?'Edit Supplier':'Add Supplier' ?></h2><form method="post" class="pp-form"><input type="hidden" name="csrf" value="<?= sc_h($csrf) ?>"><input type="hidden" name="supplier_id" value="<?= (int)($edit['id']??0) ?>"><label>Supplier Name<input name="supplier_name" required value="<?= sc_h($edit['supplier_name']??'') ?>"></label><label>Supplier Code<input name="supplier_code" value="<?= sc_h($edit['supplier_code']??'') ?>" placeholder="Blank = auto"></label><label>Contact Person<input name="contact_person" value="<?= sc_h($edit['contact_person']??'') ?>"></label><label>Mobile<input name="mobile" value="<?= sc_h($edit['mobile']??'') ?>"></label><label>Email<input type="email" name="email" value="<?= sc_h($edit['email']??'') ?>"></label><label>GSTIN<input name="gstin" value="<?= sc_h($edit['gstin']??'') ?>"></label><label>Payment Terms (days)<input type="number" min="0" name="payment_terms_days" value="<?= (int)($edit['payment_terms_days']??0) ?>"></label><label>Status<select name="status"><option value="active" <?= ($edit['status']??'active')==='active'?'selected':'' ?>>Active</option><option value="inactive" <?= ($edit['status']??'')==='inactive'?'selected':'' ?>>Inactive</option></select></label><label>Address<textarea name="address_text" rows="2"><?= sc_h($edit['address_text']??'') ?></textarea></label><label>Notes<textarea name="notes" rows="2"><?= sc_h($edit['notes']??'') ?></textarea></label><button>Save Supplier →</button></form></article>
<article class="os-card pp-span-8"><div class="os-title-row"><div><h2>Supplier Ledger Overview</h2><p>Billed − Return Credit − Paid = Outstanding.</p></div></div><div class="pp-table-wrap"><table class="pp-table"><thead><tr><th>Supplier</th><th>Contact</th><th>Billed</th><th>Returns</th><th>Paid</th><th>Outstanding</th><th>Status</th><th></th></tr></thead><tbody><?php foreach($rows as $r):?><tr><td><b><?= sc_h($r['supplier_name']) ?></b><small><?= sc_h($r['supplier_code']) ?><?= $r['gstin']?' • '.$r['gstin']:'' ?></small></td><td><?= sc_h($r['mobile']?:$r['email']?:'—') ?></td><td><?= sc_m($r['billed']) ?></td><td><?= sc_m($r['return_credit']) ?></td><td><?= sc_m($r['paid']) ?></td><td><b><?= sc_m($r['outstanding']) ?></b></td><td><span class="pp-badge <?= $r['status']==='active'?'':'warn' ?>"><?= sc_h(strtoupper($r['status'])) ?></span></td><td><a href="supplier_detail.php?id=<?= (int)$r['id'] ?>">History</a> • <a href="?edit=<?= (int)$r['id'] ?>">Edit</a></td></tr><?php endforeach;?><?php if(!$rows):?><tr><td colspan="8">No suppliers yet. Add the first real supplier when needed.</td></tr><?php endif;?></tbody></table></div></article></section><?php endif;?>
<div class="os-footer-note"><strong>Supplier identity rule:</strong> same/similar names are not auto-merged. Supplier code and internal ID remain the authoritative link for all purchasing activity.</div></main></div><script src="assets/business-collapsible.js?v=20260820-1" defer></script></body></html>
