<?php
declare(strict_types=1);

require_once __DIR__ . '/config/step10_services.php';

$error=null;$ctx=['organization_id'=>0];$legacy=['total'=>0,'mapped'=>0,'pending'=>0];$today=date('Y-m-d');$metrics=['orders'=>0,'order_value'=>0.0,'vp'=>0.0,'income'=>0.0,'royalty'=>0.0,'new_members'=>0,'renewals'=>0];$followups=[];$recent=[];$rev=defined('BUSINESS_REVERSED_SOURCE_SHEET')?BUSINESS_REVERSED_SOURCE_SHEET:'Manual Entry • Reversed';

try{
 $pdo=business_db();$ctx=step10_org_context($pdo);step10_ensure_tables($pdo);$orgId=(int)$ctx['organization_id'];$today=date('Y-m-d');$legacy=step10_legacy_state($pdo,$orgId);
 if($legacy['total']!==757||$legacy['mapped']!==757||$legacy['pending']!==0)throw new RuntimeException('Legacy source layer must remain reconciled at 757/757 before Today Center can run.');
 $queries=[
  'orders'=>"SELECT COUNT(*) FROM orders WHERE organization_id=? AND order_date=? AND COALESCE(source_sheet,'')<>?",
  'order_value'=>"SELECT COALESCE(SUM(net_amount),0) FROM orders WHERE organization_id=? AND order_date=? AND COALESCE(source_sheet,'')<>?",
  'vp'=>"SELECT COALESCE(SUM(volume_points),0) FROM volume_point_entries WHERE organization_id=? AND entry_date=? AND COALESCE(source_sheet,'')<>?",
  'income'=>"SELECT COALESCE(SUM(amount),0) FROM income_entries WHERE organization_id=? AND income_date=? AND COALESCE(source_sheet,'')<>?",
  'royalty'=>"SELECT COALESCE(SUM(amount),0) FROM royalty_entries WHERE organization_id=? AND royalty_date=? AND COALESCE(source_sheet,'')<>?",
  'new_members'=>"SELECT COUNT(*) FROM members WHERE organization_id=? AND join_date=? AND COALESCE(source_sheet,'')<>?",
  'renewals'=>"SELECT COUNT(*) FROM renewals WHERE organization_id=? AND renewal_date=? AND COALESCE(source_sheet,'')<>?",
 ];
 foreach($queries as $k=>$sql){$stmt=$pdo->prepare($sql);$stmt->execute([$orgId,$today,$rev]);$v=$stmt->fetchColumn();$metrics[$k]=in_array($k,['orders','new_members','renewals'],true)?(int)$v:(float)$v;}
 $stmt=$pdo->prepare("SELECT f.*,m.full_name member_name FROM business_followups f LEFT JOIN members m ON m.id=f.member_id AND m.organization_id=f.organization_id WHERE f.organization_id=? AND f.status='open' ORDER BY (f.due_date<?) DESC,f.due_date ASC,f.priority='urgent' DESC,f.id DESC LIMIT 12");$stmt->execute([$orgId,$today]);$followups=$stmt->fetchAll();
 $stmt=$pdo->prepare("SELECT id,event_type,entity_type,entity_id,created_at FROM audit_logs WHERE organization_id=? ORDER BY id DESC LIMIT 10");$stmt->execute([$orgId]);$recent=$stmt->fetchAll();
}catch(Throwable $e){$error=$e->getMessage();}

$dueToday=count(array_filter($followups,static fn($f)=>(string)$f['due_date']===date('Y-m-d')));$overdue=count(array_filter($followups,static fn($f)=>(string)$f['due_date']<date('Y-m-d')));
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>Today Center - Healthcare Wellness Club</title><link rel="stylesheet" href="assets/dashboard.css"><link rel="stylesheet" href="assets/step10.css"></head><body>
<header class="os-topbar"><div class="os-topbar-inner"><a class="os-brand" href="index.php"><img src="../img/logo.png" alt="Healthcare Wellness Club logo"><span><strong>Healthcare Wellness Club</strong><small>Business OS • Today Command Center</small></span></a><div class="os-top-actions"><a class="os-btn" href="global_search.php">⌕ Search</a><a class="os-btn" href="alerts_center.php">Alerts</a><a class="os-btn primary" href="data_entry_center.php">+ Add Data</a></div></div></header>
<div class="os-layout"><aside class="os-sidebar"><div class="os-nav-label">Business OS</div><nav class="os-nav"><a href="index.php"><i class="dot"></i>Dashboard</a><a class="active" href="today_center.php"><i class="dot"></i>Today Center</a><a href="global_search.php"><i class="dot"></i>Global Search</a><a href="alerts_center.php"><i class="dot"></i>Alerts & Follow-ups</a><a href="insights_center.php"><i class="dot"></i>Insights</a><a href="data_management.php"><i class="dot"></i>Data Management</a><a href="operations_center.php"><i class="dot"></i>Operations</a><a href="report_center.php"><i class="dot"></i>Reports</a></nav><div class="os-sidebar-status"><b><?= step10_h((new DateTimeImmutable($today))->format('l, d M Y')) ?></b><span>Daily facts + follow-ups + quick commands in one place.</span></div></aside><main class="os-main">
<section class="os-hero s10-hero"><div class="os-kicker">Step 10T–U • Today + Quick Command</div><h1>Start the day from one screen instead of opening five different workspaces.</h1><p>Today Center combines today’s normalized business facts, due follow-ups, latest system activity and the most-used create/search/report actions.</p><div class="os-status-row"><span class="os-chip <?= $error===null?'good':'' ?>"><?= $error===null?'TODAY CENTER LIVE':'Review required' ?></span><span class="os-chip good"><?= number_format($legacy['mapped']) ?> / 757 legacy mapped</span><span class="os-chip"><?= number_format($dueToday) ?> due today</span><span class="os-chip"><?= number_format($overdue) ?> overdue</span></div></section>
<?php if($error):?><div class="s10-alert bad"><strong>Today diagnostic:</strong> <?= step10_h($error) ?></div><?php else:?>
<section class="s10-kpis"><div class="s10-kpi"><small>Orders Today</small><strong><?= number_format((int)$metrics['orders']) ?></strong><span><?= step10_money($metrics['order_value']) ?> value</span></div><div class="s10-kpi"><small>VP Today</small><strong><?= step10_num($metrics['vp']) ?></strong><span>Normalized VP facts</span></div><div class="s10-kpi"><small>Income Today</small><strong><?= step10_money($metrics['income']) ?></strong><span>All income types</span></div><div class="s10-kpi"><small>Royalty Today</small><strong><?= step10_money($metrics['royalty']) ?></strong><span>Source royalty facts</span></div></section>
<section class="s10-grid"><article class="s10-card s10-span-7"><h2>Quick Commands</h2><p>One-click routes for the most common daily actions.</p><div class="os-report-grid"><a class="os-report" href="data_entry_center.php?tab=new_ums"><div class="os-report-head"><b>New UMS</b><em>WRITE</em></div><span>Create member + UMS lifecycle.</span><small>Add →</small></a><a class="os-report" href="data_entry_center.php?tab=vp"><div class="os-report-head"><b>Add VP</b><em>WRITE</em></div><span>Verified member-linked VP fact.</span><small>Add →</small></a><a class="os-report" href="data_entry_center.php?tab=order"><div class="os-report-head"><b>Add Order</b><em>WRITE</em></div><span>Order value, profit and VP.</span><small>Add →</small></a><a class="os-report" href="data_entry_center.php?tab=renewal"><div class="os-report-head"><b>Add Renewal</b><em>WRITE</em></div><span>Record UMS renewal.</span><small>Add →</small></a><a class="os-report" href="global_search.php"><div class="os-report-head"><b>Global Search</b><em>READ</em></div><span>Member, fact, report or command.</span><small>Search →</small></a><a class="os-report" href="insights_center.php"><div class="os-report-head"><b>Insights</b><em>LIVE</em></div><span>Month-to-month business movement.</span><small>Open →</small></a></div></article>
<aside class="s10-card s10-span-5"><h2>Today Snapshot</h2><p>Additional activity recorded on <?= step10_h(step10_date($today)) ?>.</p><div class="s10-list"><div class="s10-row"><div><b>New Members</b><small>Join date today</small></div><strong><?= number_format((int)$metrics['new_members']) ?></strong></div><div class="s10-row"><div><b>Renewals</b><small>Renewal date today</small></div><strong><?= number_format((int)$metrics['renewals']) ?></strong></div><div class="s10-row"><div><b>Follow-ups Due</b><small>Open tasks due today</small></div><strong><?= number_format($dueToday) ?></strong></div><div class="s10-row"><div><b>Overdue Follow-ups</b><small>Open tasks before today</small></div><strong><?= number_format($overdue) ?></strong></div></div></aside>
<article class="s10-card s10-span-7"><div class="os-title-row"><div><h2>Next Follow-ups</h2><p>Oldest/most urgent open commitments first.</p></div><a class="os-btn" href="alerts_center.php">Manage All</a></div><div class="s10-list"><?php if(!$followups):?><div class="s10-row"><div><b>No open follow-ups</b><small>Your queue is clear.</small></div><span class="s10-badge">CLEAR</span></div><?php endif;?><?php foreach($followups as $f):$isOver=(string)$f['due_date']<$today;?><div class="s10-row"><div><b><?= step10_h($f['title']) ?></b><small><?= step10_h(step10_date((string)$f['due_date'])) ?><?= $f['member_name']?' • '.step10_h($f['member_name']):'' ?></small></div><span class="s10-badge <?= $isOver?'bad':((string)$f['due_date']===$today?'warn':'blue') ?>"><?= $isOver?'OVERDUE':((string)$f['due_date']===$today?'TODAY':strtoupper((string)$f['priority'])) ?></span></div><?php endforeach;?></div></article>
<aside class="s10-card s10-span-5"><h2>Recent Activity</h2><p>Latest audit events across Business OS.</p><div class="s10-list"><?php if(!$recent):?><div class="s10-row"><div><b>No recent audit activity</b><small>Events will appear here.</small></div></div><?php endif;?><?php foreach($recent as $a):?><div class="s10-row"><div><b><?= step10_h(ucwords(str_replace('_',' ',(string)$a['event_type']))) ?></b><small><?= step10_h((string)($a['entity_type']??'system')) ?><?= $a['entity_id']?' #'.(int)$a['entity_id']:'' ?></small></div><strong><?= step10_h(substr((string)$a['created_at'],5,11)) ?></strong></div><?php endforeach;?></div></aside></section>
<?php endif;?></main></div></body></html>
