<?php
declare(strict_types=1);
require_once __DIR__ . '/business/config/role_portal_auth.php';
$error=null;$csrf='';
try{
    $pdo=role_portal_db();role_portal_ensure($pdo);security_step17_session_start();
    if(security_step17_total_users($pdo)===0){header('Location: business/setup_admin.php');exit;}
    $existing=security_step17_session_user($pdo,false);
    if($existing){header('Location: '.((int)$existing['must_change_password']===1?'change_password.php?required=1':role_portal_home($existing)));exit;}
    $csrf=security_step17_csrf();
    if($_SERVER['REQUEST_METHOD']==='POST'){
        security_step17_verify_csrf((string)($_POST['csrf']??''));
        $user=security_step17_login($pdo,(string)($_POST['email']??''),(string)($_POST['password']??''));
        header('Location: '.((int)$user['must_change_password']===1?'change_password.php?required=1':role_portal_home($user)));exit;
    }
}catch(Throwable $e){$error=$e->getMessage();}
?><!doctype html><html lang="en-IN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>Secure Login - Healthcare Wellness Club</title><link rel="stylesheet" href="pages/auth.css"></head><body class="auth-page">
<header class="auth-top"><a class="auth-brand" href="index.html"><img src="img/logo.png" alt="Healthcare Wellness Club"><span><strong>Healthcare Wellness Club</strong><small>Secure role-based access</small></span></a><nav class="auth-nav"><a class="auth-btn" href="index.html">Home</a><a class="auth-btn" href="shop/index.php">Products</a></nav></header>
<main class="auth-shell"><div class="auth-login-grid"><section class="auth-hero"><div class="auth-kicker">ADVANCED ROLE-BASED LOGIN</div><h1>One secure login. The right workspace for every role.</h1><p>Your role is read from the server after your credentials are verified. Selecting or changing a browser option can never upgrade an account to Administrator.</p><div class="role-grid"><article class="role-card"><div class="role-icon">A</div><h2>Administrator</h2><p>Full Business OS control.</p><ul><li>Users & permissions</li><li>Finance, inventory, reports</li><li>Security & deployment</li></ul></article><article class="role-card"><div class="role-icon">C</div><h2>Coach</h2><p>Restricted coaching workspace.</p><ul><li>Customers & follow-up</li><li>Public leads</li><li>Product guidance</li></ul></article><article class="role-card"><div class="role-icon">U</div><h2>Customer</h2><p>Private self-service portal.</p><ul><li>Own account</li><li>Product requests</li><li>Shop & tracking</li></ul></article></div></section><section class="auth-form-card"><div class="auth-kicker">SECURE SIGN IN</div><h2>Welcome back</h2><p>Enter the email and password assigned to your account. Your destination is selected automatically by server-side role.</p><?php if(isset($_GET['logged_out'])):?><div class="auth-alert good">You have signed out securely.</div><?php endif;?><?php if($error):?><div class="auth-alert" role="alert"><?=security_step17_h($error)?></div><?php endif;?><form class="auth-form" method="post" autocomplete="on"><input type="hidden" name="csrf" value="<?=security_step17_h($csrf)?>"><div class="auth-field"><label for="email">Email / Login ID</label><input class="auth-input" id="email" type="email" name="email" required autocomplete="username" autofocus></div><div class="auth-field"><label for="password">Password</label><div class="password-wrap"><input class="auth-input" id="password" type="password" name="password" required autocomplete="current-password"><button class="password-toggle" id="togglePassword" type="button" aria-label="Show password">Show</button></div><div style="display:flex;justify-content:flex-end;margin-top:8px"><a href="forgot_password.php" style="font-size:.78rem;font-weight:800">Forgot password?</a></div></div><button class="auth-submit" type="submit">Sign In Securely</button></form><div class="auth-security"><strong>Protected by STEP 17 security:</strong> secure password hashing, CSRF protection, failed-login throttling, temporary lockout, audited sessions, idle expiry and role permissions. Forgot-password requests use Administrator-assisted secure recovery.</div></section></div></main><script>document.getElementById('togglePassword')?.addEventListener('click',function(){const p=document.getElementById('password');const show=p.type==='password';p.type=show?'text':'password';this.textContent=show?'Hide':'Show';this.setAttribute('aria-label',show?'Hide password':'Show password')});</script></body></html>
