<?php
declare(strict_types=1);
require_once __DIR__ . '/business/config/role_trusted_devices.php';

$error=null;$success=null;$user=null;$devices=[];$currentTrusted=null;$csrf='';$orgId=0;
function td_when(?string $v):string{if(!$v)return '—';$t=strtotime($v);return $t?date('d M Y, h:i A',$t):$v;}
function td_client(string $ua):string{return role_trusted_default_label($ua);}

try{
    $pdo=role_portal_db();role_trusted_ensure($pdo);security_step17_session_start();
    $user=security_step17_session_user($pdo,true);
    if(!$user){header('Location: login.php');exit;}
    if((int)($user['must_change_password']??0)===1){header('Location: change_password.php?required=1');exit;}
    $ctx=security_step17_context($pdo);$orgId=(int)$ctx['organization_id'];$csrf=security_step17_csrf();

    if($_SERVER['REQUEST_METHOD']==='POST'){
        security_step17_verify_csrf((string)($_POST['csrf']??''));
        $action=(string)($_POST['action']??'');
        if($action==='trust_current'){
            $id=role_trusted_create_current($pdo,$user,(string)($_POST['current_password']??''),(string)($_POST['device_label']??''));
            $success='This device is now trusted for up to '.ROLE_TRUSTED_DEVICE_DAYS.' days. Trusted-device record #'.$id.' stores only a hash of the secret token.';
        }elseif($action==='revoke'){
            role_trusted_revoke($pdo,$user,(int)($_POST['device_id']??0));
            $success='Trusted device access was revoked. If this was the current browser, its login session remains active but it is no longer trusted for future sign-ins.';
        }
    }
    $currentTrusted=role_trusted_current($pdo,$orgId,(int)$user['id'],true);
    $devices=role_trusted_rows($pdo,$orgId,(int)$user['id']);
}catch(Throwable $e){$error=$e->getMessage();}
$home=$user?role_portal_home($user):'login.php';
?><!doctype html><html lang="en-IN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>Trusted Devices - Healthcare Wellness Club</title><link rel="stylesheet" href="pages/auth.css"><style>
.trust-layout{display:grid;grid-template-columns:minmax(300px,.72fr) minmax(0,1.28fr);gap:14px}.trust-card{border:1px solid var(--auth-line);border-radius:18px;background:rgba(255,255,255,.92);box-shadow:0 9px 27px rgba(36,72,52,.055);padding:19px}.trust-card.mint{background:linear-gradient(145deg,#fff,var(--auth-mint))}.trust-card.blue{background:linear-gradient(145deg,#fff,var(--auth-blue))}.trust-card.full{grid-column:1/-1}.trust-card h2{margin:0;font-size:1.04rem}.trust-card>p{margin:6px 0 0;color:var(--auth-muted);font-size:.78rem;line-height:1.55}.device-list{display:grid;gap:10px;margin-top:14px}.device{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:12px;padding:13px;border:1px solid #dfe8e3;border-radius:14px;background:#fff}.device.revoked{background:#f6f7f7}.device h3{margin:0;font-size:.88rem}.device-meta{margin-top:6px;color:#6d7d75;font-size:.7rem;line-height:1.6}.pill-row{display:flex;gap:7px;flex-wrap:wrap;margin-top:8px}.trust-pill{display:inline-flex;padding:5px 8px;border:1px solid #d7e6de;border-radius:999px;background:#eef9f3;color:#2f6c4d;font-size:.62rem;font-weight:850}.trust-pill.muted{background:#f1f3f4;color:#68766f}.trust-pill.warn{background:#fff6df;color:#7a6128}.revoke-btn{min-height:38px;padding:0 12px;border:1px solid #e5cfd2;border-radius:10px;background:#fff4f4;color:#8a474c;font-weight:800;cursor:pointer}@media(max-width:850px){.trust-layout{grid-template-columns:1fr}.trust-card.full{grid-column:auto}.device{grid-template-columns:1fr}}
</style></head><body class="auth-page"><header class="auth-top"><a class="auth-brand" href="<?=$home?>"><img src="img/logo.png" alt="Healthcare Wellness Club"><span><strong>Healthcare Wellness Club</strong><small>Trusted Devices • Secure Recognition</small></span></a><nav class="auth-nav"><a class="auth-btn" href="account.php">My Account</a><a class="auth-btn" href="security_alerts.php">Security Alerts</a><a class="auth-btn" href="<?=$home?>">My Portal</a><a class="auth-btn" href="logout.php">Sign Out</a></nav></header><main class="auth-shell"><section class="portal-head"><div><span class="role-badge">DEVICE SECURITY</span><h1>Trusted Devices</h1><p>Recognize your own browser securely without storing the secret device token in the database. You can revoke trust at any time.</p></div><div class="account-list" style="min-width:220px"><div class="account-row"><span>Current browser</span><b><?=$currentTrusted?'TRUSTED':'NOT TRUSTED'?></b></div><div class="account-row"><span>Trust duration</span><b><?=ROLE_TRUSTED_DEVICE_DAYS?> days max</b></div></div></section><?php if($error):?><div class="auth-alert" role="alert"><?=security_step17_h($error)?></div><?php endif;?><?php if($success):?><div class="auth-alert good"><?=security_step17_h($success)?></div><?php endif;?>
<div class="trust-layout"><section class="trust-card mint"><h2>Current Browser</h2><p>Trusting a device requires your current account password again. This prevents an unattended signed-in session from silently becoming trusted.</p><div class="account-list"><div class="account-row"><span>Detected as</span><b><?=security_step17_h(td_client((string)($_SERVER['HTTP_USER_AGENT']??'')))?></b></div><div class="account-row"><span>Trust status</span><b><?=$currentTrusted?'TRUSTED':'UNTRUSTED'?></b></div><?php if($currentTrusted):?><div class="account-row"><span>Trusted name</span><b><?=security_step17_h((string)$currentTrusted['device_label'])?></b></div><div class="account-row"><span>Expires</span><b><?=security_step17_h(td_when((string)$currentTrusted['expires_at']))?></b></div><?php endif;?></div><?php if(!$currentTrusted):?><form class="auth-form" method="post" autocomplete="off"><input type="hidden" name="csrf" value="<?=security_step17_h($csrf)?>"><input type="hidden" name="action" value="trust_current"><div class="auth-field"><label>Device Name</label><input class="auth-input" name="device_label" maxlength="120" value="<?=security_step17_h(td_client((string)($_SERVER['HTTP_USER_AGENT']??'')))?>" required></div><div class="auth-field"><label>Current Password</label><input class="auth-input" type="password" name="current_password" required autocomplete="current-password"></div><button class="auth-submit" type="submit">Trust This Device Securely</button></form><?php else:?><div class="auth-security"><strong>Trusted:</strong> future successful sign-ins from this browser can present its private HttpOnly device token. The server stores only the SHA-256 token hash.</div><?php endif;?></section>
<section class="trust-card blue"><h2>How Recognition Works</h2><p>Trusted-device recognition is an extra signal, not a replacement for your password.</p><div class="account-list"><div class="account-row"><span>Password</span><b>Still required</b></div><div class="account-row"><span>Device secret in database</span><b>Hash only</b></div><div class="account-row"><span>Browser cookie</span><b>HttpOnly + SameSite Strict</b></div><div class="account-row"><span>HTTPS production</span><b>Secure cookie</b></div><div class="account-row"><span>Unknown device</span><b>Security alert</b></div></div><div class="auth-security"><strong>Important:</strong> “Trusted” does not grant a higher role, bypass password checks, or bypass Administrator account locks.</div></section>
<section class="trust-card full"><h2>Trusted Device History</h2><p>Revoke any device you no longer own or recognize. Revoked and expired entries remain visible for security history.</p><div class="device-list"><?php foreach($devices as $d):$active=$d['revoked_at']===null&&strtotime((string)$d['expires_at'])>time();$isCurrent=$currentTrusted&&(int)$currentTrusted['id']===(int)$d['id'];?><article class="device <?=$active?'':'revoked'?>"><div><h3><?=security_step17_h((string)$d['device_label'])?></h3><div class="device-meta"><?=security_step17_h(td_client((string)($d['user_agent']??'')))?> • Added <?=security_step17_h(td_when((string)$d['created_at']))?> • Last used <?=security_step17_h(td_when((string)$d['last_used_at']))?><br>Created IP: <?=security_step17_h((string)($d['created_ip']?:'—'))?> • Last IP: <?=security_step17_h((string)($d['last_ip']?:'—'))?> • Expires: <?=security_step17_h(td_when((string)$d['expires_at']))?><?php if($d['revoke_reason']):?><br>Closed reason: <?=security_step17_h((string)$d['revoke_reason'])?><?php endif;?></div><div class="pill-row"><?php if($isCurrent):?><span class="trust-pill">CURRENT TRUSTED DEVICE</span><?php elseif($active):?><span class="trust-pill">TRUSTED</span><?php else:?><span class="trust-pill muted">REVOKED / EXPIRED</span><?php endif;?></div></div><?php if($active):?><form method="post" onsubmit="return confirm('Revoke trusted-device recognition for this device? This does not automatically close the current login session.')"><input type="hidden" name="csrf" value="<?=security_step17_h($csrf)?>"><input type="hidden" name="action" value="revoke"><input type="hidden" name="device_id" value="<?=(int)$d['id']?>"><button class="revoke-btn" type="submit">Revoke Trust</button></form><?php endif;?></article><?php endforeach;?><?php if(!$devices):?><div class="empty-state">No device has been trusted for this account yet.</div><?php endif;?></div></section></div></main></body></html>
