<?php
declare(strict_types=1);
require_once __DIR__ . '/../business/config/public_store_step23.php';
require_once __DIR__ . '/pwa_step24.php';
$error=null;$rows=[];$cats=[];$q=trim((string)($_GET['q']??''));$category=(int)($_GET['category']??0);
try{$pdo=ps23_db();ps23_ensure($pdo);$ctx=ps23_context($pdo);$set=ps23_settings($pdo,$ctx['organization_id']);if(empty($set['storefront_enabled']))throw new RuntimeException('The product portal is temporarily unavailable.');$rows=ps23_catalog($pdo,$ctx['organization_id'],$q,$category);$cats=ps23_categories($pdo,$ctx['organization_id']);}catch(Throwable $e){$error=$e->getMessage();}
function avlabel(string $status):string{return match($status){'available'=>'Available now','limited'=>'Limited stock • request allowed','unavailable'=>'Availability confirmed at review',default=>'Availability confirmed at review'};}
function avclass(string $status):string{return $status==='unavailable'?'review':$status;}
$description='Browse Healthcare Wellness Club products with source-listed MRP and VP, add them to cart, then submit an order request for Coach/Administrator confirmation.';
$schema=['@context'=>'https://schema.org','@type'=>'Store','name'=>'Healthcare Wellness Club Product Portal','description'=>$description,'url'=>s24_url('index.php'),'image'=>s24_origin().rtrim(dirname(s24_shop_path()),'/').'/img/logo.png'];
?><!doctype html><html lang="en-IN"><head><?php s24_head('Products - Healthcare Wellness Club',$description,'index.php','index,follow,max-image-preview:large',$schema);?></head><body>
<a class="skip-link" href="#main-content">Skip to main content</a>
<header class="store-top"><div class="store-bar"><a class="store-brand" href="../index.html" aria-label="Healthcare Wellness Club home"><img src="../img/logo.png" alt="Healthcare Wellness Club" width="42" height="42"><span><strong>Healthcare Wellness Club</strong><small>Public Product Portal</small></span></a><nav class="store-actions" aria-label="Store actions"><a class="store-btn" href="status.php">Track Request</a><a class="store-btn primary" href="cart.php">Cart (<span data-cart-count aria-live="polite">0</span>)</a></nav></div></header>
<main class="store-shell" id="main-content"><section class="store-hero" aria-labelledby="portal-title"><div class="store-kicker">CUSTOMER PRODUCT REQUEST PORTAL</div><h1 id="portal-title">Add products to your cart, then send your order request for confirmation.</h1><p>Prices use the current active India price-list MRP. Even when live club stock is not confirmed, you may add a product and submit a request; your Coach/Administrator reviews final availability, eligible pricing, taxes, delivery and payment before any sale is finalized.</p></section>
<?php if($error):?><div class="notice bad" role="alert"><?=ps23_h($error)?></div><?php else:?>
<form class="store-toolbar" method="get" role="search" aria-label="Search products"><label class="sr-only" for="productSearch">Search product, stock number or category</label><input class="store-input" id="productSearch" name="q" value="<?=ps23_h($q)?>" placeholder="Search product, stock number or category" enterkeyhint="search"><label class="sr-only" for="categoryFilter">Product category</label><select class="store-select" id="categoryFilter" name="category" aria-label="Product category"><option value="0">All categories</option><?php foreach($cats as $cat):?><option value="<?=(int)$cat['id']?>" <?=$category===(int)$cat['id']?'selected':''?>><?=ps23_h($cat['category_name'])?></option><?php endforeach;?></select><button class="store-btn primary" type="submit">Search</button></form>
<div class="notice">Order submission is a request, not an instant paid sale. Final availability is confirmed during Coach/Administrator review. Home delivery below 100 VP may carry the source-listed ₹100 delivery charge excluding taxes where applicable.</div>
<section class="store-grid" aria-label="Products"><?php foreach($rows as $row):?><article class="product-card"><div class="product-image"><?php if(!empty($row['verified_image'])):?><img src="<?=ps23_h($row['verified_image'])?>" alt="<?=ps23_h($row['product_name'])?>" loading="lazy" decoding="async" fetchpriority="low" width="640" height="540"><?php else:?><div class="product-placeholder" aria-hidden="true">HWC</div><?php endif;?></div><div class="product-body"><span class="pill <?=ps23_h(avclass((string)$row['availability_status']))?>"><?=ps23_h(avlabel((string)$row['availability_status']))?></span><div class="meta"><?=ps23_h($row['category_name'])?> • Stock <?=ps23_h($row['sku'])?></div><h2><a class="product-title-link" href="product.php?id=<?=(int)$row['id']?>"><?=ps23_h($row['product_name'])?></a></h2><div><span class="price"><?=ps23_money($row['mrp'])?></span> <span class="vp"><?=ps23_h(rtrim(rtrim(number_format((float)$row['volume_points'],3,'.',''),'0'),'.'))?> VP</span></div><div class="meta">Price effective <?=ps23_h($row['effective_from'])?> • MRP</div><div class="product-actions"><a class="store-btn" href="product.php?id=<?=(int)$row['id']?>" aria-label="View <?=ps23_h($row['product_name'])?> details">Details</a><button class="store-btn primary" type="button" data-add-product="<?=(int)$row['id']?>" aria-label="Add <?=ps23_h($row['product_name'])?> to cart">Add to Cart</button></div></div></article><?php endforeach;?><?php if(!$rows):?><div class="card empty" style="grid-column:1/-1">No matching active products.</div><?php endif;?></section>
<?php endif;?></main><footer class="store-footer">Healthcare Wellness Club • Product order requests only • Final confirmation by the club <span class="network-badge" data-network-status role="status" aria-live="polite">Online</span></footer><script src="<?=s24_h(s24_asset('store.js'))?>" defer></script></body></html>
