<?php
declare(strict_types=1);
require_once __DIR__ . '/../business/config/public_store_step23.php';
require_once __DIR__ . '/pwa_step24.php';
$error=null;$product=null;try{$pdo=ps23_db();ps23_ensure($pdo);$ctx=ps23_context($pdo);$product=ps23_product($pdo,$ctx['organization_id'],(int)($_GET['id']??0));}catch(Throwable $e){$error=$e->getMessage();}
function pd_av(string $status):string{return match($status){'available'=>'Available now','limited'=>'Limited stock • request allowed','unavailable'=>'Availability confirmed at review',default=>'Availability confirmed at review'};}
function pd_av_class(string $status):string{return $status==='unavailable'?'review':$status;}
$title=$product?(string)$product['product_name'].' - Healthcare Wellness Club':'Product - Healthcare Wellness Club';$description=$product?(string)$product['product_name'].' — source-listed MRP and VP from the current Healthcare Wellness Club product catalog.':'Healthcare Wellness Club product details.';$schema=null;
if($product){$availability=match((string)$product['availability_status']){'available'=>'https://schema.org/InStock','limited'=>'https://schema.org/LimitedAvailability',default=>'https://schema.org/PreOrder'};$schema=['@context'=>'https://schema.org','@type'=>'Product','name'=>(string)$product['product_name'],'sku'=>(string)$product['sku'],'category'=>(string)$product['category_name'],'url'=>s24_url('product.php?id='.(int)$product['id']),'offers'=>['@type'=>'Offer','priceCurrency'=>'INR','price'=>number_format((float)$product['mrp'],2,'.',''),'availability'=>$availability,'url'=>s24_url('product.php?id='.(int)$product['id'])]];if(!empty($product['verified_image']))$schema['image']=(string)$product['verified_image'];}
?><!doctype html><html lang="en-IN"><head><?php s24_head($title,$description,$product?'product.php?id='.(int)$product['id']:'index.php','index,follow,max-image-preview:large',$schema);?></head><body>
<a class="skip-link" href="#main-content">Skip to main content</a><header class="store-top"><div class="store-bar"><a class="store-brand" href="index.php" aria-label="Back to Healthcare Wellness Club products"><img src="../img/logo.png" alt="Healthcare Wellness Club" width="42" height="42"><span><strong>Healthcare Wellness Club</strong><small>Product Detail</small></span></a><nav class="store-actions" aria-label="Store actions"><a class="store-btn" href="index.php">Products</a><a class="store-btn primary" href="cart.php">Cart (<span data-cart-count aria-live="polite">0</span>)</a></nav></div></header>
<main class="store-shell" id="main-content"><?php if($error):?><div class="notice bad" role="alert"><?=ps23_h($error)?></div><?php else:?><section class="two-col" aria-label="Product detail"><article class="card"><div class="product-image" style="border-radius:16px;max-height:520px"><?php if(!empty($product['verified_image'])):?><img src="<?=ps23_h($product['verified_image'])?>" alt="<?=ps23_h($product['product_name'])?>" decoding="async" fetchpriority="high" width="900" height="760"><?php else:?><div class="product-placeholder" style="width:130px;height:130px" aria-hidden="true">HWC</div><?php endif;?></div></article><aside class="card"><div class="store-kicker"><?=ps23_h($product['category_name'])?></div><h1><?=ps23_h($product['product_name'])?></h1><p class="meta">Stock No. <?=ps23_h($product['sku'])?><?=!empty($product['pack_size'])?' • '.ps23_h($product['pack_size'].' '.$product['pack_unit']):''?></p><span class="pill <?=ps23_h(pd_av_class((string)$product['availability_status']))?>"><?=ps23_h(pd_av((string)$product['availability_status']))?></span><div style="margin:18px 0"><div class="price"><?=ps23_money($product['mrp'])?></div><div class="vp"><?=ps23_h(rtrim(rtrim(number_format((float)$product['volume_points'],3,'.',''),'0'),'.'))?> VP</div><div class="meta">Source-listed MRP • effective <?=ps23_h($product['effective_from'])?></div></div><div class="notice">You may add this product to your request even when live stock is not confirmed. Your Coach/Administrator confirms final availability, eligible pricing, taxes, delivery and payment before the order becomes a final sale.</div><button class="store-btn primary" style="width:100%" type="button" data-add-product="<?=(int)$product['id']?>" aria-label="Add <?=ps23_h($product['product_name'])?> to cart">Add to Cart</button></aside></section><?php endif;?></main><footer class="store-footer">Healthcare Wellness Club • Customer Product Request Portal <span class="network-badge" data-network-status role="status" aria-live="polite">Online</span></footer><script src="<?=s24_h(s24_asset('store.js'))?>" defer></script></body></html>
