const HWC_CART_KEY='hwc_public_cart_v1';let hwcInstallPrompt=null;
function hwcCart(){try{const value=JSON.parse(localStorage.getItem(HWC_CART_KEY)||'[]');return Array.isArray(value)?value:[]}catch(e){return[]}}
function hwcSaveCart(value){try{localStorage.setItem(HWC_CART_KEY,JSON.stringify(value))}catch(e){}hwcSyncCartBadge()}
function hwcAdd(productId,qty=1){const cart=hwcCart();const row=cart.find(item=>Number(item.product_id)===Number(productId));if(row)row.qty=Math.min(20,Number(row.qty||0)+qty);else cart.push({product_id:Number(productId),qty:Math.min(20,qty)});hwcSaveCart(cart);return cart}
function hwcSet(productId,qty){let cart=hwcCart();qty=Math.max(0,Math.min(20,Number(qty)||0));const index=cart.findIndex(item=>Number(item.product_id)===Number(productId));if(qty===0&&index>=0)cart.splice(index,1);else if(index>=0)cart[index].qty=qty;else if(qty>0)cart.push({product_id:Number(productId),qty});hwcSaveCart(cart)}
function hwcRemove(productId){hwcSet(productId,0)}function hwcClear(){hwcSaveCart([])}
function hwcSyncCartBadge(){const count=hwcCart().reduce((sum,row)=>sum+Number(row.qty||0),0);document.querySelectorAll('[data-cart-count]').forEach(element=>{element.textContent=String(count);element.setAttribute('aria-label',`${count} item${count===1?'':'s'} in cart`)})}
function hwcAnnounce(message){let live=document.getElementById('hwcLiveRegion');if(!live){live=document.createElement('div');live.id='hwcLiveRegion';live.className='sr-only';live.setAttribute('role','status');live.setAttribute('aria-live','polite');live.setAttribute('aria-atomic','true');document.body.appendChild(live)}live.textContent='';window.setTimeout(()=>{live.textContent=message},30)}
function hwcNetworkState(){const online=navigator.onLine;document.querySelectorAll('[data-network-status]').forEach(element=>{element.textContent=online?'Online':'Offline';element.classList.toggle('offline',!online)});if(!online)hwcAnnounce('You are offline. Live availability, checkout and request tracking need an internet connection.')}
async function hwcAuthNavigation(){const link=document.querySelector('.store-auth-link');if(!link)return;try{const response=await fetch('../session_status.php',{cache:'no-store',credentials:'same-origin'});if(!response.ok)return;const state=await response.json();if(state.authenticated){link.textContent='My Portal';link.href='../'+state.portal;link.setAttribute('aria-label',`Open ${state.role} portal for ${state.name}`)}else{link.textContent='Login';link.href='../login.php'}}catch(e){link.textContent='Login';link.href='../login.php'}}
function hwcStoreNavigation(){const bar=document.querySelector('.store-bar');if(!bar||bar.querySelector('.store-site-nav'))return;const nav=document.createElement('nav');nav.className='store-site-nav';nav.setAttribute('aria-label','Main website navigation');const links=[['../index.html','Home'],['../pages/about.html','About'],['../pages/services.html','Services'],['../pages/success.html','Stories'],['index.php','Products'],['../pages/contact.html','Contact Club'],['../login.php','Login']];for(const [href,label] of links){const a=document.createElement('a');a.href=href;a.textContent=label;a.className='store-site-link';if(label==='Products'){a.classList.add('active');a.setAttribute('aria-current','page')}if(label==='Login')a.classList.add('store-auth-link');nav.appendChild(a)}const actions=bar.querySelector('.store-actions');if(actions)bar.insertBefore(nav,actions);else bar.appendChild(nav);hwcAuthNavigation()}
function hwcInstallButton(){if(!hwcInstallPrompt||document.querySelector('[data-install-pwa]'))return;const actions=document.querySelector('.store-actions');if(!actions)return;const button=document.createElement('button');button.type='button';button.className='store-btn install';button.dataset.installPwa='1';button.textContent='Install App';button.setAttribute('aria-label','Install Healthcare Wellness Club product portal');button.addEventListener('click',async()=>{if(!hwcInstallPrompt)return;hwcInstallPrompt.prompt();await hwcInstallPrompt.userChoice.catch(()=>null);hwcInstallPrompt=null;button.remove()});actions.appendChild(button)}
window.addEventListener('beforeinstallprompt',event=>{event.preventDefault();hwcInstallPrompt=event;hwcInstallButton()});window.addEventListener('appinstalled',()=>{hwcInstallPrompt=null;document.querySelector('[data-install-pwa]')?.remove();hwcAnnounce('Healthcare Wellness Club product portal installed.')});window.addEventListener('online',hwcNetworkState);window.addEventListener('offline',hwcNetworkState);
window.addEventListener('load',()=>{if('serviceWorker' in navigator){navigator.serviceWorker.register('./sw.js',{scope:'./'}).catch(()=>{})}});
document.addEventListener('DOMContentLoaded',()=>{hwcStoreNavigation();hwcSyncCartBadge();hwcNetworkState();hwcInstallButton();document.querySelectorAll('[data-add-product]').forEach(button=>{button.addEventListener('click',()=>{hwcAdd(button.dataset.addProduct,1);const oldText=button.textContent;button.textContent='Added ✓';hwcAnnounce('Product added to cart.');window.setTimeout(()=>{button.textContent=oldText},900)})});document.querySelectorAll('[data-add-combo]').forEach(button=>{button.addEventListener('click',()=>{const ids=String(button.dataset.addCombo||'').split(',').map(Number).filter(id=>id>0);ids.forEach(id=>hwcAdd(id,1));const oldText=button.textContent;button.textContent='Complete Combo Added ✓';hwcAnnounce('All combo products added to cart.');window.setTimeout(()=>{button.textContent=oldText},1200)})})});
document.addEventListener('DOMContentLoaded',()=>{const form=document.getElementById('checkoutForm');if(!form)return;const shell=form.closest('.store-shell');if(!shell)return;shell.classList.add('checkout-shell');const hero=shell.querySelector('.store-hero');if(hero)hero.classList.add('checkout-hero');const layout=shell.querySelector('.two-col');if(layout)layout.classList.add('checkout-layout');const formCard=form.closest('.card');if(formCard)formCard.classList.add('checkout-form-card');const summary=layout?.querySelector('aside.card');if(summary)summary.classList.add('checkout-summary-card');const progress=document.createElement('nav');progress.className='cart-progress checkout-progress';progress.setAttribute('aria-label','Checkout progress');progress.innerHTML='<span class="done"><b>✓</b>Shopping Cart</span><i></i><span class="active"><b>2</b>Customer Details</span><i></i><span><b>3</b>Request Confirmation</span>';shell.insertBefore(progress,shell.firstChild)});
document.addEventListener('DOMContentLoaded',()=>{const trackInput=document.getElementById('orderCode');const orderCode=document.querySelector('.order-code');if(!trackInput&&!orderCode)return;const shell=(trackInput||orderCode).closest('.store-shell');if(!shell)return;shell.classList.add('tracking-shell');const hero=shell.querySelector('.store-hero');if(hero)hero.classList.add('tracking-hero');if(trackInput){trackInput.closest('.card')?.classList.add('premium-track-card')}if(orderCode){shell.classList.add('confirmation-state');const result=shell.querySelector('.two-col');if(result)result.classList.add('tracking-result');const progress=document.createElement('nav');progress.className='cart-progress confirmation-progress';progress.setAttribute('aria-label','Order request progress');progress.innerHTML='<span class="done"><b>✓</b>Cart</span><i></i><span class="done"><b>✓</b>Details</span><i></i><span class="active"><b>✓</b>Request Saved</span>';shell.insertBefore(progress,shell.firstChild);const success=document.createElement('div');success.className='confirmation-mark';success.innerHTML='<span>✓</span><div><strong>Thank you!</strong><small>Your product request has been received successfully.</small></div>';result?.insertBefore(success,result.firstChild)}});
