-- STEP 14 COMPLETE — Purchase & Supplier Management System
-- Healthcare Wellness Club Business OS
-- MySQL 8+ / MariaDB compatible.

USE healthcare_wellness_club;

CREATE TABLE IF NOT EXISTS purchase_suppliers (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  organization_id BIGINT UNSIGNED NOT NULL,
  supplier_code VARCHAR(60) NOT NULL,
  supplier_name VARCHAR(190) NOT NULL,
  contact_person VARCHAR(150) NULL,
  mobile VARCHAR(40) NULL,
  email VARCHAR(190) NULL,
  gstin VARCHAR(40) NULL,
  address_text TEXT NULL,
  payment_terms_days INT UNSIGNED NOT NULL DEFAULT 0,
  notes TEXT NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'active',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_purchase_supplier_org FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE,
  UNIQUE KEY uq_purchase_supplier_code (organization_id, supplier_code),
  KEY idx_purchase_supplier_name (organization_id, supplier_name),
  KEY idx_purchase_supplier_status (organization_id, status)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS purchase_orders (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  organization_id BIGINT UNSIGNED NOT NULL,
  club_id BIGINT UNSIGNED NULL,
  supplier_id BIGINT UNSIGNED NOT NULL,
  po_number VARCHAR(80) NOT NULL,
  order_date DATE NOT NULL,
  expected_date DATE NULL,
  currency_code CHAR(3) NOT NULL DEFAULT 'INR',
  subtotal DECIMAL(16,2) NOT NULL DEFAULT 0,
  notes TEXT NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'draft',
  raw_source_id BIGINT UNSIGNED NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_purchase_order_org FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE,
  CONSTRAINT fk_purchase_order_club FOREIGN KEY (club_id) REFERENCES clubs(id) ON DELETE SET NULL,
  CONSTRAINT fk_purchase_order_supplier FOREIGN KEY (supplier_id) REFERENCES purchase_suppliers(id) ON DELETE RESTRICT,
  CONSTRAINT fk_purchase_order_currency FOREIGN KEY (currency_code) REFERENCES currencies(currency_code),
  CONSTRAINT fk_purchase_order_raw FOREIGN KEY (raw_source_id) REFERENCES raw_source_records(id) ON DELETE SET NULL,
  UNIQUE KEY uq_purchase_po_number (organization_id, po_number),
  KEY idx_purchase_order_supplier (organization_id, supplier_id, order_date),
  KEY idx_purchase_order_status (organization_id, status, expected_date)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS purchase_order_items (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  organization_id BIGINT UNSIGNED NOT NULL,
  purchase_order_id BIGINT UNSIGNED NOT NULL,
  product_id BIGINT UNSIGNED NOT NULL,
  listing_id BIGINT UNSIGNED NOT NULL,
  product_name_snapshot VARCHAR(190) NOT NULL,
  stock_no_snapshot VARCHAR(100) NULL,
  ordered_quantity DECIMAL(16,3) NOT NULL,
  estimated_unit_cost DECIMAL(16,2) NULL,
  line_amount DECIMAL(16,2) NOT NULL DEFAULT 0,
  notes TEXT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_purchase_order_item_org FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE,
  CONSTRAINT fk_purchase_order_item_order FOREIGN KEY (purchase_order_id) REFERENCES purchase_orders(id) ON DELETE CASCADE,
  CONSTRAINT fk_purchase_order_item_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE RESTRICT,
  CONSTRAINT fk_purchase_order_item_listing FOREIGN KEY (listing_id) REFERENCES product_market_listings(id) ON DELETE RESTRICT,
  KEY idx_purchase_order_item_order (organization_id, purchase_order_id),
  KEY idx_purchase_order_item_product (organization_id, product_id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS purchase_bills (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  organization_id BIGINT UNSIGNED NOT NULL,
  club_id BIGINT UNSIGNED NULL,
  supplier_id BIGINT UNSIGNED NOT NULL,
  purchase_order_id BIGINT UNSIGNED NULL,
  invoice_number VARCHAR(120) NOT NULL,
  invoice_date DATE NOT NULL,
  due_date DATE NULL,
  currency_code CHAR(3) NOT NULL DEFAULT 'INR',
  subtotal DECIMAL(16,2) NOT NULL DEFAULT 0,
  discount_amount DECIMAL(16,2) NOT NULL DEFAULT 0,
  tax_amount DECIMAL(16,2) NOT NULL DEFAULT 0,
  other_charges DECIMAL(16,2) NOT NULL DEFAULT 0,
  total_amount DECIMAL(16,2) NOT NULL DEFAULT 0,
  return_credit DECIMAL(16,2) NOT NULL DEFAULT 0,
  paid_amount DECIMAL(16,2) NOT NULL DEFAULT 0,
  receipt_status VARCHAR(30) NOT NULL DEFAULT 'pending',
  payment_status VARCHAR(30) NOT NULL DEFAULT 'unpaid',
  notes TEXT NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'active',
  raw_source_id BIGINT UNSIGNED NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_purchase_bill_org FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE,
  CONSTRAINT fk_purchase_bill_club FOREIGN KEY (club_id) REFERENCES clubs(id) ON DELETE SET NULL,
  CONSTRAINT fk_purchase_bill_supplier FOREIGN KEY (supplier_id) REFERENCES purchase_suppliers(id) ON DELETE RESTRICT,
  CONSTRAINT fk_purchase_bill_po FOREIGN KEY (purchase_order_id) REFERENCES purchase_orders(id) ON DELETE SET NULL,
  CONSTRAINT fk_purchase_bill_currency FOREIGN KEY (currency_code) REFERENCES currencies(currency_code),
  CONSTRAINT fk_purchase_bill_raw FOREIGN KEY (raw_source_id) REFERENCES raw_source_records(id) ON DELETE SET NULL,
  UNIQUE KEY uq_purchase_supplier_invoice (organization_id, supplier_id, invoice_number),
  KEY idx_purchase_bill_due (organization_id, status, payment_status, due_date),
  KEY idx_purchase_bill_supplier (organization_id, supplier_id, invoice_date)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS purchase_bill_items (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  organization_id BIGINT UNSIGNED NOT NULL,
  purchase_bill_id BIGINT UNSIGNED NOT NULL,
  purchase_order_item_id BIGINT UNSIGNED NULL,
  product_id BIGINT UNSIGNED NOT NULL,
  listing_id BIGINT UNSIGNED NOT NULL,
  product_name_snapshot VARCHAR(190) NOT NULL,
  stock_no_snapshot VARCHAR(100) NULL,
  billed_quantity DECIMAL(16,3) NOT NULL,
  received_quantity DECIMAL(16,3) NOT NULL DEFAULT 0,
  unit_cost DECIMAL(16,2) NOT NULL,
  line_discount DECIMAL(16,2) NOT NULL DEFAULT 0,
  tax_amount DECIMAL(16,2) NOT NULL DEFAULT 0,
  line_total DECIMAL(16,2) NOT NULL,
  notes TEXT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_purchase_bill_item_org FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE,
  CONSTRAINT fk_purchase_bill_item_bill FOREIGN KEY (purchase_bill_id) REFERENCES purchase_bills(id) ON DELETE CASCADE,
  CONSTRAINT fk_purchase_bill_item_po_item FOREIGN KEY (purchase_order_item_id) REFERENCES purchase_order_items(id) ON DELETE SET NULL,
  CONSTRAINT fk_purchase_bill_item_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE RESTRICT,
  CONSTRAINT fk_purchase_bill_item_listing FOREIGN KEY (listing_id) REFERENCES product_market_listings(id) ON DELETE RESTRICT,
  KEY idx_purchase_bill_item_bill (organization_id, purchase_bill_id),
  KEY idx_purchase_bill_item_product (organization_id, product_id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS purchase_receipts (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  organization_id BIGINT UNSIGNED NOT NULL,
  club_id BIGINT UNSIGNED NULL,
  supplier_id BIGINT UNSIGNED NOT NULL,
  purchase_bill_id BIGINT UNSIGNED NOT NULL,
  receipt_number VARCHAR(90) NOT NULL,
  receipt_date DATE NOT NULL,
  delivery_reference VARCHAR(190) NULL,
  notes TEXT NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'posted',
  raw_source_id BIGINT UNSIGNED NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_purchase_receipt_org FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE,
  CONSTRAINT fk_purchase_receipt_club FOREIGN KEY (club_id) REFERENCES clubs(id) ON DELETE SET NULL,
  CONSTRAINT fk_purchase_receipt_supplier FOREIGN KEY (supplier_id) REFERENCES purchase_suppliers(id) ON DELETE RESTRICT,
  CONSTRAINT fk_purchase_receipt_bill FOREIGN KEY (purchase_bill_id) REFERENCES purchase_bills(id) ON DELETE RESTRICT,
  CONSTRAINT fk_purchase_receipt_raw FOREIGN KEY (raw_source_id) REFERENCES raw_source_records(id) ON DELETE SET NULL,
  UNIQUE KEY uq_purchase_receipt_number (organization_id, receipt_number),
  KEY idx_purchase_receipt_bill (organization_id, purchase_bill_id, receipt_date)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS purchase_receipt_items (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  organization_id BIGINT UNSIGNED NOT NULL,
  purchase_receipt_id BIGINT UNSIGNED NOT NULL,
  purchase_bill_item_id BIGINT UNSIGNED NOT NULL,
  product_id BIGINT UNSIGNED NOT NULL,
  listing_id BIGINT UNSIGNED NOT NULL,
  quantity_received DECIMAL(16,3) NOT NULL,
  unit_cost DECIMAL(16,2) NOT NULL,
  batch_code VARCHAR(120) NOT NULL,
  manufacture_date DATE NULL,
  expiry_date DATE NULL,
  inventory_transaction_id BIGINT UNSIGNED NOT NULL,
  inventory_batch_id BIGINT UNSIGNED NOT NULL,
  returned_quantity DECIMAL(16,3) NOT NULL DEFAULT 0,
  use_as_profit_cost TINYINT(1) NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_purchase_receipt_item_org FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE,
  CONSTRAINT fk_purchase_receipt_item_receipt FOREIGN KEY (purchase_receipt_id) REFERENCES purchase_receipts(id) ON DELETE CASCADE,
  CONSTRAINT fk_purchase_receipt_item_bill_item FOREIGN KEY (purchase_bill_item_id) REFERENCES purchase_bill_items(id) ON DELETE RESTRICT,
  CONSTRAINT fk_purchase_receipt_item_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE RESTRICT,
  CONSTRAINT fk_purchase_receipt_item_listing FOREIGN KEY (listing_id) REFERENCES product_market_listings(id) ON DELETE RESTRICT,
  CONSTRAINT fk_purchase_receipt_item_tx FOREIGN KEY (inventory_transaction_id) REFERENCES inventory_transactions(id) ON DELETE RESTRICT,
  CONSTRAINT fk_purchase_receipt_item_batch FOREIGN KEY (inventory_batch_id) REFERENCES inventory_batches(id) ON DELETE RESTRICT,
  KEY idx_purchase_receipt_item_receipt (organization_id, purchase_receipt_id),
  KEY idx_purchase_receipt_item_bill_item (organization_id, purchase_bill_item_id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS purchase_payments (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  organization_id BIGINT UNSIGNED NOT NULL,
  supplier_id BIGINT UNSIGNED NOT NULL,
  purchase_bill_id BIGINT UNSIGNED NOT NULL,
  payment_date DATE NOT NULL,
  amount DECIMAL(16,2) NOT NULL,
  payment_method VARCHAR(50) NOT NULL DEFAULT 'other',
  reference_no VARCHAR(150) NULL,
  notes TEXT NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'active',
  raw_source_id BIGINT UNSIGNED NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_purchase_payment_org FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE,
  CONSTRAINT fk_purchase_payment_supplier FOREIGN KEY (supplier_id) REFERENCES purchase_suppliers(id) ON DELETE RESTRICT,
  CONSTRAINT fk_purchase_payment_bill FOREIGN KEY (purchase_bill_id) REFERENCES purchase_bills(id) ON DELETE RESTRICT,
  CONSTRAINT fk_purchase_payment_raw FOREIGN KEY (raw_source_id) REFERENCES raw_source_records(id) ON DELETE SET NULL,
  KEY idx_purchase_payment_bill (organization_id, purchase_bill_id, status, payment_date),
  KEY idx_purchase_payment_supplier (organization_id, supplier_id, status, payment_date)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS purchase_returns (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  organization_id BIGINT UNSIGNED NOT NULL,
  supplier_id BIGINT UNSIGNED NOT NULL,
  purchase_bill_id BIGINT UNSIGNED NOT NULL,
  return_number VARCHAR(90) NOT NULL,
  return_date DATE NOT NULL,
  reason TEXT NOT NULL,
  total_credit DECIMAL(16,2) NOT NULL DEFAULT 0,
  status VARCHAR(30) NOT NULL DEFAULT 'posted',
  raw_source_id BIGINT UNSIGNED NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_purchase_return_org FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE,
  CONSTRAINT fk_purchase_return_supplier FOREIGN KEY (supplier_id) REFERENCES purchase_suppliers(id) ON DELETE RESTRICT,
  CONSTRAINT fk_purchase_return_bill FOREIGN KEY (purchase_bill_id) REFERENCES purchase_bills(id) ON DELETE RESTRICT,
  CONSTRAINT fk_purchase_return_raw FOREIGN KEY (raw_source_id) REFERENCES raw_source_records(id) ON DELETE SET NULL,
  UNIQUE KEY uq_purchase_return_number (organization_id, return_number),
  KEY idx_purchase_return_bill (organization_id, purchase_bill_id, return_date)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS purchase_return_items (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  organization_id BIGINT UNSIGNED NOT NULL,
  purchase_return_id BIGINT UNSIGNED NOT NULL,
  purchase_receipt_item_id BIGINT UNSIGNED NOT NULL,
  product_id BIGINT UNSIGNED NOT NULL,
  quantity_returned DECIMAL(16,3) NOT NULL,
  unit_cost DECIMAL(16,2) NOT NULL,
  credit_amount DECIMAL(16,2) NOT NULL,
  inventory_transaction_id BIGINT UNSIGNED NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_purchase_return_item_org FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE,
  CONSTRAINT fk_purchase_return_item_return FOREIGN KEY (purchase_return_id) REFERENCES purchase_returns(id) ON DELETE CASCADE,
  CONSTRAINT fk_purchase_return_item_receipt_item FOREIGN KEY (purchase_receipt_item_id) REFERENCES purchase_receipt_items(id) ON DELETE RESTRICT,
  CONSTRAINT fk_purchase_return_item_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE RESTRICT,
  CONSTRAINT fk_purchase_return_item_tx FOREIGN KEY (inventory_transaction_id) REFERENCES inventory_transactions(id) ON DELETE RESTRICT,
  KEY idx_purchase_return_item_return (organization_id, purchase_return_id),
  KEY idx_purchase_return_item_receipt_item (organization_id, purchase_receipt_item_id)
) ENGINE=InnoDB;
